### ISSUE TITLE
Verification 

### ISSUE THREAD

**Issue by amaizenshtein** [ytti/oxidized#1050]
Hi Guys,

I'm trying to use oxs to push set of commands to my devices
So I basically created a file named username and set cli commands, and run this command

oxs -x username --verbose --threads 5 —group Arista

How I can make sure that all commands were pushed and nothing has failed ? without going device by device to verify?

**Comment by wk** [comment]
Presumably, you'd be running `Oxidized` for configuration collection as well, and would be able to compare the diff (before/after) to see if everything has taken place. Alternatively, you could log the interaction with the device to a file and review (or grep through) the results.

I'll close this issue here as it pertains primarily to `oxidized-script` rather than `oxidized`, please re-open it there if it's still relevant.
