### ISSUE TITLE
git garbage collection

### ISSUE THREAD

**Issue by momorientes** [ytti/oxidized#108]
I have oxidized polling >100 Devices for quite some time (~1 year) and noticed that the .git directory kept taking up inodes. In numbers: 3340120 and it began to become a problem.  
After a git gc --aggressive run the inode count was  reduced to 31.  
Adding gc.auto to the git config could solve this problem.

**Comment by ytti** [comment]
In July 2014 we changed from 'grit' to 'rugged', so if you've had same oxidized before that, you're using different git code.

You might want to try in latest release if issue still persists.

**Comment by ytti** [comment]
Is this issue still relevant?

**Comment by ytti** [comment]
Closed due to inactivity.

**Comment by Alexanderis** [comment]
Hi team,

I am using git output and I have noticed the same issue reported here.
The system ran out of inodes a few days ago and the culprit was identified as oxidized with ~1.5mil taken by the repo.

I have 260+ devices and they get backed up once every hour:

```
~:/etc/oxidized/configs.git/default.git$ find ./ | wc -l
56757

~:/etc/oxidized/configs.git/default.git$ sudo kill -STOP 30881
~:/etc/oxidized/configs.git/default.git$ sudo git reflog expire --expire=now --all; sudo git gc --prune=now
Counting objects: 56536, done.
Compressing objects: 100% (56491/56491), done.
Writing objects: 100% (56536/56536), done.
Total 56536 (delta 41809), reused 0 (delta 0)
Removing duplicate objects: 100% (256/256), done.
~:/etc/oxidized/configs.git/default.git$ sudo kill -CONT 30881

~:/etc/oxidized/configs.git/default.git$ find ./ | wc -l
20
```

I can see the file count increase after restarting the process: 
```
 oxidized -v
0.16.3

 while true; do echo $(find /etc/oxidized/configs.git | wc -l); echo "sleeping for 5 seconds"; sleep 5; done
1038
sleeping for 5 seconds
1047
sleeping for 5 seconds
1055
sleeping for 5 seconds
```

```
output:
   default: git
   git:
     single_repo: true
     user: oxidized
     email: test@test.co,
     repo: "/etc/oxidized/configs.git/default.git"
```

Any way to make git use a sane amount of inodes other then having a cron job run with "sudo git reflog expire --expire=now --all; sudo git gc --prune=now" ?

**Comment by ytti** [comment]
I'm not sure how git works, but it may be that we create always bogus data here: https://github.com/ytti/oxidized/blob/master/lib/oxidized/output/git.rb#L182

Even if we don't create commit, we're writing the blob and index, just so that we can compare if tree changed. 

We probably need to find way to do this without creating useless inodes, or at least clean afterwards.

**Comment by wk** [comment]
Unfortunately, per libgit2/libgit2#3247 there is no intention to add support for git reflog expiry or GC to libgit2, and by extension to Rugged, which the git output uses. 

This will have to be an external process that runs `git gc` occasionally to compact the refs.

**Comment by ytti** [comment]
We could fetch the latest version, compare the strings, and not try to write same blob. This would stop trash from occurring. 
Now we kinda streamline the process and always just do the same thing, and let git figure it out.

**Comment by ytti** [comment]
This may fix the problem: https://github.com/ytti/oxidized/tree/refactor-git_gc

**Comment by ytti** [comment]
To test

1. ensure you are currently increasing inode/file count in the git repo
2. ensure you no longer increase it after the patch
