### ISSUE TITLE
A server is already running. Check /root/.config/oxidized/pid

### ISSUE THREAD

**Issue by chasgames** [ytti/oxidized#1084]
Hello

I'm using the official docker container, but every few days, oxidised just stops working with "A server is already running. Check /root/.config/oxidized/pid".

I think i fixed it before by deleting the file or emptying the pid file.

But now I cant get it to work, I even tried re-creating it with docker-compose down --rmi all, docker-compose up -d
 
but i still get this in the logs:
oxidized_1  | Nov  3 10:25:44 6f0dc6d1c8b4 syslog-ng[17]: syslog-ng starting up; version='3.5.3'
oxidized_1  | A server is already running. Check /root/.config/oxidized/pid
oxidized_1  | A server is already running. Check /root/.config/oxidized/pid
oxidized_1  | A server is already running. Check /root/.config/oxidized/pid
oxidized_1  | A server is already running. Check /root/.config/oxidized/pid
oxidized_1  | A server is already running. Check /root/.config/oxidized/pid
oxidized_1  | A server is already running. Check /root/.config/oxidized/pid
oxidized_1  | A server is already running. Check /root/.config/oxidized/pid
oxidized_1  | A server is already running. Check /root/.config/oxidized/pid
oxidized_1  | A server is already running. Check /root/.config/oxidized/pid
oxidized_1  | A server is already running. Check /root/.config/oxidized/pid

my compose file looks like this

oxidized:
  restart: unless-stopped
  image: oxidized/oxidized:latest
  ports:
    - "8888:8888"
  environment:
    CONFIG_RELOAD_INTERVAL: 86400
  volumes:
    - "./oxidized:/root/.config/oxidized"

Thanks

**Comment by laf** [comment]
Maybe oxidized is crashing. Check dmesg and/or enable debug in oxidized and check the logs after you see the already running message to see if anything further is recorded.

**Comment by chasgames** [comment]
Thanks Laf, I enabled debug, but my logs directory is still empty after a restart, unless they all get directed into "docker-compose logs" ?

Unfortunately I temporarily fixed it again by removing the pid file and updating oxidized with docker-compose pull.

I usually get this message every few days, so I will update again with some more info like dmesg.

**Comment by udha** [comment]
I don't know if related but Ctrl+c hasn't been closing properly for me in either direct install nor if I attach to docker container. With direct install of example after ^C I can only get to shell by then backgrounding and running kill %1 then deleting the pidfile manually. Have been too busy to look into it but since I'm not the only one seeing this I'll check it out again tomorrow and see what's up

**Comment by chasgames** [comment]
I got this again, i removed the pid file again and pulled and restarted which fixed again.

In the broken state, curl dmesg shows some errors like this:

```
[356439.942500] rrdtool[7490]: segfault at 8 ip 00007fee7649aa30 sp 00007ffec95658a0 error 4 in librrd.so.4.3.5[7fee76466000+51000]
[356443.203526] rrdtool[5452]: segfault at 8 ip 00007fbf612cfa30 sp 00007ffcb74bb380 error 4 in librrd.so.4.3.5[7fbf6129b000+51000]
[356446.329417] rrdtool[6687]: segfault at 8 ip 00007ff584abba30 sp 00007ffdde7a7bc0 error 4 in librrd.so.4.3.5[7ff584a87000+51000]
[356469.141764] rrdtool[7058]: segfault at 8 ip 00007fdde447fa30 sp 00007ffc52d8acb0 error 4 in librrd.so.4.3.5[7fdde444b000+51000]
[356478.176568] rrdtool[7191]: segfault at 8 ip 00007fe535b9aa30 sp 00007ffe8e971f80 error 4 in librrd.so.4.3.5[7fe535b66000+51000]
[356483.125138] br-07b1c825d2b4: port 2(veth96f2f6b) entered disabled state
[356483.230471] br-07b1c825d2b4: port 2(veth96f2f6b) entered disabled state
[356483.234439] device veth96f2f6b left promiscuous mode
[356483.234458] br-07b1c825d2b4: port 2(veth96f2f6b) entered disabled state
[356483.839211] br-07b1c825d2b4: port 2(vethf10a470) entered blocking state
[356483.839215] br-07b1c825d2b4: port 2(vethf10a470) entered disabled state
[356483.839340] device vethf10a470 entered promiscuous mode
[356483.839468] IPv6: ADDRCONF(NETDEV_UP): vethf10a470: link is not ready
[356483.839472] br-07b1c825d2b4: port 2(vethf10a470) entered blocking state
[356483.839474] br-07b1c825d2b4: port 2(vethf10a470) entered forwarding state
[356484.122610] br-07b1c825d2b4: port 2(vethf10a470) entered disabled state
[356487.282588] IPv6: ADDRCONF(NETDEV_CHANGE): vethf10a470: link becomes ready
[356487.282658] br-07b1c825d2b4: port 2(vethf10a470) entered blocking state
[356487.282661] br-07b1c825d2b4: port 2(vethf10a470) entered forwarding state
[356487.443690] br-07b1c825d2b4: port 1(veth75cf24c) entered disabled state
[356487.559254] br-07b1c825d2b4: port 1(veth75cf24c) entered disabled state
[356487.569969] device veth75cf24c left promiscuous mode
[356487.569987] br-07b1c825d2b4: port 1(veth75cf24c) entered disabled state
[356487.759680] br-07b1c825d2b4: port 1(veth7e749d4) entered blocking state
[356487.759683] br-07b1c825d2b4: port 1(veth7e749d4) entered disabled state
[356487.759785] device veth7e749d4 entered promiscuous mode
[356487.759942] IPv6: ADDRCONF(NETDEV_UP): veth7e749d4: link is not ready
[356487.759945] br-07b1c825d2b4: port 1(veth7e749d4) entered blocking state
[356487.759947] br-07b1c825d2b4: port 1(veth7e749d4) entered forwarding state
[356488.136447] IPv6: ADDRCONF(NETDEV_CHANGE): veth7e749d4: link becomes ready
[361831.214363] docker0: port 1(vethb92d59c) entered disabled state
[361831.387686] docker0: port 1(vethb92d59c) entered disabled state
[361831.400868] device vethb92d59c left promiscuous mode
[361831.400890] docker0: port 1(vethb92d59c) entered disabled state
[361831.817748] overlayfs: upper fs needs to support d_type. This is an invalid configuration.
[361831.971466] overlayfs: upper fs needs to support d_type. This is an invalid configuration.
[361832.003693] overlayfs: upper fs needs to support d_type. This is an invalid configuration.
```

not sure if these errors are related

**Comment by bbrendon** [comment]
I have the same issue. I thought it was my understanding of docker. I'll keep and eye out.

**Comment by wk** [comment]
The current version of the oxidized docker container has undergone significant changes since the issue was opened. Tagging the issue `user_pending` and closing it for now/ Feel free to re-open it if you can reproduce it on a current version of the container with a fresh copy of relevant logs from both the host and oxidized itself.

**Comment by teemupulliainen** [comment]
I'm running into the same issue with with a locally built container (built from https://github.com/ytti/oxidized a week or so ago). Removing the pidfile manually fixes it every time, though. 

I thought it was just related to killed/crashing containers but apparently the pid file is (occasionally?) left behind even when stopping gracefully with docker stop.

However, I worked around this by simply removing the pidfile in method check_pid in cli.rb. Might not have been the optimal solution though :)

          + puts "A server is already running. Deleting #{pidfile}"
          + File.delete(pidfile)
---
           - puts "A server is already running. Check #{pidfile}"
           - exit(1)

Logs during docker stop/start:

```
...
D, [2018-07-20T12:21:26.102508 #23] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 10
 Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2018-07-20 12:21:26 +0000 ===
 Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2018-07-20 12:21:26 +0000 ===- Goodbye!

 Goodbye!
*** Shutting down runit daemon (PID 15)...
*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...
Jul 20 12:21:26 31387643963f syslog-ng[9]: syslog-ng shutting down; version='3.5.6'
Jul 20 12:21:26 31387643963f syslog-ng[9]: EOF on control channel, closing connection;
*** Init system aborted.
*** Killing all processes...
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Jul 20 12:21:30 31387643963f syslog-ng[9]: syslog-ng starting up; version='3.5.6'
Jul 20 12:21:31 31387643963f syslog-ng[9]: EOF on control channel, closing connection;
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 15
Jul 20 12:21:31 31387643963f cron[21]: (CRON) INFO (pidfile fd = 3)
Jul 20 12:21:31 31387643963f cron[21]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
**A server is already running. Deleting /root/.config/oxidized/pid**
I, [2018-07-20T12:21:32.310751 #22]  INFO -- : Oxidized starting, running as pid 22
...
```

**Comment by wk** [comment]
The PID file should be deleted upon graceful shutdown. Re-opening this.

**Comment by wk** [comment]
@chasgames @teemupulliainen Could you test if this still breaks and leaves behind a PID file in the latest version when 'rest' in config is set to 'false' (i.e., web components are not loaded) in your envrionment?

**Comment by teemupulliainen** [comment]
@wk Can't seem to reproduce the issue in the latest version with 'rest' set to false.

**Comment by Dmulligen** [comment]
the problem is with Puma webserver its already running the most simple thing to do on ubuntu 16.04/18.04
- run command : ps ax 
-  look for Puma x.x.x (txp://172.0.0.1:8888) [oxidized] 
-  look for the proces PID of the puma webserver 
- run the command : kill [PID nummer][something like [kill 15002]
run the oxidized script again 

or in a docker container  :

- run command :  cd 
-  type : exit for stopping oxidized procceses
- type again : exit for again stopping oxidized
- type again : exit for move out of the docker container.
- go back in the container and run the oxidized script 

didnt this work repeat this but then reboot the container

**Comment by wk** [comment]
@teemupulliainen I'm guessing ytti/oxidized-web#161 introduced a condition where stopping puma (when it runs to serve the RESTful API) prevents the at_exit block in ```oxidized/cli.rb``` from being executed and cleaning up the pidfile.

**Comment by candlerb** [comment]
I have an oxidized server running in an lxd container (not docker) and I see the same thing.  Since this is a persistent container, I have been able to narrow down the problem.

I am starting oxidized with a simple systemd unit:

```
[Unit]
Description=Oxidized - Network Device Configuration Backup Tool
After=network-online.target multi-user.target
Wants=network-online.target

[Service]
ExecStart=/usr/local/bin/oxidized
User=oxidized
Group=oxidized
KillSignal=SIGINT
Restart=always
RestartSec=30

[Install]
WantedBy=multi-user.target
```

And it is failing to start with this error:

```
A server is already running. Check /home/oxidized/.config/oxidized/pid
```

Well, the pidfile exists, but the process it refers to does not:

```
# ls -l /home/oxidized/.config/oxidized/pid
-rw-r--r-- 1 oxidized oxidized 3 Sep 23 15:04 /home/oxidized/.config/oxidized/pid

root@ix-oxidized:~# cat /home/oxidized/.config/oxidized/pid
486

root@ix-oxidized:~# ps auxwww | grep 486
root     31496  0.0  0.0  14620  1032 ?        S+   10:44   0:00 grep --color=auto 486
root@ix-oxidized:~#
```

So I made a change to `/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/cli.rb` to try and find out why:

```
    def check_pid
      if pidfile?
        ps = pid_status(pidfile)
        case ps
        when :running, :not_owned
          puts "A server is already running (#{ps}). Check #{pidfile}"
          exit(1)
        when :dead
          File.delete(pidfile)
        end
      end
    end
```

and I get the result:

```
A server is already running (not_owned). Check /home/oxidized/.config/oxidized/pid
```

Hmm. So it thinks there *is* a process 486.  What if I try the the `pid_status` logic manually?

```
root@ix-oxidized:~# irb
irb(main):001:0> Process.kill(0, 9999)
Errno::ESRCH: No such process
	from (irb):1:in `kill'
	from (irb):1
	from /usr/bin/irb:11:in `<main>'
irb(main):002:0> Process.kill(0, 486)
=> 1
irb(main):003:0>
root@ix-oxidized:~# su -l oxidized
oxidized@ix-oxidized:~$ irb
irb(main):001:0> Process.kill(0, 9999)
Errno::ESRCH: No such process
	from (irb):1:in `kill'
	from (irb):1
	from /usr/bin/irb:11:in `<main>'
irb(main):002:0> Process.kill(0, 486)
Errno::EPERM: Operation not permitted
	from (irb):2:in `kill'
	from (irb):2
	from /usr/bin/irb:11:in `<main>'
irb(main):003:0>
```

WTF??  Aside: it doesn't seem to be [documented](https://apidock.com/ruby/Process/kill/class) what the return value of 1 from `Process.kill` means, but I note the underlying `kill(2)` call can only return 0 or -1.

What if I do it directly from the shell without ruby?

```
root@ix-oxidized:~# kill -0 9999; echo $?
bash: kill: (9999) - No such process
1
root@ix-oxidized:~# kill -0 486; echo $?
0
root@ix-oxidized:~# ps auxwww | grep 486
root     31596  0.0  0.0  14620  1088 ?        S+   10:53   0:00 grep --color=auto 486
root@ix-oxidized:~# strace kill -0 486 2>&1 | grep kill
execve("/bin/kill", ["kill", "-0", "486"], [/* 12 vars */]) = 0
kill(486, SIG_0)                        = 0
```

The same! There is no process 486, but kill disagrees.

Now, this is inside a lxd container with its own pid namespace.  What about on the main OS which is hosting the container?

```
root@ix-mon2:~# ps auxwww | grep 486
root     19716  0.0  0.0  14228   968 pts/10   S+   11:56   0:00 grep --color=auto 486
root@ix-mon2:~# kill -0 9999
bash: kill: (9999) - No such process
root@ix-mon2:~# kill -0 486
bash: kill: (486) - No such process
```

That looks fine.

But the fundamental issue is: there's an "invisible" stale process in the container.  If it affects both docker and lxd containers then it would appear most likely to be a kernel issue.  However I'll raise it on an lxc/lxd forum and see if anyone else has seen anything like it.

**Comment by candlerb** [comment]
[Forum link](https://discuss.linuxcontainers.org/t/ghost-pid-inside-container/2851)

**Comment by candlerb** [comment]
And for completeness: inside the container, there is no `/proc/486` either.

```
root@ix-oxidized:~# ls /proc | grep 486
root@ix-oxidized:~#
```

This might be a workaround: if we are running under Linux and `/proc/<pid>` does not exist then we know the process is gone.

**Comment by candlerb** [comment]
Turns out the ghost process was actually a thread:

```
root@ix-oxidized:~# ps auxwww -L | grep 486 | grep -v grep
root       480   486  0.0    3  0.0 277088  5988 ?        Ssl  Sep29   0:00 /usr/lib/policykit-1/polkitd --no-debug
```

But changing oxidized to check for the existence of `/proc/<pid>` would not help.  Bizarrely, `ls /proc` does not list 486, but `ls /proc/486` *does* still work.

```
root@ix-oxidized:~# ls /proc | grep 486
root@ix-oxidized:~# ls /proc/486
attr        comm             fd        map_files   net            pagemap      schedstat     stat     timerslack_ns
autogroup   coredump_filter  fdinfo    maps        ns             patch_state  sessionid     statm    uid_map
auxv        cpuset           gid_map   mem         numa_maps      personality  setgroups     status   wchan
cgroup      cwd              io        mountinfo   oom_adj        projid_map   smaps         syscall
clear_refs  environ          limits    mounts      oom_score      root         smaps_rollup  task
cmdline     exe              loginuid  mountstats  oom_score_adj  sched        stack         timers
root@ix-oxidized:~# ls -l /proc/486/exe
lrwxrwxrwx 1 root root 0 Oct  4 11:15 /proc/486/exe -> /usr/lib/policykit-1/polkitd
root@ix-oxidized:~#
```

**Comment by candlerb** [comment]
There is some info [here](https://unix.stackexchange.com/questions/434092/how-does-linux-tell-threads-apart-from-child-processes) on distinguishing between pids and tids.

Looking at the 'ghost' pid 486, you can see it has a different Tgid (480) which is the real process that spawned it.

```
root@ix-oxidized:~# cat /proc/486/stat
486 (gmain) S 1 480 480 0 -1 4194368 361 0 1 0 0 0 0 0 20 0 3 0 3262 283738112 1497 18446744073709551615 4194304 4202692 140727313633600 0 0 0 2147221247 4096 0 0 0 0 -1 2 0 0 0 0 0 6303168 6304336 22978560 140727313641312 140727313641352 140727313641352 140727313641435 0
root@ix-oxidized:~# head /proc/486/status
Name:	gmain
Umask:	0022
State:	S (sleeping)
Tgid:	480
Ngid:	0
Pid:	486
PPid:	1
TracerPid:	0
Uid:	0	0	0	0
Gid:	0	0	0	0
```

Whereas the 'real' process 480 has a Tgid which is also 480.

```
root@ix-oxidized:~# cat /proc/480/stat
480 (polkitd) S 1 480 480 0 -1 4194304 361 0 1 0 0 0 0 0 20 0 3 0 3254 283738112 1497 18446744073709551615 4194304 4202692 140727313633600 0 0 0 2 4096 0 0 0 0 17 3 0 0 4 0 0 6303168 6304336 22978560 140727313641312 140727313641352 140727313641352 140727313641435 0
root@ix-oxidized:~# head /proc/480/status
Name:	polkitd
Umask:	0022
State:	S (sleeping)
Tgid:	480
Ngid:	0
Pid:	480
PPid:	1
TracerPid:	0
Uid:	0	0	0	0
Gid:	0	0	0	0
```

So a solution would be: if you can read `/proc/<pid>/status`, and the Tgid line contains a number which is *different* to the pid, then the pid can be safely assumed to be not a real process, so return `:dead` which allows the pidfile to be deleted.

Note: although `/proc/<pid>/stat` might be easier to parse, beware that column 2 [can contain whitespace](https://github.com/dagwieers/dstat/issues/120).  Whether it can also include a right-parenthesis I have not tested.

**Comment by vowywowy** [comment]
This seems to be happening almost at random when the container is restarted and the pid file is still present. 

In my case, when watchtower was updating the container, sometimes the pid file would remain and cause issues because I had a persistent volume where oxidized could store its files.

My workaround for this issue, without changing any docker config, is to modify the oxidized config and simply add a `pid:`  declaration to place the pid file in a non persistent location in the container. ie. The troublesome pid file would then be deleted and recreated upon container restart.

**To be explicit, I added `pid: "/var/pid"` to my oxidized config and haven't had any issues since.**

**Comment by joshbenner** [comment]
Moving the pid into the docker container will only work around this issue if the container is destroyed and recreated. However, doing a docker stop/start or a docker restart does not destroy the container, therefore the pid file still remains.

**Comment by tyler-8** [comment]
I've tried two different ways of defining the `pid` file. I've mounted a volume on the host filesystem to be the target `pid` location: the error still happens.

And I tried @vowywowy 's method of defining the `pid` inside the container but the issue happens there as well. The only temporary fix that seems to work is either destroying and recreating the container, or using `docker exec -it <container_id> bash` and doing an `rm -f /var/pid` to clear the `pid` file. But inevitably, I'll have to do it again after the next restart/reboot.

**Comment by candlerb** [comment]
You are correct.  I tried to explain the problem before:

* Oxidized starts.  It writes its pid (let's say "486") into the pidfile
* The container is stopped and restarted
* On container start, pids are allocated from 1 upwards again - but not exactly the same
* When oxidized wants to start, the original process obviously has gone.  But it finds that there is some other process or thread with id 486.
* Oxidized aborts startup, thinking (wrongly) that you are trying to start a second oxidized process when the first one is already running.

It doesn't matter where the pidfile is stored: the pidfile is being written and read correctly.  The problem is that after container restart, if some other process or thread starts up whose id is the same as the old oxidized process, oxidized won't start.

I've thought about the options for this a bit more, and I think the best approach is to use a lockfile instead of a pidfile.  When the process starts, create the lockfile (if it doesn't exist) and obtain an exclusive lock; if this fails then abort.  When the process dies, the lock is automatically dropped by the OS.

This has the advantage of being portable (it should work on BSD as well as Linux), and solves the problem properly: all you are trying to avoid is two instances of oxidized running at once.

**Comment by timwsuqld** [comment]
I agree with @candlerb about a lockfile, as we have this issue with the PID checking as well.

**Comment by timwsuqld** [comment]
I'm using the following in my docker-compose to make it work (modify the path as required). Of course, this means we _could_ end up with 2 instances running, but I have to just let docker take care of that.
```yaml
command: bash -c 'rm /tmp/pid; /sbin/my_init'
```

**Comment by nekatak** [comment]
I have the same issue with the latest docker container. The moment you define a `pid` in the config file the container fails to start across reboots (always) with an error:
`oxidized[37367]: A server is already running. Check /root/.config/oxidized/pid`

Of course the issue is reproduced across restarts of the systemd docker.service.

The before mentioned workaround solves it for me as also "solved" it assigning `pid: /dev/null`

**Comment by techallan** [comment]
Same issue.
I'm completely new to docker, so I can't really provide detailed debug information, but I need to empty **/etc/oxidized/pid** after every reboot to get the container up and running again.

**Comment by tuaninbox** [comment]
I found that pid file in oxidized folder is not empty

$ ls
config  configs  crashes  logs  model  pid

after removing this file I can start container normally.

**Comment by FlorianHeigl** [comment]
issue persists

**Comment by candlerb** [comment]
I have a reasonable solution for this now: move the pidfile to a ramdisk, and it's always gone when the system starts.

Create `/etc/tmpfiles.d/oxidized.conf` with the following content:

```
#Type Path            Mode UID      GID        Age Argument
d     /run/oxidized   0755 oxidized oxidized   -   -
```

Then change the oxidized config file so it says

```
pid: "/run/oxidized/pid"
```

Reboot/restart.

(This works fine for an incus container, which has systemd in it. For a docker container, I guess you could remove the pidfile at startup, although TBH I think pidfile checking should be disabled completely when running under docker and when not running daemonized)
