### ISSUE TITLE
Automatically save device configuration when running Oxidized

### ISSUE THREAD

**Issue by nktl** [ytti/oxidized#1090]
Hi,

It would be great if we could automatically write/save/commit device configuration to persistent memory as a part of Oxidized run (so every night or so). This would be useful for hardware where by default configuration changes are not saved - like on Cisco, where 'write' / 'copy run start' command has to be run manually. It occasionally happens that someone forgets to commit the configuration and changes then could be lost after unexpected restart (power outage, device crash), possibly breaking stuff.

Is this possible to achieve by defining some post-run command for the device class in Oxidized?
Or is it not possible to do this easily at the moment?

**Comment by laf** [comment]
This is done per os model. For instance for IOS this is done by do show run rather than show conf and is already part of that model: https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/ios.rb#L118

I can't comment for every model out there but if the device has the ability to show the running unsaved config then the model can make the most of it.

**Comment by nktl** [comment]
Thank you for the prompt response!
I did add 

```
  cmd 'write memory' do |cfg|
    comment cfg
  end
```

To ios and iosxr models ('copy run start' there prompts for the file name, which confuses oxidized).

And:

```
  cmd 'copy run start' do |cfg|
    comment cfg
  end
```

To nxos model (where 'write memory' command does not exist) - and all of this seems to work very well.

Is it straightforward to expose some flag in global config file (like saveconfig: true) that would then control if the copy/write part of the code in the model is actually executed? I would be more than happy to do this, but unfortunately have got zero Ruby skills.

**Comment by laf** [comment]
Ah so you're asking to have the ability to actually save the config rather than just backup the current running one.

I would say that this can be done as you've already shown and yes it should be a global config. Here's a PR which adds a new config option: https://github.com/ytti/oxidized/pull/1089/files

I don't do ruby but maybe:

```ruby
if vars :saveconfig
  cmd 'copy run start' do |cfg|
    comment cfg
  end
end
```

saveconfig: true

**Comment by wk** [comment]
While the implementation detailed by @laf is perfectly feasible, and I see the original author has found a solution that fits their needs - for the oxidized project itself, it goes against the [philosophy](https://github.com/ytti/oxidized/pull/894#issuecomment-312418888) of not modifying device state. Oxidized is generally expected to be provided with read-only credentials on devices from which it archives configuration.

In the current vision, you might consider instead scheduling (via e.g. crontab) a separate task to do this using [oxidized-script](https://github.com/ytti/oxidized-script), which should allow you to simply execute arbitrary commands against your devices, such as a forced configuration save.
