### ISSUE TITLE
Adding a Model?

### ISSUE THREAD

**Issue by cstrock** [ytti/oxidized#1173]
This is probably a total beginner question, but basically I'm trying to add support for Dell X1052.  So, I've created a copy of powerconnect.rb name x1052.rb in the same folder.  Then I do docker build, but that file doesn't end up in the image, and the I get errors about not finding an x1052 model. (I figure the current dell rb can serve as a starting point)

So I'm guessing there is a proper way to add a new model .rb, but I just can't find it.  I checked here, reddit and libre.  I'm just not seeing it.

Any advice?

**Comment by Fhajad** [comment]
Question: What's the error you're getting? Did you change the class name up top from PowerConnect to x1052?

**Comment by cstrock** [comment]
When I run the docker build command, the file I created doesn't make it in to the docker container, so I'm unable to test the actual file.  So my first question is more about how to get the file added to container's build.  Then I'm going to work on the actual device script.  Does that make sense?

**Comment by laf** [comment]
When you run docker build, is it definitely against the directory you've added the file to?

**Comment by cstrock** [comment]
I believe so, I add the file in the same folder where I edit the powerconnect.rb to work properly (btw, you need to add a "cmd 'enable'" before the show running config on that for it to work).

So the edited powerconnect.rb ends up in the build, but not the x1052.rb file I created.  Wasn't sure if there was a command I needed to add include additional files or not, or if it should just add everything under /oxidized basically.

**Comment by laf** [comment]
I've tested this and it doesn't end up in the docker file if you haven't commited the changes so add the file, commit and re-run build / run docker commands it should work fine @cstrock .

Let me know if we can close this issue down?

**Comment by cstrock** [comment]
I'll need to figure out how to commit the changes so the file builds then, but if you've tested it, that's fine w/ me to close it.  I'll try just adding the file directly in the image for now until I can make it work, then I'll look in to committing.  Thanks for the help.

**Comment by laf** [comment]
Should be as simple as:

```bash
git add <filename>
git commit -am 'Added new model X'
```

That should be all you need.

**Comment by wk** [comment]
@cstrock since you've opened this issue, additional documentation on the subject of [creating and extending models](https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md) was written. Please take a look there, as it contains an answer to your questions.

In relation to the oxidized docker container, the easiest way to add new models without rebuilding the container, assuming you've started your container with `-v /etc/oxidized:/root/.config/oxidized`, is to simply create a `model` directory in `/etc/oxidized` on the docker host, and place the model file there. Files present in that directory will be loaded first, before any models that are included in the docker container itself.

**Comment by laf** [comment]
Thanks for the info @wk.

Closing this down as all bases should now be covered.
