### ISSUE TITLE
Huawei config includes current date and time

### ISSUE THREAD

**Issue by craig** [ytti/oxidized#1218]
When using Oxidized for the Huawei AntiDDoS8000 Platform (vrp), the configuration always contains the current date and time, thus it is being bumped every run, making a lot of unneeded commits to git.

This illustrates the issue:

```
$ ssh admin@huawei
User Authentication
Password: 

*************************************************************************
*                         Copyright (C) 2007-2016                       *
*                     Huawei Technologies Co., Ltd.                     *
*                           All rights reserved.                        *
*               Without the owner's prior written consent,              *
*        no decompiling or reverse-engineering shall be allowed.        *
*************************************************************************


Info: The max number of VTY users is 10, and the number
      of current VTY users on line is 1.
      The current login time is 2018-03-14 19:42:04+01:00.
<myhostname>display version
2018-03-14 19:42:14.040 +01:00
Huawei Technologies Versatile Routing Platform Software
VRP (R) Software, Version 5.160 (AntiDDoS8030 V500R001C20SPC300)
```

This happens for all commands:
```
<myhostname>display arp all
2018-03-14 19:43:44.320 +01:00
```

**Comment by wk** [comment]
This is the result of a non-default configuration for Huawei devices. 

To un-do it, enter `system-view` mode and execute the `undo timestamp enable` command. This will eliminate the addition of a timestamp after each CLI `display` command.

**Comment by laf** [comment]
@craig Can this be closed based on the info above please?

**Comment by craig** [comment]
@wk thanks for the hint, the command is incorrect, but I found the correct one:

`timestamp disable`

The timestamp feature is enabled by default on this firmware, so there is nothing in the config about it. If it's disabled via that command, only then does it show up. I had searched for anything time-related in the config, and couldn't find anything, also not in the docs. Thanks, this really helped me out, it now works flawlessly. :+1: 

Maybe we could still filter lines with a timestamp so other don't have this issue?

**Comment by wk** [comment]
Interesting, thanks for following up on this @craig.

This is not the case with some products, such as the CloudEngine product line (VRP V100, V200 - timestamp defaults to disabled) but appears to be the case for at least for some of the the security products, including the IPS module, NIP product line, and the AntiDDoS in this issue (VRP V500 - timestamp defaults to enabled).

It might be interesting to establish if the default is different across product lines, VRP versions, or follows some other segmentation.

A curious design choice, since as a consequence the command required  (`feature disable` vs. `undo feature enable`) for configuring the state of a specific feature depends not on the intent of the operator but rather on its default state.
