### ISSUE TITLE
Keep device history when adding group

### ISSUE THREAD

**Issue by denniswa** [ytti/oxidized#1224]
Hi,

I just created a few groups and added a device in each group when I noticed that the device revision history for that node was lost (device used to be in default).
Is there any way to avoid this when adding existing devices to a new group?

From the log I can see that the device now gets a new config like this
'Configuration updated for legacy/ybtug.sunet.se'
looking back in the log is used to be in the default group
'Configuration updated for /ybtug.sunet.se'

Thanks!

**Comment by vppencilsharpener** [comment]
If you are storing the configs in a git repository and viewing the history from there, you should be able to perform a `git mv` to move the old files to the new group location. 

The process would be:
1. Stop Oxidized
1. Add the groups to the device
1. Update the git repository
1. Start Oxidized

Because Oxidized uses a bare repository you need to clone it first. Then move the files to the new group directory, stage and commit then finally push back to the repository. 

The commit history should follow the file move.
