### ISSUE TITLE
FreeBSD install updates

### ISSUE THREAD

**Issue by datriumadmin** [ytti/oxidized#1247]
I used the following to install oxidized on FreeBSD 11.1.  It was necessary to manually add net-telnet.
pkg install rubygem-net-telnet rubygem-oxidized rubygem-oxidized-script rubygem-oxidized-web

**Comment by wk** [comment]
@nickhilliard as the maintainer of the FreeBSD rubygem-oxidized* package, could you please take a look if you have a dependency on rubygem-net-telnet in place, and update the package if you do not?

Please reply to this issue when you, so that the FreeBSD installation instructions can be updated to mention the native package.

**Comment by nickhilliard** [comment]
PR filed on FreeBSD bugzilla for this:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=227118

**Comment by wk** [comment]
@nickhilliard Thanks! Please update ytti/oxidized#1249 when the FreeBSD PR is resolved. That will trigger a pull for a documentation update mentioning the port in the FreeBSD section, and also close this issue together with it.
