### ISSUE TITLE
Per-Command Breakouts

### ISSUE THREAD

**Issue by dotwaffle** [ytti/oxidized#125]
At the moment, all the commands run by oxidized appear in the same file, named after the device it logged into.

I was wondering if there was any desire to further split this out? For instance, perhaps the hostname could be a directory and there would be a number of files in there -- "showrun" "showinventory" etc. You could either give a command an alias or it would automatically create one by stripping non-alpha characters from the command name and use that instead?

Would that be a welcome addition?

**Comment by ytti** [comment]
We already support this thanks to persistence of @RichiH 

In your model you can do something like

cmd 'bar' do |cfg|
  cfg.type = 'xyzzy-bar'
  cfg
end

And storage backend can then use this type as it pleases. Git backend either creates new repo by that name, or by optional configuration uses existing repo.

What we don't do yet, but what we may need to support is 'extension models', now if you place ios.rb in ~/.config/oxidized/model/ios.rb it is loaded instead of global/shipping ios.rb model. However, you might want to use latest and greatest shipping model with some local tinkering/tuning. I think it's like 2h work to support that.

**Comment by ytti** [comment]
Any update?

**Comment by dotwaffle** [comment]
Sort of, I started screaming and bashing my head in with a soda can and a ruby dev came over to help me.

I re-implemented oxidized in 222 lines of bash (as we only talk to Arista for this, it was fairly simple)

So, erm... Sorry :S I didn't get far enough with it to warrant merging!
