### ISSUE TITLE
why did you make strange link in oxidized and oxidized-web?

### ISSUE THREAD

**Issue by yuri-zubov** [ytti/oxidized#1292]
in my opinion, `oxidized.gemspec` must have 
```
 s.add_runtime_dependency 'oxidized-web'
```
in `oxidized-web.gemspec` line
```
 s.add_runtime_dependency 'oxidized',            '~> 0.21.0'
```
 must be replaced with 
```
 s.add_development_dependency 'oxidized',            '~> 0.21.0'
```
or maybe must be deleted

**Comment by wk** [comment]
Here's the outlay:
* `oxidized` does not require `oxidized-web` for runtime. Not everyone wants a web interface (and its dependencies), hence no dependency in `oxidized.gemspec`. This allows a user to deploy the `oxidized` gem *without* deploying the `oxidized-web` gem.
* `oxidized-web` does not have its own runtime at all, and relies on `oxidized` to run, as it is bootstrapped from [oxidized/lib/oxidized/core.rb](https://github.com/ytti/oxidized/blob/master/lib/oxidized/core.rb#L20), hence the runtime dependency in `oxidized-web.gemspec`. Deploying just the `oxidized-web` gem without having the `oxidized` gem makes no sense.

Does this address your concerns?

**Comment by yuri-zubov** [comment]
I agree with you. but if `oxidized.gemspec` has ` s.add_runtime_dependency 'oxidized-web'`
bundler will fetch 'oxidized-web' and depended gems only, `oxidized-web` will not be loaded to oxidired. `oxidized-web` will be loaded only if config file has `:rest`

**Comment by wk** [comment]
Why would it be desirable to have the `oxidized-web` gem and all the dependencies installed together with `oxidized` if they are not going to be loaded and the user has no intention of using them?

**Comment by yuri-zubov** [comment]
it takes a small space on a disk, but it very convenient for users.  You need to install only one gem.
I really spend a lot of time for setup it at the first time. I wrote `:rest` in the config and could not understand why it didn't work.

**Comment by yuri-zubov** [comment]
yes, I see this message but I install this gem in development mode.
I use rbenv for installing all gems.
I made 
```
git clone git@github.com:ytti/oxidized.git
bundle install
bundle exec gem install oxidized-web
bundle exec oxidized 
```
and see this message https://github.com/ytti/oxidized/blob/master/lib/oxidized/core.rb#L22.
and how to fix it in development mode I don't know
I wrote 
`s.add_development_dependency 'oxidized-web'` to `oxidized.gemspec`
made bundle install
and after that command `bundle exec oxidized ` started working

**Comment by wk** [comment]
You may have been looking for [`bundle add oxidized-web`](http://bundler.io/man/bundle-add.1.html), which should accomplish essentially the same thing you've done manually.

The current [build from Git](https://github.com/ytti/oxidized/blob/master/README.md#build-from-git) instructions rely on `gem` rather than `bundler`, and there adding an extra gem following the same pattern should work as-is.

I'm not sure coupling `oxidized` and `oxidized-web` is the right way forward here. Some tools such as [`oxidized-script`](https://github.com/ytti/oxidized-script) use `oxidized` essentially as a library, and would not appreciate extra cruft pulled by default as part of their dependency chain. 

Perhaps in the future, with additional modularity in place, the `oxidized` gem can be transitioned to be a meta-package that pulls all the dependencies required to use `oxidized` as a full-blown application, while portions of what is currently `oxidized` get spun off into e.g. `oxidized-engine`.

**Comment by yuri-zubov** [comment]
@wk Thanks for your answer
