### ISSUE TITLE
LibreNMS API Integration

### ISSUE THREAD

**Issue by Nantallen** [ytti/oxidized#1357]
I realize this issue has been posed numerous times in the past, usually resulting in an issue with bad API token or permissions.  

I believe my issue to be a little different as I can call the API and get results via curl, but still can't get oxidized to run.

So: 

Firstly:  curl call
```bash
curl -H 'X-Auth-Token: 066754086e623dae398b4b4206778b19' http://localhost/api/v0/oxidized
[
    {
        "hostname": "localhost",
        "os": "linux",
        "ip": "127.0.0.1"
    },
    {
        "hostname": "jks-vcenter.jks-systems.com",
        "os": "vmware",
        "ip": "xxx.xxx.xxx.xxx"
    },
    {
        "hostname": "esxi02.jks-systems.com",
        "os": "vmware",
        "ip": "xxx.xxx.xxx.xxx"
    },
    {
        "hostname": "jks-recol-3850.jks-systems.com",
        "os": "iosxe",
        "ip": "xxx.xxx.xxx.xxx"
    }
}
```

You can see that the curl call returns results.  Secondly, my source config:
```
source:
  default: http
  debug: false
  http:
    url: http://127.0.0.1/api/v0/oxidized
    secure: false
    map:
      name: ip
      model: os
    headers:
      X-Auth_Token: '066754086e623dae398b4b4206778b19'
```
When I run oxidized, I get:
```
no implicit conversion of String into Integer
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/source/http.rb:44:in `dig': no implicit conversion of String into Integer (TypeError)
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/source/http.rb:44:in `block (2 levels) in load'
        from /var/lib/gems/2.3.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
        from /var/lib/gems/2.3.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/source/http.rb:42:in `block in load'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/source/http.rb:38:in `each'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/source/http.rb:38:in `load'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:15:in `block in load'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:128:in `synchronize'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:128:in `with_lock'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:10:in `load'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:123:in `initialize'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/core.rb:14:in `new'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/core.rb:14:in `initialize'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/core.rb:4:in `new'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/core.rb:4:in `new'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/cli.rb:12:in `run'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/bin/oxidized:9:in `<top (required)>'
        from /usr/local/bin/oxidized:22:in `load'
        from /usr/local/bin/oxidized:22:in `<main>'
```

I have tried changing the mappings under source, changing debug from false to true, looking through logs, etc.  Local router.db works fine in oxidized, but I can't get the sourcing working via API.

Any thoughts on where to start?  Are there additional levels of debugging I can perform?  Please be mindful that I am not a ruby expert.  First outing if you will.

Thanks,

**Comment by laf** [comment]
`X-Auth_Token` != `X-Auth-Token` :)

LibreNMS has a config validator for oxidized: `tools/tool=oxidized-cfg-check/`

**Comment by Nantallen** [comment]
DOH!

I knew someone would fix my derp.  That was the issue.

Now I just need to work on my mappings as I get:

source returns no usable nodes

But, that is likely on me as well.

Thank you very much.

**Comment by Nantallen** [comment]
Turns out I don't have a model for iosxe.  Has one been created?  I tried copying the ios.rb to iosxe.rb, but it doesn't appear to work.

**Comment by laf** [comment]
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/iosxe.rb does exist but it not in a tagged release. Copying ios.rb to iosxe.rb should work as that's all the actual model does.

**Comment by wk** [comment]
Is there a particular integration headache that makes using the `map_model` dict in the configuration for this type of symbolic links between model names less suitable than cloning the entire model?

**Comment by laf** [comment]
From a LibreNMS perspective, we have started mapping models that don't match names so people don't have to care. However if Oxidized already matches we don't bother - if the model is in master but not a tagged release then people will end up in the situation as above.

**Comment by wk** [comment]
The `iosxe.rb` model in master, however, is a shim for `ios.rb`, presumably for easy discovery.

The initial concept for model shims was that they are useful when some (minor) element of the original model needs to be modified (for example, when we want to emit a warning that the model is being renamed) rather than to be used as a symlink. `map_model`, on the other hand, seems suitable exactly for this use case - symlinks between models.

Ultimately the issue appears to be such: once oxidized has generated an empty configuration [here](https://github.com/ytti/oxidized/blob/e97a7707c45f30390d721d752d76fdb5d701c72d/lib/oxidized/config.rb#L47) with the default model maps, there is no chance to append anything to it - because a running oxidized installation, even after an upgrade, will still use the existing configuration file, preventing updating the user's model map effectively (as such changes will override the user's preferences from that point on). This functionality needs to be rethought if it is to be used effectively.

**Comment by laf** [comment]
> Ultimately the issue appears to be such: once oxidized has generated an empty configuration here with the default model maps, there is no chance to append anything to it - because a running oxidized installation, even after an upgrade, will still use the existing configuration file, preventing updating the user's model map effectively (as such changes will override the user's preferences from that point on). This functionality needs to be rethought if it is to be used effectively.

Imho, it's much better to abstract model mapping from users. People shouldn't really have to care so the shims (again imho) are perfect for this + allow people to drop in additional code to that model if it needs extending out.

**Comment by ytti** [comment]
We can update config as we want, while keeping user config in place.

It's just Hash object, we can insert/remove/update and #save it to disk.

Like if you change output #git, it'll generate git's default config, while keeping everything you already had in place.

But yes, iosxe is verbatim ios, the differences are not on the IOS shell level. There are more differences between two IOS platforms than IOS and IOS-XE generally. 
So to me ```ìosxe: ios``` mapping is the best case, if someone insists differentiating ios and ios-xe.

Ultimately difference between ios and ios-xe is if it contains cisco's bootOS or linux as bootOS. Juniper makes similar changes between JunOS release without alerting operator about it, some version boots FreeBSD another Linux, yet we don't insist calling it junos_freebsd and junos_linux, because the difference between junos platforms is greater than the difference between the junos versions booting different OS.

**Comment by laf** [comment]
@ytti Can we close this? The original question has been resolved and a discussion on model mapping has been done elsewhere.
