### ISSUE TITLE
changelog format?

### ISSUE THREAD

**Issue by ytti** [ytti/oxidized#1360]
How should the changelog look like? So that it is more data than string blobs.

Should it be markdown table? Should there be separate tables for bugfixes/features?

Does https://keepachangelog.com/en/0.3.0/ make sense?

We don't have to convert old shit if we don't want to, but at least for new shit we should have bit more formal/data based changelog. Suggestions? Maybe demo your suggestion in https://stackedit.io/app#

If we had good commit hygiene, where each commit maps to an issue, then perhaps every commit could be changelog item, and it could be purely machine generated. But I guess we're not there and won't be.

**Comment by wk** [comment]
A PR template has been preemptively introduced in #1361 so that users submitting PRs are encouraged to at least update the current changelog following the existing format in order not to create additional clean-up debt going forward.

**Comment by jplitza** [comment]
The current monolithic changelog has its drawbacks, because it's guaranteed to cause merge conflicts for every other PR after a any PR is merged.

Ansible has a cool (yet a bit more complicated) way of doing changelogs: The actual changelog document is auto-generated on release from changelog fragments, which are separate files in the repository. That way, merge conflicts don't happen because the fragments are kept in different files for different PRs.
