### ISSUE TITLE
RFE: Allow specifying Net::SSH debugging level

### ISSUE THREAD

**Issue by fenner** [ytti/oxidized#1414]
I'm running:
* 0.24.0-8-gf094776

in a docker image that I built that comes `FROM oxidized/oxidized:latest`

I spent a few hours trying to figure out why I kept getting "password incorrect" when debugging showed that I had the right password.  It turned out to be that I was using "password" instead of "keyboard-interactive" as an auth_method.  I only eventually figured it out by adding

```
      ssh_opts[:verbose] = Logger::DEBUG
```

to `lib/oxidized/input/ssh.rb`; it'd be nice to be able to specify this in the oxidized config file.

**Comment by ytti** [comment]
Can you test this? https://github.com/ytti/oxidized/tree/feature-ssh_logging_level

Also I think this is your issue: https://github.com/ytti/oxidized/blob/master/docs/Configuration.md#ssh-auth-methods

**Comment by ytti** [comment]
If you are running Arista EOS, you might want also want to read this:
https://github.com/ytti/oxidized/blob/master/docs/Model-Notes/EOS.md

I think it's one of those things where vendor fucked up, but because they do not have method to update standard while maintaining backward compatibility to old standard, they didn't dare to fix error, as usually no matter how trivial error, there is now someone who relies on that behaviour.

**Comment by fenner** [comment]
It does work, with the caveat that it goes to stdout, not the log file.  Passing `:logger` with your logger fixes this; that would make it a better feature for users as opposed to my one-off:

```
      ssh_opts[:logger]     = Oxidized.logger
```
(I tested this, and the output now goes to the `log:` file)

There are tradeoffs to keyboard-interactive, like, TACACS can supply multiple prompts for 2fa and the password method can't support that. Rather than saying "the vendor made a decision that I don't agree with" it seems that you could reduce friction by just adding keyboard-interactive to the list of default mechanisms.  What's the harm?

**Comment by ytti** [comment]
We had ```keyboard-interactive``` as default after we noticed Arista EOS is broken and mandates it. But some other platforms subsequently broke, as they must not have it. 

We are decidedly not doing keyboard-interactive authentication, it's plainly wrong. Arista is aware it is plainly wrong, but you can't fix broken things always, because some customers rely  on broken behaviour.
There are other similar examples, like SW/HW convergence is not synchronous by default, so you start to advertise you have path to your neighbours before you have installed in hardware. There is toggle to synchronise it, so you only advertise forward after it's programmed, but Arista won't make it default, as surely some customers now rely on the broken behaviour or at least don't mind it and prefer the faster convergence. 
I talked with Arista about this, and proposed they implement 'standard A.B.C' stanza in config, if you define that, it'll define what configuration is there implicitly, if you don't define it, it carries over implied standard depending on EOS version. This would allow them to move forward with new standards, while not breaking any existing deployments. But it didn't take.

I'm not at this point going change the logger to oxidized logger, it might be good idea, but for now, all the docs explain how to debug input issues via input debug and file-per-node. 

Thanks you or testing, it's in the master branch now.

**Comment by fenner** [comment]
> I'm not at this point going change the logger to oxidized logger, it might be good idea, but for now, all the docs explain how to debug input issues via input debug and file-per-node.

Just to be clear, the debugging goes to the stdout of the oxidized process, not to the file-per-node.

**Comment by ytti** [comment]
Aaah grr. Hmm I think it's still probably OK, as it's going to be noisy as hell, so you're likely only going to do this with single node? 
Or would you prefer Oxidized logger? I guess you're the expert on how it's simplest to troubleshoot at this point :)

**Comment by fenner** [comment]
Yeah, it's noisy as hell.  I just ran "oxidized -d" manually and watched it all scream by, and happened to catch the algorithm mismatch as it went by.  I suggested the oxidized logger since I thought that might end up being easier for the next person, since nothing else goes to stdout, they might never even see this output.

**Comment by ytti** [comment]
Fair enough, I'll change it to oxidized logger, thanks.
