### ISSUE TITLE
non-existing enable-password for some devices

### ISSUE THREAD

**Issue by mr-deamon** [ytti/oxidized#1432]
https://github.com/ytti/oxidized/blob/ae2d1a202cdfa3c8dd488b8be045e025234913ae/lib/oxidized/model/ios.rb#L138
The ios-devices with no enable-password are trying to resolve my password, which then runs into a timeout.
`Translating "abc"...domain server (x.x.x.x) (y.y.y.y)`
My solution right now is to comment the line above. Does anybody has the same problem, and a solution for it?
Thank you so much!
chris

**Comment by ytti** [comment]
More probable explanation is that you give the Node enable password, telling it's ip or hostname, 


I'm working on lot of assumptions here, because you didn't provide any information. But I assume you are using CSV source file, and you are missing fields for some nodes. Furthermore just adding sufficient amount of fields is not gonna cut it, as empty enable is still enable password with just newline. So you likely want to add that enable field with value ```false``` or ```nil```

**Comment by ytti** [comment]
Ok I understand your issue. 

You've mapped ```enable``` to password, so ```enable``` is always defined. Yet there won't be any enable password prompt, as you are already enabled.

I guess we could detect prompt after issuing enable, and not enter enable password, if password prompt didn't appear. 
But before anything like that, we should try to understand why are you mapping enable to password, thus claiming that every node actually uses enable.

Are either of these solutions possible

1. do not map enable, in this particular example it would just work, and not  try to enable. But perhaps you have some other device which needs enable, can you remove it from them too?

2. have your HTTP API return enable when enable is needed and ```nil``` or ```false``` when not needed.

**Comment by mr-deamon** [comment]
thank you for your comment! I think i will go for option 2, create a new field and set it to the password if it is needed or to nil if not. i tried it with a static source and it worked, so i will change my api accordingly.
thank you for your help!
chris
