### ISSUE TITLE
Comware: Output contains prompt and command (flapping)

### ISSUE THREAD

**Issue by empi89** [ytti/oxidized#1447]
I have a huge amount (>500) of HPE switches and especially the 5120 which sometimes output the prompt and command. This leads to flapping in configuration versions and flooding of hooks. e.g.:

```
-<SW-INT-XXX >display current-configuration
 #
  version 5.20.99, Release 2221P15
+<SW-INT-XXX>display current-configuration
 #
  version 5.20.99, Release 2221P15
```

I have observed that this is especially the case when the devices have some cpu load due to snmp polling. I have already changed some parts of the comware-Model to have it more reliable:
1. removed "display version" - block (because I had the same behavior as with display current-configuration)
2. removed "display device" - block (because I had the same behavior as with display current-configuration)
3. replaced
```
    post_login 'screen-length disable'
    post_login 'undo terminal monitor'
```
with 
```
    post_login do
      send "screen-length disable\n"
      send "undo terminal monitor\n"
      expect /[cC]urrent terminal/
    end
```
Because I often had the message "Info: Current terminal monitor is off." contained in the output.

For the display current-configuration I would like to implement some kind of late-filter which removes the lines starting with a prompt. However I have not found any examples how to do this in the other models. Could you please provide a hint on this? Thanks in advance!

**Comment by ytti** [comment]
The device obviously always shows prompt and command, right? It doesn't print them sometimes and not print sometimes? 
So they should be taken away by this:
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/comware.rb#L18

Why isn't it working? I think it's race condition because broken model. We rely on screen-scraping prompt to know when output has ended. If we do not eat prompt when it happens, another command may consume it early and we go out of sync and cause all kind of funky issues.

Your correction makes it more broken. ```send``` doesn't expect anything, if those commands produce prompt, you have prompts in buffer which are unconsumed.

In the original model, there is same problem:
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/comware.rb#L37-L43

I assume bunch of these actually produce command line, which is not consumed. 

It would be safer to refactor all ```send``` away. Replace them with ```cmd``` which expects to see prompt, or if another argument is specifies, expect to see that regexp. This way we retain lock-step with output. 
I can't tell how to refactor the original, as I don't have the platform, but once it works with all ```send``` replaced with ```cmd``` it'll be far more robust.

**Comment by berilslv** [comment]
Hi guys, can someone comment this? Im facing the same issue that versions are spaming because of these lines: 
![image](https://user-images.githubusercontent.com/46807385/53944358-e10e6f80-40c7-11e9-9192-a387323c5ff2.png)
Can you @ytti  suggest me which lines to edit @ comware.rb ?
