### ISSUE TITLE
oxidized-script, use script against multiple devices without group configuration

### ISSUE THREAD

**Issue by bruccoo3000** [ytti/oxidized#1455]
Hello all,

Is there a way to use the oxidized script against multiple devices without setting up groups in the config file?

I have tried setting up groups and when doing so I lose the previous versions so curious if this is possible.

Thanks

**Comment by ytti** [comment]
You should have opened this issue in oxidized-script. 

It's not currently possible. And if we add reasonable way to do it, we break backward compatibility. Reasonable way would be

```oxs command node1 node2 node3```

But today node is before command, so that would not work. We could easily do something like

```oxs node1,node2,node3 command```

That would basically be just:

Change:
https://github.com/ytti/oxidized-script/blob/master/lib/oxidized/script/cli.rb#L37-L42

To 

```
@hosts = @host.split(/\s*,\s*/)
@hosts.each do |host|
  @host = host
  <lines 37 ... 42>
end
```

**Comment by bruccoo3000** [comment]
ytti,

Thanks for the quick response and apologies for running this through the wrong application.

So, made the changes to the cli.rb file and have the command working but output only displays the first node listed.

Should I re-open this in the oxidized-script section?

**Comment by ytti** [comment]
Please do. And show your code, I feel like you made some mistake, it should have the ```puts``` inside the loop, showing output for each.
There won't be any per node-headers.

**Comment by laf** [comment]
Can confirm that changing the lines indicated works fine.

I added a puts line so I also then get:

```
host: sw01
===============
```
