### ISSUE TITLE
Allied Tellesis promp problem

### ISSUE THREAD

**Issue by cesc007** [ytti/oxidized#1493]
Hi,

 I have been trying to add an Allied switch to Oxidized but I can not get it to work properly. The switch is:

AlliedWare Plus (TM) 5.4.3 07/08/14 10:24:01

Build name : x900-5.4.3-3.13a.rel
Build date : Tue Jul 8 10:24:03 NZST 2014
Build type : RELEASE

Oxidized works fine for Juniper and Cisco devices so I know is working fine, but with this allied swicht I get this:

6286 #22134] WARN -- : 172.30.9.0 status no_connection, retry attempt 1
7987 #22134] WARN -- : 172.30.9.0 status no_connection, retry attempt 2
8822 #22134] WARN -- : 172.30.9.0 status no_connection, retry attempt 3
9501 #22134] WARN -- : 172.30.9.0 status no_connection, retries exhausted, giving up

I am using the alliedplus.rb posted on supported devices.

This is my config file:

```
username: ******
password: ******
model: junos
resolve_dns: true
interval: 86400
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 172.26.3.141:8888
next_adds_job: false
vars:
  enable: 1tx7
groups: {}
models: {}
pid: "/root/.config/oxidized/pid"
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: true
  ssh:                 
    secure: false   
  ftp:
    passive: true
  utf8_encoded: true
output:   
  default: git
  git:
    user: Oxidized
    email: o@example.com
    repo: "/var/lib/oxidized/devices.git"
source:
  default: csv
  csv:
    file: "/root/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    vars_map:
     enable: 4
    gpg: false
model_map:
  cisco: ios
  juniper: junos
  ciscoxr: IOSXR
  allied: Awplus
```

**Comment by mattie47** [comment]
So your device has IP address 172.30.9.0 ? I assume you've verified you can telnet into it normally fine from your oxidized box?

The log implies oxidized can't make a connection to the device. So I don't think it's hitting any of the awplus.rb config yet..

I also just verified telnet is still working fine with oxidized and awplus.

Thanks,

Matt

**Comment by cesc007** [comment]
Yes, my device has the 172.30.09 address, and yes I can telnet this devices from my server where I am running oxidized.

**Comment by mattie47** [comment]
Are you sure you've entered the address correctly into the Oxidized router.db database? 

You've got logging turned on - It would be worth having a look at the logs for the device under the /logs directory.

**Comment by cesc007** [comment]
Yeah I am sure the ip address is ok. these are the logs:

/root/.config/oxidized/logs/172.30.9.0-telnet

```
                    ACCESO RESTRINGIDO, SOLO ACCESO AUTORIZADO!!!
                  Todas las actividades estan siendo monitoreadas.
                 Su violacion esta sujeta a persecucion por la Ley.
SwCaliNorte_9.0 login:

```

**Comment by mattie47** [comment]
@cesc007  I'm just seeing if I can reproduce your problem. 

I originally didn't test this with a login banner, however configuring one it seems to work for me. 

I'm now just trying to see whether the issue for oxidized is with the hostname you have.

For reference, SwCaliNorte_9.0 is an invalid hostname in later versions of AW+:

```
Enter configuration commands, one per line.  End with CNTL/Z.
c2-access2(config)#hostname SwCaliNorte_9.0
% hostname contains invalid characters
```

------------

So I've just tried an x900 running x900-5.4.3-3.13a.rel with the same login banner and hostname, and am not seeing your problem:

```
Trying 10.37.105.35...
Connected to 10.37.105.35.
                    ACCESO RESTRINGIDO, SOLO ACCESO AUTORIZADO!!!
                  Todas las actividades estan siendo monitoreadas.
                 Su violacion esta sujeta a persecucion por la Ley.
SwCaliNorte_9.0 login: manager
Password:
No entry for terminal type "network";
using vt100 terminal settings.
^M
AlliedWare Plus (TM) 5.4.3 07/08/14 10:24:01

SwCaliNorte_9.0>enable^M
SwCaliNorte_9.0#Show System^M
Switch System Status                                   Fri Aug 24 07:23:03 2018

Board       ID  Bay   Board Name                         Rev   Serial number
--------------------------------------------------------------------------------
Base       270        x900-24XT                          A-0   A1QH8A50C
PSU        212  PSU1  AT-PWR01-AC                        F-1   86619240
Fan module 214  PSU2  AT-FAN01                           F-1   93043415
--------------------------------------------------------------------------------
RAM:  Total: 512120 kB Free: 397480 kB
Flash: 63.0MB Used: 22.1MB Available: 40.9MB
--------------------------------------------------------------------------------
Environment Status : Normal
Uptime             : 0 days 00:03:59
Bootloader version : 1.0.9
```

There is two things you could try see if it makes a difference though:

1.  Edit awplus.rb

I suspect the issue is that for whatever reason it's struggling to detect the "login" prompt correctly. I see several other oxidized model/vendor config files include a "^" for the prompt detection, and this may help you.

You can run "gem content oxidized" to see where the resource files for oxidized are, but assuming you're running the latest version, edit awplus.rb:

```bash
nano /var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/model/awplus.rb
```

Change line 64 to include "^" before "login":

```diff
-  # Config required for telnet to detect username prompt
-  cfg :telnet do
-    username /^login:\s/
-  end
+ # Config required for telnet to detect username prompt
+  cfg :telnet do
+    username /^login:\s/
+  end
```

Please let me know if this fixes your problem.

Otherwise, can you please try some troubleshooting such as:
1. Changing the device hostname
2. Removing login banner
3. Try using SSH instead. 


For future troubleshooting, please open the `/root/.config/oxidized/logs/172.30.9.0-telnet` log file using **vim** and paste the output here. Vim is needed because it displays "escape characters" which oxidized uses to detect the login prompt. 


Thanks,

Matt

**Comment by mattie47** [comment]
Actually I might have reproduced the problem....

Will update here with more info if I can figure out anything useful.

Thanks,

Matt

**Comment by mattie47** [comment]
I haven't had time to see if I can fix this yet in the awplub.rb file, but the problem seems to be with the latest version of Oxidized.

I have no issues with telnet with Oxidized version 0.20.0, but do with latest version 0.24.0.

**Comment by cesc007** [comment]
Don't worry I really apprecciate your help.

**Comment by mattie47** [comment]
@cesc007  Sorry I'm probably not going to get a chance to fix this. 

I've resigned from Allied Telesis and only have a couple days left working here, so I won't have access to gear soon. 

My only suggestion would be to enable SSH and use that instead.

```
conf t
crypto key generate hostkey rsa
service ssh
ssh service allow-users *
```


Thanks,

Matt

**Comment by cesc007** [comment]
Hi, thanks it works perfect.

thanks a lot.
