### ISSUE TITLE
Problem with sros.rb "alcatel" when trying to fetche configuration

### ISSUE THREAD

**Issue by hugobrandao** [ytti/oxidized#1504]
Hello guys!!
I'm having an issue when trying to fetche the configuration of a alcatel 7750-SR.

Issue:
Use Ctrl-C to stop
D, [2018-09-04T11:21:22.599997 #1826] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 1
D, [2018-09-04T11:21:22.600612 #1826] DEBUG -- : lib/oxidized/worker.rb: Added 192.168.1.23 to the job queue
D, [2018-09-04T11:21:22.600646 #1826] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-09-04T11:21:22.600749 #1826] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for 192.168.1.23 at 2018-09-04 10:21:22 UTC
D, [2018-09-04T11:21:22.601129 #1826] DEBUG -- : AUTH METHODS::["none", "publickey", "password"]
D, [2018-09-04T11:21:22.601183 #1826] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to 192.168.1.23
D, [2018-09-04T11:21:22.846017 #1826] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([-\w.:>*]+\s?[#]\s?)$/] at 192.168.1.23
D, [2018-09-04T11:21:23.600900 #1826] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-09-04T11:21:24.153015 #1826] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at 192.168.1.23
D, [2018-09-04T11:21:24.153178 #1826] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "environment no more", block: nil at 192.168.1.23
D, [2018-09-04T11:21:24.153255 #1826] DEBUG -- : lib/oxidized/input/ssh.rb environment no more @ 172.30.2.1 with expect: /^([-\w.:>*]+\s?[#]\s?)$/
D, [2018-09-04T11:21:24.153491 #1826] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([-\w.:>*]+\s?[#]\s?)$/] at 192.168.1.23
D, [2018-09-04T11:21:24.601245 #1826] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-09-04T11:21:25.601530 #1826] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-09-04T11:21:26.601859 #1826] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-09-04T11:21:27.602191 #1826] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-09-04T11:21:28.602543 #1826] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-09-04T11:21:29.602865 #1826] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel

The problem is that when the oxidized tries to connect with the router and after giving the command environment no more seems to be waiting for the prompt or to give an enter for the next command.

I appreciate that someone could help me

Cumps

**Comment by ZacharyPuls** [comment]
Try using the timos.rb model. We have two 7750s in production, and I vaguely remember running into this same issue.

**Comment by joaodiogo123** [comment]
@ZacharyPuls I'm running into the same problem as @hugobrandao . Our 7750s are still running TiMOS. Could you please share the timos.rb file?

**Comment by joaodiogo123** [comment]
So, I seem to have figured it out. The 7750s seem to need a `carriage return` instead of a `linefeed`. With that being said, what I did was add a `\r\n` to all the commands I wanted to run. You can check the modded timos.rb bellow:
`class TiMOS < Oxidized::Model

  #
  # Nokia SR OS (TiMOS) (formerly TiMetra, Alcatel, Alcatel-Lucent).
  # Used in 7705 SAR, 7210 SAS, 7450 ESS, 7750 SR, 7950 XRS, and NSP.
  #

  comment  '# '

  prompt /^([-\w\.:>\*]+\s?[#>]\s?)$/

  cmd :all do |cfg, cmdstring|
    new_cfg = comment "COMMAND: #{cmdstring}\n"
    new_cfg << cfg.each_line.to_a[1..-2].join
  end

  #
  # Show the boot options file.
  #
  cmd "show bof \n\r" do |cfg|
    cfg.gsub! /# Finished .*/, ''
    cfg.gsub! /# Generated .*/, ''
    comment cfg
  end

  #
  # Show the system information.
  #
  cmd "show system information \n\r" do |cfg|
    #
    # Strip uptime.
    #
    cfg.sub! /^System Up Time.*\n/, ''
    cfg.gsub! /# Finished .*/, ''
    cfg.gsub! /# Generated .*/, ''
    comment cfg
  end

  #
  # Show the card state.
  #
  cmd "show card state \n\r" do |cfg|
    cfg.gsub! /# Finished .*/, ''
    cfg.gsub! /# Generated .*/, ''
    comment cfg
  end

  #
  # Show the boot log.
  #
  cmd "file type bootlog.txt \n\r" do |cfg|
    #
    # Strip carriage returns and backspaces.
    #
    cfg.gsub! /\r/, ''
    cfg.gsub! /[\b][\b][\b]/, "\n"
    cfg.gsub! /# Finished .*/, ''
    cfg.gsub! /# Generated .*/, ''
    comment cfg
  end

  #
  # Show the running debug configuration.
  #
  cmd "show debug \n\r" do |cfg|
    cfg.gsub! /# Finished .*/, ''
    cfg.gsub! /# Generated .*/, ''
    comment cfg
  end

  #
  # Show the saved debug configuration (admin debug-save).
  #
  cmd "file type config.dbg \n\r" do |cfg|
    #
    # Strip carriage returns.
    #
    cfg.gsub! /\r/, ''
    cfg.gsub! /# Finished .*/, ''
    cfg.gsub! /# Generated .*/, ''
    comment cfg
  end

  #
  # Show the running persistent indices.
  #
  cmd "admin display-config index \n\r" do |cfg|
    #
    # Strip carriage returns.
    #
    cfg.gsub! /\r/, ''
    cfg.gsub! /# Finished .*/, ''
    cfg.gsub! /# Generated .*/, ''
    comment cfg
  end

  #
  # Show the running configuration.
  #
  cmd "admin display-config \n\r" do |cfg|
    #
    # Strip carriage returns.
    #
    cfg.gsub! /\r/, ''
    cfg.gsub! /# Finished .*/, ''
    cfg.gsub! /# Generated .*/, ''
  end

  cfg :telnet do
    username /^Login: /
    password /^Password: /
  end

  cfg :telnet, :ssh do
    post_login "environment no more\r\n"
    pre_logout "logout\r\n"
  end
end`

This problem seem to only happen with devices running the old TiMOS. I have 7750 running SROS and it works just fine with the sros.rb.
Maybe @ytti could check if this is the best way to do it. Or if there is a way to adapt the  sros.rb to work with older devices.

**Comment by joaodiogo123** [comment]
Bump

**Comment by ZacharyPuls** [comment]
@joaodiogo123 I personally think the best resolution to this would be to restore and apply the fix to the old timos.rb, and use that for older TimOS models. But I'll leave the architectural decisions to @ytti.

Out of curiosity, is there any barrier to you updating those devices to SR-OS? Assuming you are running them as NIDs or similar. We only have two 7750s (running as IP transit aggregation routers, in an all-Cisco core, for whatever reason), which do not get updated very often, and they are running SR-OS.

**Comment by joaodiogo123** [comment]
@ZacharyPuls I also think that would be the best way to fix the problem. At least if there is no way to build a model that's compatible with both TiMOS and SRO-OS.

Regarding the updating of the devices, no, I have no way to upgrade them to SR-OS. I actually have a couple of 7750s running SR-OS. But I also have some 7450s running the old TiMOS.
