### ISSUE TITLE
Docker Image missing sql adaptor gems

### ISSUE THREAD

**Issue by dnapper** [ytti/oxidized#1526]
Hi 

The docker file is missing the gem installs for the sqlite3 and mysql2. 
I tried updating the docker file but i'm not sure if I did it correctly. 

I added libmysqlclient-dev to the apt-get install list as it's an upstream build dependency.
I also added sqlite3 and mysql2 to the gem install list.

[Buildfile.txt](https://github.com/ytti/oxidized/files/2385259/Buildfile.txt)

Those steps pass in the build but then it fails at step 22 where it complains about rake. 

Step 22/32 : RUN rake install
 ---> Running in 9c8d84e53805
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

(See full trace by running task with --trace)
The command '/bin/sh -c rake install' returned a non-zero code: 1

**Comment by jerebernard** [comment]
Yes same issue, is it possible to add it into the image to avoid to create a local image ?
I'm using docker compose and using sql request as a source.

**Comment by wk** [comment]
Thanks for this feature request. Since without some SQL drivers, sequel (which is included in the Docker build) won't do much out of the box, it seems quite reasonable to include some of the most used ones.

Merging #1534 to address this as well as lighten the resulting container. Please test the resulting container as-built.

**Comment by jerebernard** [comment]
It works fine using mysql2. Thank you !!!
