### ISSUE TITLE
put multiple files into one git commit

### ISSUE THREAD

**Issue by pubyun** [ytti/oxidized#1552]
if there are multiple updates, it will create multiple git commits.

Can we have a option to only create single git commit?

**Comment by msil** [comment]
Why do you want this feature?

**Comment by msil** [comment]
I was wondering this myself a few weeks ago, as we were getting huge numbers of commits for our devices. In the end i tracked it down to a particular model that was creating lots of unnecessary commits. Once I fixed the model, we were back to a reasonable number of changes.

**Comment by pubyun** [comment]
updates in same time are mostly atomic operation

**Comment by wk** [comment]
The current model of committing per node rather than per job carries with it a number of advantages:

* Commit taking place as soon as the changes have been successfully collected
* Ability to run on a per-node-per-update hooks at all levels (oxidized, remote git hooks, ...)
* Obvious behavior pattern in case of a job completed with exceptions (such as failed collections from some, but not all, devices)
* Ability to annotate individual commits (which affect a single specific node) with external information (such as the username of the person who has performed the change) to make the commit log more informative.
