### ISSUE TITLE
Junos change the way the config is fetched

### ISSUE THREAD

**Issue by roedie** [ytti/oxidized#1563]
Hi,

When using the current junos model the configuration is requested using 'show configuration | display omit'. While this does give you the full config, using diffs on it is quite useless because a lot of the time there is absolutely no context at all.

Wouldn't it be nicer if the config was fetched using 'show configuration | display omit | display set'?

This will modify the config for all current users of course, but it will be much easier to understand when diffing the config.

Any thoughts about this?

Sander

**Comment by ytti** [comment]
Have you seen this https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md

IOS-XR has similar 'formal' output, which is far more grep friendly.

I'm with you, but it's not marketable as standard. Much like people for some reason want 'remove_secret' which I view as an antipattern. Probably they turned it on in Rancid because it happened to exceed and secure sounds good, and decade later they now assume it's their policy.

**Comment by roedie** [comment]
Gosh your quick ;-)

Nope, I haven't seen it before. But will implement it that way. Thanks!
