### ISSUE TITLE
Help: Pager Expect regex

### ISSUE THREAD

**Issue by dnapper** [ytti/oxidized#1571]
I’m working on a new model file and i’m not sure if i’m using the expect statement correctly to handle the paging on this device.

The output looks like this (from a tcpdump).

```
hostname > show configuration running
Please wait… (up to a minute)

module ct3 1/1
framing m13
<SNIP>
exit aaa
Press any key to continue (q : quit) :.
```

The regex should be simple enough with this
`expect /(.+)any key to continue(.+)/ do |data, re|
    send ' '
    data.sub re, ''
  end`

Based on the Oxidized log saying 'timeout waiting for more data' and tcpdump stopping at the press any key prompt so it's not seeing the expect pattern. 

I’ve tried several other iterations without the data substitution.
I've tried more aggressive regex such as ./*continue.*/.
So far nothing works. 

Do I have to put the regex match inside the cmd statement? 
Could there be other random garbage in the telnet session that is messing up the regex?

**Comment by wk** [comment]
It may be helpful if you can post a pcap file containing the interaction with the device (both manual, by running the commands you expect to run) and through Oxidized. This will allow inspecting if any unexpected characters (such as an unusual character instead of a white space) are output by this model. 

A copy of the model, as well as some information regarding the device may also prove helpful as another user may be familiar with the peculiarities of the device and OS type.

The regexp itself seems correct and should trigger on the pattern you've provided.
