### ISSUE TITLE
[aen.rb] Regex for prompt with empty spaces

### ISSUE THREAD

**Issue by mmarin11** [ytti/oxidized#1598]
Dear community. We are trying top backup the configuration of Accedian devices (AEN) model and some of the devices have a prompt with empty spaces
For example:

Sta Catarina- SO-1-5687:

And the backup procedure is failing with error
not matching configured prompt (?-mix:^([-\w.\/:?\[\]\(\)]+:\s?)$)

Is there a way to specify a regex rule that supports empty spaces?

Thank you

**Comment by wk** [comment]
The current regexp indeed does not appear to support your use case:
```ruby
irb(main):020:0> "Sta Catarina- SO-1-5687:".match /^([-\w.\/:?\[\]()]+:\s?)$/
=> nil
```

Adding a whitespace (`\s`) match inside the prompt seems to work:
```ruby
irb(main):021:0> "Sta Catarina- SO-1-5687:".match /^([-\w\s.\/:?\[\]()]+:\s?)$/
=> #<MatchData "Sta Catarina- SO-1-5687:" 1:"Sta Catarina- SO-1-5687:">
```
Using spaces in hostnames is discouraged, as it is not possible to express such hostnames in DNS. Regardless, if this results in a successful configuration retrieval in your scenario, please update this issue or create a PR with the above suggested change. Since the OS type allows for such hostnames, there's no reason not to support them in the model.
