### ISSUE TITLE
Troubleshoot device problem without affecting other devices

### ISSUE THREAD

**Issue by j362557** [ytti/oxidized#1626]
What is a good practice when adding a new device? 
I mean, the first time you are adding a new device you may run in trouble: SSH/telnet is not established, username/password is not working, etc. During the troubleshooting you might need to restart Oxidized some times to validate if configuration for new device is working. But here is the problem: Every time you restart Oxidized daemon, it go through all the devices, log in, and check if there is any change.

How to add a new device and troubleshoot a specific device problem without affecting the others?

Thanks.

**Comment by j362557** [comment]
Hi davama.

You pointed exactly what I meant to say. Every time I restart Oxidized it logs in on every device. Since during a debug you probably will restart Oxidized sometimes, it will log in a lot of times and running all the commands.

Anyway...
**I think that a good feature for Oxidized would be the possibility to schedule the hours it would run. That said, then a feature to run a backup only for specific device for trouleshoot purpose or every other need** 


Appreciate your help.
Thank you.

**Comment by hvoIIITA** [comment]
Yes, please. I would greatly appreciate if we could schedule to run at a specific time, even better if we can break it would by grouping.

**Comment by ml-cms** [comment]
when will be a scheduled backup possible?
I like oxidized but one of the biggest disadvantages is the lack of supporting scheduled backups.
Until there is no scheduled backup it is not possible for me to migrate fronm RANCID because on some sites we backup more than 1000 devices on a scheduled basis. The schedule is urgently needed because we have devices that become high CPU during backup, so these devices are not allowed to backup during working hours. Most of the devices are only allowed to backup outside working hours or at specified times!
Also a oxidized restart results in login on all nodes and make config backups wich is also not optimal if you have more than a handful devices configured.
