### ISSUE TITLE
ssh encryption error

### ISSUE THREAD

**Issue by kevhjelm** [ytti/oxidized#1724]
I'm trying to get config from a switch using oxidized, but receiving this error 
[![enter image description here][1]][1]
what is protocol 2.0?
Am I using the wrong encryption algorithm? first picture is from the switch log and the second is from oxidized . I'm not sure where it fails and how to troubleshoot

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/X2VWC.png
  [2]: https://i.stack.imgur.com/Ml397.png

**Comment by wk** [comment]
If your host system has OpenSSL 1.1.x installed, you may be affected by net-ssh/net-ssh#503. Upgrading to Oxidized 0.26.3 and making sure that the installed version of `net-ssh` dependency is 5.0 or higher (remove the 4.1.0 currently in place prior to installing Oxidized 0.26.3 or upgrade it manually using `gem` and uninstall the older version) might help to resolve this.

**Comment by kevhjelm** [comment]
I did what you suggested and upgraded oxidized to 0.26.3, and to net-ssh-5.1.0  and also oxidized-web. The oxidized debug gives the same error

3 #21605] DEBUG -- : 10.20.4.10 raised Net::SSH::Disconnect with msg "disconnected: protocol error: rcvd type 0 (2)"
 #21605] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for host-xx

And for for the switch, also the same

CP1  [03/07/19 08:46:51.276:CET] 0x000d858b 00000000 GlobalRouter SSH INFO New connection from ip 192.168.195.57 port 41512
CP1  [03/07/19 08:46:51.276:CET] 0x000d8603 00000000 GlobalRouter SSH INFO Enabling compatibility mode for protocol 2.0
CP1  [03/07/19 08:46:51.280:CET] 0x0003c77a 00000000 GlobalRouter IP INFO kex:chosen algorithms for client->server: encryption:aes128-cbc mac:hmac-sha1 compression:none
CP1  [03/07/19 08:46:51.280:CET] 0x0003c77a 00000000 GlobalRouter IP INFO kex:chosen algorithms for server->client: encryption:aes128-cbc mac:hmac-sha1 compression:none
CP1  [03/07/19 08:46:51.420:CET] 0x000d8602 00000000 GlobalRouter SSH INFO Disconnecting: protocol error: rcvd type 0
CP1  [03/07/19 08:44:51.594:CET] 0x000d8602 00000000 GlobalRouter SSH INFO bad pkalg ssh-rsa

I see the switch mentions " bad pkalg ssh-rsa" is it using another encryption method? Do you have other suggestions? 

my system
Ubuntu 18.04.2 LTS
OpenSSL 1.1.0g  2 Nov 2017
net-ssh-5.1.0

**Comment by wk** [comment]
If I understand correctly from your description, you have similar switches of the same model that work and that do not work. If that is indeed the case, this suggests a remote-side root cause which could include:

* Different firmware version on the device
* Different MAC or KEX configuration on the device
* Device is not correctly configured to accept authentication via desired mechanism from the user (i.e. key vs. password)
* Oxidized configuration for device differs (typo, different group with different parameters, etc.)

It might be helpful to attempt to log in to the affected devices via SSH, using the same user as Oxidized, from the same host, using regular ssh (with -vvv) and validate that the same MAC, KEX, authentication method, and key (if any) are used as expected.

**Comment by kevhjelm** [comment]
I have 4 different switches Extreme VSP7K, VSP8K2, VSP8K4 and VSP9K.
For my VSP 7 and VSP8K2 everything works perfectly, I'm able to fetch the config.
but for my VSP8K4 and VSP9K model, I'm getting the error provided earlier. One thing that might be the problem is the ACL configuration or as mentioned the difference in SSH key access

I will look into my ACL and firmware versions and take it from there. Closing for now
