### ISSUE TITLE
Ruby issues after upgrade to 2.3

### ISSUE THREAD

**Issue by dalamanster** [ytti/oxidized#1730]
hello world, 

We had oxidized installed on CentOS 7 for a long time. This week we upgraded the ruby from version 2.0 to 2.3.  

First I uninstalled old one - yum remove ruby ruby-devel
Second: I installed new ruby using RVM ([steps](https://github.com/ytti/oxidized#installing-ruby-23-using-rvm))

Now i have this strange setup, where I dont see ruby installed when invoked with sudo: 
```
[panenkar@custconfig ~]$ ruby -v
ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-linux]

[panenkar@custconfig ~]$ sudo ruby -v
sudo: ruby: command not found

[panenkar@custconfig ~]$ sudo -i
[root@custconfig ~]# ruby -v
ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-linux]
```
All the gems where installed from userspace of user "panenkar" using sudo.
Buto ruby is not visible now in sudo space.. strange.. 
 
I would like to ask you here. What are correct installation steps of oxidized gems? 
"gem install oxidized" should be installed as root ? or as sudoer user? 

Thank you

**Comment by wk** [comment]
If you want to make RVM play along with sudo, you may be looking for [rvmsudo](https://rvm.io/integration/sudo), although other techniques exist. 

One alternative is to install a newer Ruby system-wide; see the installation instructions for RHEL / CentOS (they're been recently updated) regarding [SCL](https://github.com/ytti/oxidized#centos-oracle-linux-red-hat-linux).

Oxidized itself will happily run as an unprivileged user. You can install the gem as a user (after installing RVM as *that same user*) by running `gem install oxidized --user` or similar. See the gem documentation [here](https://guides.rubygems.org/rubygems-basics/).

I will close this issue as it seems to be focused on the mechanics of Ruby, gem, and sudo rather than `Oxidized` itself.

**Comment by dalamanster** [comment]
Thank you, oxidized is running now as a unprivileged user. I had issues with ruby via SCL so I used RVM

I had to:
- delete old ruby and scl (yum erase...)
- delete old gems (fortunately .config and git files are saved separately)
- install RVM as a oxidized user (with installation steps in oxidized [readme](https://github.com/ytti/oxidized#installing-ruby-23-using-rvm))
- install gems as a oxidized unprivileged user (I was using sudo before)
- edit [oxidized.service](https://github.com/ytti/oxidized/blob/master/extra/oxidized.service) file. I had to point ExecStart to wrapper `/home/oxidized/.rvm/gems/ruby-2.3.8/wrappers/oxidized`
- start service oxidized

**Comment by andreasmalta** [comment]
i had issues with SCL too, but the steps above sorted me, maybe the installation instructions for centos 7 should be updated?
