### ISSUE TITLE
Support for Cisco Unified Communication Manager

### ISSUE THREAD

**Issue by azmihamzah** [ytti/oxidized#1736]
Is there any model that i can follow to pull configuration from cisco unified communication manager (CUCM)?

From cisco's manual

https://www.cisco.com/c/en/us/support/docs/unified-communications/unified-communications-manager-callmanager/211975-CUCM-DRS-Backup-and-Restore-Operations-v.html

it requires to set a sftp server to dump the config file(s) before running the DRS backup utils

**Comment by AJ-Acevedo** [comment]
This would be very interesting. I could see a need for this.

**Comment by wk** [comment]
From the linked document, it appears backups are expected to take place over `sftp`. Currently, there's no `sftp` input in place within Oxidized, so that would be a precondition for implementing a suitable model.

There does appear to be a Ruby `sftp` implementation [here](https://github.com/net-ssh/net-sftp) that may be relevant. If an `sftp` input and a matching model are contributed, they'd be candidates for inclusion.

**Comment by AJ-Acevedo** [comment]
Hello no-response bot. What was the "_request for more information_"?
