### ISSUE TITLE
remove_secret and unfiltered output

### ISSUE THREAD

**Issue by astenger** [ytti/oxidized#1774]
For consumption by different teams the option to do remove_secret and unfiltered outputs would help.

I love that the code already has regex in place to strip sensitive config in the models themselves.

It appears though that the stripping is done on input. It would be more elegant to apply it during output so different outputs can chose to do the stripping or not.

In part this is related to the multiple output request.
https://github.com/ytti/oxidized/issues/425

As a workaround I guess I could run two oxidized containers and one using remove_secret and the other one processing unfiltered.

**Comment by ytti** [comment]
I think this might be possible to do already today in models, perhaps something like:

```
cmd "show run" do |cfg|
   @mycfg ||= {}
   @mycfg["show run"] = cfg
   cfg
end

post do
   cfg = Oxidized.string ""
   @mycfg.each do |_cmd, output|
     cfg << output
   end
   cfg.type = "unsecured"
   cfg.name = "configs"
  cfg
end
```


Something to that note. Personally I don't really understand utility of removing 'secrets' from config at all, and I suspect if rancid didn't do it by default, no one would have thought to ask it. But because rancid did it by default, people thought it's now their policy and think they must have it.

**Comment by danpoltawski** [comment]
I'm also interested to have this feature 

> Something to that note. Personally I don't really understand utility of removing 'secrets' from config at all, and I suspect if rancid didn't do it by default, no one would have thought to ask it.  

One reason we haven't just switched to removing secrets across the board is that we have some device types (fortios) which regenerate their output secrets on every `show full-configuration`. So in order to get useful config diffs to see real changes we need to excluded these constantly changing fields.
