### ISSUE TITLE
Propose Feature Request: Generic Linux Module for Configs

### ISSUE THREAD

**Issue by davama** [ytti/oxidized#1818]
Hello,

One of my backburner projects is to backup all critical configurations for our different linux servers. I was planning to write up a simple bash script to do it but then i wondered, "does oxidized already do this??" :thinking: 

Not that they change a lot but if something it did, we can see the change and restore if need be.

Was looking at the [culumus](https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/cumulus.rb) module which has something similar to what i was thinking.

Would it be ok for me to submit something similar but for Linux in general? I could call it `linuxgeneric`

Of course my org needs differ so ill make it generic to start with. 

The details could be hashed out later but just wanted some opinions.

Thoughts??

Thanks,
dave

**Comment by wk** [comment]
There is a considerable breadth to what falls under "Linux server", and may include hundreds or even thousands of packages and configuration files which further differ in availability and names across different distributions and versions.

Network equipment and appliance vendors typically hide much of this complexity behind a vendor provided distribution that includes an opinionated, default, configuration for the operating system - and then expose a small purpose-built user-serviceable configuration aperture limited to the scope of its supported features.

You might want to consider inverting the model and embracing declarative configuration management via a tool such as ansible, salt, puppet or a declarative distribution such as nixos. These tools include a broad range of high and low level abstractions to deal with common problems in this domain, and would result in there being a single repository of authoritative configurations. Nearly all of these tools also offer some functionality to validate the "compliance" of a specific server to its declared configuration in order to identify and rectify configuration drift (i.e., "diffs" in the style of Oxidized).

Alternatively, you might want to consider traditional backup tools for these Linux servers which will include both configuration and data (or even complete partitions, volumes, and disks) allowing for a complete recovery of all data.

**Comment by davama** [comment]
@wk thank you for the reply

> There is a considerable breadth to what falls under "Linux server", and may include hundreds or even thousands of packages and configuration files which further differ in availability and names across different distributions and versions.

Absolutely agree

>You might want to consider inverting the model and embracing declarative configuration management via a tool such as ansible, salt, puppet or a declarative distribution such as nixos. These tools include a broad range of high and low level abstractions to deal with common problems in this domain, and would result in there being a single repository of authoritative configurations. Nearly all of these tools also offer some functionality to validate the "compliance" of a specific server to its declared configuration in order to identify and rectify configuration drift (i.e., "diffs" in the style of Oxidized).

Aware of their existence. We use ansible for routine tasks and salt is overkill for our needs (cool software though). We could hack up our own thing to do what we want no problem but the oxidized service is already running and works fantastic! (why reinvent or spend time implement something new when you can append to what already exist)

> Alternatively, you might want to consider traditional backup tools for these Linux servers which will include both configuration and data (or even complete partitions, volumes, and disks) allowing for a complete recovery of all data.

Yes, that is done but for our critical DBs not configs specifically. We simply need config backups/diffs if any.


Going back to point 1 about "considerable breadth", my idea was to follow the `cumulus` model and used [Extended-Model](https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md) to meet our needs. Others who wish to use this model can follow suit. 

Granted I cannot account for every OS flavor, that is a fact, but the leaner the base model is the better. Just providing a foundation.

defining "lean" could be discussed in the PR. I already have a sample, but need to test before i submit. 

Thank you,
Dave

**Comment by WhiteNoseThunderPants** [comment]
@davama Have you checked out [etckeeper](http://etckeeper.branchable.com/)?

**Comment by davama** [comment]
@WhiteNoseThunderPants

Thanks for the reply!

No, never seen. Looks interesting. 

PR is far along now, and personally dont want to implement a new application. But ill keep it in mind! Who knows ¯\_(ツ)_/¯ 

Thanks!!
Dave

**Comment by WhiteNoseThunderPants** [comment]
@davama No problem, just wanted to make sure you were aware of it.
