### ISSUE TITLE
process_cmd_output clobbering output when exec=true

### ISSUE THREAD

**Issue by jcbailey2** [ytti/oxidized#1847]
Warning: I'm not a Ruby developer by any means, so my understanding may be flawed...

Ran into an issue after upgrading from 0.24.0 to 0.26.3 where a custom module I had written was no longer returning any output from calls to cmd.

Module is something like:
```
class Foo < Oxidized::Model
  pre do
    cfg_name = cmd 'cat /etc/current_cfg.txt'
    cfg_name = cfg_name.strip

    cfg = 'Configuration Name'
    cfg += cfg_name
 end

  cfg :ssh do
    exec true
    pre_logout 'exit'
  end
end
```

I was able to track down the issue to process_cmd_output in module.rb. Reviewing changes, if I revert process_cmd_output back to what it was prior to commit https://github.com/ytti/oxidized/commit/0e0b2aa43dec8d0858b6736d3267dd2f8e4f8ee5, everything works fine. The variable output comes into the function as _Net::SSH::Connection::Session::StringWithExitstatus, so I assume the first line that would cast the output as a Oxidzed::String isn't actually firing due to the logic in use.

Unfortunately, that's about where my expertise ends. The === operator in Ruby seems to be a bit black magic, so I'm not sure _what_ exactly the difference in logic is.

If there is any other information that would be useful, please let me know.

**Comment by ytti** [comment]
So only thing you did, was revert the class comparison?

=== like == or anything else, is just a method in ruby, there is nothing magic about it. If you do ```String === "foo"``` what is really happening is ```String.===("foo")```, so method call to method named === with argument "foo".

```
[1] pry(main)> String === "moi"
=> true
[2] pry(main)> String == "moi".class
=> true
```

So ostensibly both are same. But what actually === does, it behaves like ```is_a?``` or ```kind_of?``` where as ```Class == object.class``` behaves like ```ìnstance_of?```. 
instance_of matches class exactly, is_a/kind_of match parent classes too.


However I don't see why that would break it. The first line tests if it's normal string, instead of oxidized string, then creates oxidized string out of the normal string. 2nd line creates empty oxidized string if it is not oxidised string.
So for clobbering to happen, somehow you should be getting a variable which is not a oxidized string nor a string, so the first line doesn't match anymore and second line matches, which creates an empty Oxidized string
If you can write on the first line of the process_cmd_output ```Oxidized.logger.debug "the class is: #{output.class}"``` and watch the debug to see what is its class, that would be useful to fully understand the issue.




Does this work for you?
```ruby
    def process_cmd_output(output, name)
      output = Oxidized::String.new(output) if output.kind_of?(::String)
      output = Oxidized::String.new('') unless output.instance_of?(Oxidized::String)
      output.set_cmd(name)
      output
    end
```

**Comment by jcbailey2** [comment]
The proposed fix seems to have the intended result (ie. returned value is the data expected from the exec channel).

The classes I'm seeing passed to process_cmd_output are:

- Net::SSH::Connection::Session::StringWithExitstatus
- Oxidized::String
- String

Net::SSH::Connection::Session::StringWithExitstatus is what is getting passed from the custom model that is using exec. The instances of Oxidized::String and String are from the other models I have in use (ios, iosxr, netscaler among others).

**Comment by ytti** [comment]
Alright that's a good catch, yes Net::SSH::Connection::Session::StringWithExitstatus would break it.
I'll submit a fix.
