### ISSUE TITLE
Keep changes of router.db file in local git repo

### ISSUE THREAD

**Issue by vicbreen** [ytti/oxidized#1852]
Is there a simple way to make router.db get backed up like the router configs? It would be really great to have version history of that file.

**Comment by zombah** [comment]
Simplest imo with bash script which commit all changes triggered by cronjob, something like:
```
cd xxx
git add --all
git commit -a -m "update"
```

**Comment by ytti** [comment]
I will strongly recommend router.db not to be your source of truth. You have a bigger problem right now, your problem is, you don't know what devices you have. Router.db cannot be source of that information.

My proposal, develop some device registry, SQL or such. Have Oxidized query the SQL or generate router.db from the SQL.

This way, you have some source of truth, out of which you can provision all device stuff, like monitoring, configuration, etc.

**Comment by zombah** [comment]
@ytti even if router.db is intermidiate step between source of truth and oxidized and sounds fine to track router.db chages for some extra audit

**Comment by vicbreen** [comment]
Absolutely agree with your recommendations. I'm working on a new source of
truth but it's not decided upon (internal departmental squabbles) but it
will be happening soon in some form. In the mean time, I just need a sane
way to track changes in the static file that isn't too far outside of
oxidized, but I suppose a manual or cron'd git push would work for now.

I'm migrating out of an old rancid instance and that's the old way of doing
things around here where router.db was versioned by CVS in addition to the
device configs. Breaking old bad habits is also part of the process.

Thanks for the input!

**Comment by ytti** [comment]
In the interim, I'd use what ever practices you use to provision servers. Like puppet and have that router.db managed in your puppet repository.
