### ISSUE TITLE
Enable require username & password

### ISSUE THREAD

**Issue by hebval** [ytti/oxidized#1874]
Hi everyone !

I have an issue when i'm trying to backup one of my HP J9726A 2920 switch.

We wanted to create read-only users to avoid having our admin ids in the config file. Everything is working well on all our equipments except the one i mentionned :

On my Oxidized VM, I'm connecting to the switch, but I'm not with manager privileges to run the display current-config command. Here is my main problem :

When i launch an "enable" command, this switch is the ONLY ONE that ask me to insert an username and a password. How am I supposed to write the username AND the password in the config file ? 

Don't know if you'll understand my question... But some help will be enjoyed !

**Comment by deajan** [comment]
With what user do you login ? operator ?
Describe the manual process you're doing to show the config. Best would be a ssh/telnet log.

**Comment by BapRx** [comment]
Hi, I hope you solved your issue but if you haven't, you can solve it by redefining your manager account without the "user-name" option.
You just have to run this command followed by the manager password:
`password manager`

I believe that the switch asks for the enable username because it was set up with this command:
`password manager user-name <yourUsername>`
