### ISSUE TITLE
New model request: GWD 6900S

### ISSUE THREAD

**Issue by hrtrd** [ytti/oxidized#1927]
Hello. Try add new model: GWD GFA6900S
show version: https://pastebin.com/Xu6n94ve
show running-config:   like cisco cli showing all configurations.

create new file /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/model/gfa.rb  and paste 

require 'oxidized/model/gfa.rb'

class gfa

    cmd 'show version' do |cfg|
        comment cfg
    end

end

try start and got this:

--------------------------------------------------
2019-10-08 10:07:47 UTC
undefined method `cmd' for GFA:Class [NoMethodError]
--------------------------------------------------
/var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/model/gfa.rb:7:in `<class:GFA>'
/var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/model/gfa.rb:4:in `<top (required)>'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/manager.rb:9:in `load'
/var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/manager.rb:60:in `loader'
/var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/manager.rb:47:in `add_model'
/var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/node.rb:170:in `resolve_model'
/var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/node.rb:22:in `initialize'
/var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:21:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:21:in `block (2 levels) in load'
/var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:16:in `each'
/var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:16:in `block in load'
/var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:130:in `synchronize'
/var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:130:in `with_lock'
/var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:10:in `load'
/var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:125:in `initialize'
/var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/core.rb:14:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/core.rb:14:in `initialize'
/var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/cli.rb:13:in `run'
/var/lib/gems/2.5.0/gems/oxidized-0.26.3/bin/oxidized:8:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'

**Comment by ytti** [comment]
You're not subclassing it the class.

**Comment by hrtrd** [comment]
Yes, i read https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md  and try create analog. But some wrong. If you do not complicate, tell me what i need change?

**Comment by ytti** [comment]
Sorry those documents are specifically for extending existing models, not about creating new one.  For new one you do not require any file, and you must subclass the class you're creating.

Please see some existing model, you can copy it to ~/.config/oxidized/mode/ directory under new name and start editing it.

**Comment by penfold1972** [comment]
Did you mean to say to put the file in ~/.config/oxidized/model/ or ~/.config/oxidized/mode/ ?
I'm trying to create a new model and have created the file ~/.config/oxidized/model/centos.rb with the text below, but all I see is the error:
node {:name=>"lnco-cableos-1", :ip=>"10.62.7.1", :model=>"CableOS", :group=>"Harmonic"} raised Oxidized::ModelNotFound with message 'CableOS not found for node 10.62.7.1'

It feels like the process isn't finding the file in the OXIDIZED_HOME (/opt/oxidized) to load the customer model.rb, but since it finding the config file, I assume it must finding the correct home dir. 

So I feel like I am missing something obvious.

`root@nis-oxidized-1:/opt/oxidized/.config/oxidized# more model/cableos.rb 
class CableOS < Oxidized::Model

  comment '# '

  def telnet
    @input.class.to_s.match(/Telnet/)
  end

  cmd 'show running-config | nomore'

  cmd 'show version' do |cfg|
    comment cfg
  end

  cfg :telnet do
    username(/^login:/)
    password(/^Password:/)
  end

  cfg :ssh do
    exec true # don't run shell, run each command in exec channel
  end

  cfg :telnet, :ssh do
    # post_login 'set cli screen-length 0'
    # post_login 'set cli screen-width 0'
    pre_logout 'exit'
  end
end`

**Comment by dmacias-teamam** [comment]
Copy a stock model into the $OXIDIZED_HOME/.config/oxidized/model/
The models In github here: https://github.com/ytti/oxidized/tree/master/lib/oxidized/model

stock models in your system: `gem environment`

**Comment by davama** [comment]
Copy a stock model into the $OXIDIZED_HOME/.config/oxidized/model/
The models In github here: https://github.com/ytti/oxidized/tree/master/lib/oxidized/model

stock models in your system: `gem environment`

**Comment by penfold1972** [comment]
I copied the junos.rb as directed to ~/.config/oxidized/model/centos.rb and restarted oxidized. Edited the file to define the class as CentOS and changed the command to what I want ran and commented out the rest.
Got the same error:
```Dec 06 14:48:32 nis-oxidized-1 oxidized[10819]: Oxidized starting, running as pid 10819
Dec 06 14:48:32 nis-oxidized-1 oxidized[10819]: lib/oxidized/nodes.rb: Loading nodes
Dec 06 14:48:32 nis-oxidized-1 oxidized[10819]: node {:name=>"lnco-cableos-1", :ip=>"10.62.7.1", :model=>"CableOS", :group=>"Harmonic"} raised Oxidized::ModelNotFound with message 'CableOS not found for 
Dec 06 14:48:32 nis-oxidized-1 oxidized[10819]: lib/oxidized/nodes.rb: Loaded 121 nodes
Dec 06 14:48:32 nis-oxidized-1 oxidized[10819]: Puma starting in single mode...
Dec 06 14:48:32 nis-oxidized-1 oxidized[10819]: * Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
Dec 06 14:48:32 nis-oxidized-1 oxidized[10819]: * Min threads: 0, max threads: 16
Dec 06 14:48:32 nis-oxidized-1 oxidized[10819]: * Environment: development
Dec 06 14:48:32 nis-oxidized-1 oxidized[10819]: * Listening on tcp://0.0.0.0:8888
Dec 06 14:48:32 nis-oxidized-1 oxidized[10819]: Use Ctrl-C to stop```

If I understand correctly, the program reads my router.db file and finds the node I am testing with, doesn't recognize the model. So it merely complains and ignores it, which is why I have 122 lines and 121 nodes.

It's still not clear what I'm doing wrong.

**Comment by davama** [comment]
> ~/.config/oxidized/model/centos.rb 

Change the file name too

**Comment by penfold1972** [comment]
I used strace and it looks like I found two things I was doing wrong.

1. The program was looking in /opt/oxidized/model/ rather than /opt/oxidized/.config/oxidized/model, which was solved by a quick softlink.
2. After that, it must have read the file, but then it couldn't find a filename with the same case. After renaming cableos.rb to CableOS.rb all of the No Such File errors disappeared and I got 122 nodes as expected.
```stat("/opt/oxidized/model/CableOS.rb", 0x7ffd3d345e10) = -1 ENOENT (No such file or directory)```

This is noteworthy because the files to use as an example (/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/model/junos.rb) does not seem to have the matching case requirement for the JunOS class.
