### ISSUE TITLE
Powerconnect configuration pull updates every polling period without configuration changes

### ISSUE THREAD

**Issue by gbbromley** [ytti/oxidized#195]
Everytime Oxidized pulls running configuration from the Dell PowerConnect switches if will obtain system information believe through show system. This includes System Up Time which changes every polled period i.e.
! System Up Time: 629 days, 03h:58m:34s
1hour later
! System Up Time: 629 days, 04h:58m:44s

Any chance the def clean cfg could be updated to strip that updating field?

**Comment by ytti** [comment]
What is the powerconnect model? It looks like model will ignore anything from up time until empty line, for many models. 
Unsure why there even is model check.

If this is satisfied:
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/powerconnect.rb#L54
You shouldn't see those lines in config

Looking at older version:
https://github.com/ytti/oxidized/commit/82dc9fad5d59fa2bc9533a62af35f0985dabadec
It seems older version ignored uptime line, in every case. 

Perhaps @MrRJ45 accidentally removed all cleaning on non-specified models?

**Comment by MrRJ45** [comment]
The models listed should be those that allow stacking and may show multiple lines, one for each stack member.

We should probably have an else on that if statement which is just a next so we skip the uptime/temperature line

**Comment by ytti** [comment]
Can I get examples of the two different versions of 'show system'. So that I can determine if

a) I need to create clean_old and clean_new to handle them separately
OR
b) If general clean can be made to address both types

@MrRJ45 can you put in http://p.ip.fi/ both versions or as many unique versions as exist?
@gbbromley  can you put in http://p.ip.fi your 'show system' on non-working boxes?

**Comment by gbbromley** [comment]
Uploaded outputs for PCM6220 and PCM6348 - http://p.ip.fi/Mbhs

**Comment by ytti** [comment]
Ok, so that is 'style 1' now we need input from @MrRJ45 for 'style 2', to see if generic can be made or separate ones.

Where did the output style change? Is one of the output style from older boxes and newer boxes? Or is it one is from consumer boxes, one from enterprise? Just if I need to have two different #clean methods, I'd like to have some reasonable name for them.

**Comment by MrRJ45** [comment]
I will have a look shortly to see if we have examples. Most of our Dell switches are stackable so shows in the format above.

Thinking about this, if the matched line has a colon in it then it will be a single line, otherwise we can probably assume it is a block that needs to be skipped.

I will see what examples I can find in the mean time :)

**Comment by gbbromley** [comment]
I think for the Blade PowerConnect we are using the following changes appear to support removing Up Time

Line 22:
Adjust (/d{4})[P|F]? to ([M](/d{4})[P|F]?
matches PowerConnect M6220 and M6348 Blade modules

Which enables an adjusted  line 54 to have |^M6220$|^M6348$ appended after ^8024$ and before / to remove the offending section.

We appear to lose the whole section, but it results in more stable configuration diffs:
-! System Up Time: 634 days, 04h:53m:07s
-! System Contact:
-! System Name: EXCH2010-BC1-B1-fhdis
-! System Location:
-! Burned In MAC Address: A4BA.DB82.150F
-! System Object ID: 1.3.6.1.4.1.674.10895.3015
-! System Model ID: PCM6220
-! Machine Type: PowerConnect M6220
-! Temperature Sensors:
-!
-! Unit Description Temperature Status
-! (Celsius)
-! ---- ----------- ----------- ------
-! 1 System 36 Good
-!
-! Power Supplies:
-!

**Comment by ytti** [comment]
We can always certainly support single clean function, regardless of models, we just need to know the two output styles.

**Comment by MrRJ45** [comment]
Sorry guys, I've been really busy recently. Hoping to find some examples today and I'll look at the best fix for this.

**Comment by MrRJ45** [comment]
I've found some time to look at this and come up with a much better way of determining if the switch is one that can be stacked. Based on all of the output I can find, the word unit means it is stackable.

This should be much simpler than working from the model of the switch. I've just implemented this on our install so I can check all of our Dells in the morning once they have been backed up :smiley:
