### ISSUE TITLE
Rewrite procurve configs?

### ISSUE THREAD

**Issue by 1183519e** [ytti/oxidized#1978]
While oxidized works perfectly fine for my procurves, it's not safe to copy the config these switches produce to the command line of a switch. Two issues I'm aware of:

- Procurve have a default snmp-community after a factory reset. To make the config deployable, you would need to add `no snmp-community public` before all other snmp-community-lines.
- Ports need to be member of a vlan. If you have a vlan config like:
```
vlan 1
    no untagged 1-10
    no ip address
    exit
vlan 10 
    untagged 1-8
    tagged 9-10
    ip address 192.0.2.2 255.255.255.0
    exit
```
...the first block, when deployed on a new switch, would do nothing as all ports need to remain in the default vlan 1. After the second block, ports 9-10 would still be in vlans 1,10 with native vlan 1. A solution in the cases I know of would be to move the vlan 1 block down past any other vlan block.

First question before I start coding: Is it the scope of this project to handle the quirks of the OS and produce copy-paste-safe configs, or should this project keep producing configs as written by the OS without altering them?

**Comment by davama** [comment]
What about copying the config to `/cfg/startup-config` ?

```
scp my-backup-sw-config <host>:/cfg/startup-config
```

It will cause your switch to reboot, if it accepts the config. Otherwise nothing will happen and you will see in the logs what line was offending.

If i remember correctly you have to enable `ip ssh filetransfer` on a defaulted procurve switch to scp your file.

**Comment by 1183519e** [comment]
Thanks for your answer. That would certainly work for rolling back a config. 

My scope is (also) on replacing hardware, preferably on a single paste into a serial console or maybe other one-step solutions. I work in an environement where we don't always have a network engineer nearby. Therefore I want to keep the runbook as short and easy as possible.

**Comment by davama** [comment]
> First question before I start coding: Is it the scope of this project to handle the quirks of the OS and produce copy-paste-safe configs, or should this project keep producing configs as written by the OS without altering them?

The only "altering" that im aware is the removal of secrets.
I am not a fan of HP myself but I dont deploy from a serial console often (:disappointed: cisco rtrs); all remote.

If pasting to a serial console, why not just paste vlanX then vlan1 if that is an issue. Usually when I paste a config, I paste in junks just in case something spits out with an error.

If you have a template config then just scping the cfg would make everything easier since defaulted switch will get an IP from dhcp. Yes, dhcp would be needed, a router can easily do that.
