### ISSUE TITLE
BUG?: migrating to a new server, first git commit drops all files and starts from scratch.

### ISSUE THREAD

**Issue by ykuksenko** [ytti/oxidized#2033]
Hello and thank you for creating this project!

I automated my deployment of oxidized for migrating to a new server and do a `git clone --bare 1.1.1.1:path/to/repo /repo.git` to initialize the local repo. However the first commit that oxidized makes to resume the git history is it deletes all existing files and starts re-adding them one per commit.

I expected that only the file that is changing would be modified and not the deletion of all the other files. This seems to be a bug.

I may be completely wrong, but this may have something to do with the fact that a bare repo does not usually have an `index` (staging?) file in it as it is not a work directory. However immediately after a commit is made by oxidized the index file is present along with a `FETCH_HEAD` file. I was not able to find any `git` flags/arguments that would create an index file in a bare repo.

#631 requested a feature where oxidized itself would fetch the repo if it doesn't exist and that would be helpful here. For now I am using the suggested approach from that issue.

relevant bits of my config:
```
  output:                                                                                                                                                                        
    default: git                                                                                                                                                                 
    debug: true                                                                                                                                                                  
    git:                                                                                                                                                                         
      single_repo: true                                                                                                                                                          
      user: Oxidized                                                                                                                                                             
      email: oxidized@example.com                                                                                                                                                 
      repo: "/oxidized/oxidized.git"
  hooks:                                                                                                                                                                         
    remote:                                                                                                                                                                      
      type: githubrepo                                                                                                                                                           
      events: [post_store]                                                                                                                                                       
      remote_repo: 1.1.1.1:/backups/oxidized                                                                                                                                
      username: git                                                                                                                                                         
      publickey: /oxidized/oxidized@git.pub                                                                                                                                      
      privatekey: /oxidized/oxidized@git     
```

Thank you.

**Comment by clontarfx** [comment]
Oxidized will be initialising "/oxidized/oxidized.git". So this seems to be expected behaviour.

Need more information about your migration of Oxidized to a new server. You should be able to copy everything as-is, including the .git directory. Why are you manually initialising a new repo on your new server? Why aren't you letting Oxidized do it?

I assume it's because you want to retain git history, in which case you only need to clone your remote repo to your local oxidized.git. That's how I've done it many times myself.

Once you've cloned (without bare), you need to check .git/config and make sure the `[remote "origin"]` section is correct.

**Comment by chn42** [comment]
Just wanted to confirm the behaviour, not sure if this could be handled by Rugged, I'm not very familiar with ruby.

Steps to reproduce:
* create git repo with history, either manually or converted from rancid
* clone bare from this repo and use this as the base for output
* the cloned bare repo doesn't have a index file
* if you (regularly) clone from this bare repo, the clone does have the index file
* staring oxidised without the index file exactly reproduces the behaviour explained by @ykuksenko
* you can fix this issue by copying the index file from either the original repo, or the (regularly) cloned repo into the bare repo ahead of the first start of oxidized

A possible solution would be to use a regularly cloned repo for oxidized instead of a bare repo.

**Comment by Nayruden** [comment]
Somewhat related issue that explains the behavior seen in this bug -- https://github.com/ytti/oxidized/issues/1805#issuecomment-904033732
