### ISSUE TITLE
Backing Up WS-C2948G-GE-TX Running CatOS

### ISSUE THREAD

**Issue by doublejz** [ytti/oxidized#2063]
I have a old Cisco WS-C2948G-GE-TX running 8.4(11)GLX that I can't seem to get into Oxidized.

It reaches the device but throws an error as follows:
192.168.1.2 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^[\w.@-]+>\s?(\(enable\) )?$)"

I found some other catos.rb people modified and were using for CatOS but I had no luck and back to the "stock" catos.rb file.

]$ telnet 192.168.1.2
Trying 192.168.1.2...
Connected to 192.168.1.2.
Escape character is '^]'.

Cisco Systems, Inc. Console
Core Switch
Enter password:
core-switch> en
Enter password:
core-switch> (enable)

I did try SSH but it only uses SSHv1 so I don't think SSH will work. Either way, its not catching the prompts.

W, [2020-04-08T15:41:44.279329 #1838]  WARN -- : 192.168.1.2 raised Net::SSH::Exception (rescued RuntimeError) with msg "incompatible SSH version `SSH-1.5-1.2.26'"

]$ ssh -1 admin@192.168.1.2
admin@192.168.1.2's password:

Cisco Systems, Inc. Console
Core Switch
core-switch> en
Enter password:
core-switch> (enable)

Any suggestions as to why the ":" and ">" aren't being caught for login?

**Comment by doublejz** [comment]
Guessing I'm going to have to go back to rancid due to lack of replies here. :-(

**Comment by ytti** [comment]
You should use what ever you are comfortable with. If rancid works for you, no reason to spend your time on other systems.

I don't have personally time to help with trivial issues, as it would be half time job. There are many reason your problem may be happening, and there isn't enough information in your issue to answer, which means your issue is time expensive to solve, as you need so much help to solve it.
We don't know what is your enable set to, what you expect it to be (are you entering enable password, are you just pressing enter). You didn't record debug session of what Oxidized is doing with the device, i.e. what does the failing session look like.

**Comment by doublejz** [comment]
Didn't mean that I just want to bail on this and go to rancid but if I have to, I have to.
Regarding more information. I'm not sure what you want in regards to debug, this?

`D, [2020-04-15T19:24:44.541109 #21406] DEBUG -- : lib/oxidized/worker.rb: Added /192.168.1.2 to the job queue
D, [2020-04-15T19:24:44.541181 #21406] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2020-04-15T19:24:44.541615 #21406] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for 192.168.1.2 at 2020-04-15 19:24:44 UTC
D, [2020-04-15T19:24:45.542694 #21406] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2020-04-15T19:24:46.544063 #21406] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2020-04-15T19:24:47.545466 #21406] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2020-04-15T19:24:48.546824 #21406] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2020-04-15T19:24:49.548161 #21406] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2020-04-15T19:24:50.549539 #21406] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2020-04-15T19:24:51.550894 #21406] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2020-04-15T19:24:52.552233 #21406] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2020-04-15T19:24:53.553624 #21406] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2020-04-15T19:24:54.554996 #21406] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2020-04-15T19:24:55.556357 #21406] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2020-04-15T19:24:56.557706 #21406] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2020-04-15T19:24:57.559060 #21406] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2020-04-15T19:24:58.560457 #21406] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2020-04-15T19:24:59.561771 #21406] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2020-04-15T19:25:00.563167 #21406] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2020-04-15T19:25:01.564682 #21406] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2020-04-15T19:25:02.566294 #21406] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2020-04-15T19:25:03.567777 #21406] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2020-04-15T19:25:04.569137 #21406] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
W, [2020-04-15T19:25:04.589483 #21406]  WARN -- : 192.168.1.2 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^(\r?[\w.@:\/-]+[#>]\s?)$)"
D, [2020-04-15T19:25:04.589623 #21406] DEBUG -- : lib/oxidized/node.rb: Oxidized::Telnet failed for 192.168.1.2
D, [2020-04-15T19:25:04.589783 #21406] DEBUG -- : lib/oxidized/job.rb: Config fetched for 192.168.1.2 at 2020-04-15 19:25:04 UTC
W, [2020-04-15T19:25:05.571286 #21406]  WARN -- : /192.168.1.2 status no_connection, retry attempt 1
`

Also

```
[oxidized@oxidized oxidized]$ grep 192.168.1.2 router.db
192.168.1.2:catos:admin:L3tMe1n!:L3tMe1n!NoW!
[oxidized@oxidized oxidized]$

```
Does this help at all?

**Comment by JAM2199562** [comment]
Try to modify the following line in the config file
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
I am not familiar with the syntax of regular expressions, so I simply executed the following command
no banner login
no banner motd

**Comment by wk** [comment]
The issue appears to be caused by the device not having complete AAA authentication configured, which the model expects. The device thus displays a simple password-only prompt during telnet login that defers from the prompt that is displayed with AAA configured.

The prompt the device emits: `Enter password:`
The prompt the model expects during telnet login: [`Password:`](https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/catos.rb#L27)

As a result of this discrepancy, the model never completes logging in via telnet and does not see the prompt in order to execute the configuration collection commands.

You could try copying the `catos.rb` file into your `~/.config/oxidized/model/` directory, and changing the relevant line into, for example, `password /^(Enter password|Password):/`. After introducing this change, restart Oxidized.
