### ISSUE TITLE
Oxidized can't backup configuration's Huawei Swicth

### ISSUE THREAD

**Issue by PutuGandi** [ytti/oxidized#2175]
hello i need help ,
i got log like this:
**172.16.10.64 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^(<[\w.-]+>)$)"**
when i want to add Switch Huawei S5720 for backup configuration.

**/etc/hosts**:
`172.16.10.64     ACS01-CCTV-PIN-CARGO-INT`

**router.db**:
`ACS01-CCTV-PIN-CARGO-INT:vrp`

**config**:
---
username: lagandi
password: lagandi
model: junos
interval: 1800
use_syslog: true
log: /home/oxidized/.config/oxidized/logs
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: 
  enable: lagandi
groups: {}
models: {}
pid: /home/oxidized/.config/oxidized/pid
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: git
  file:
    directory: /home/oxidized/.config/oxidized/configs
  git:
    user: Oxidized
    email: o@example.com
    repo: /home/oxidized/.config/oxidized/oxidized.git
source:
  default: csv
  csv:
    file: /home/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    gpg: false
model_map:
  cisco: ios
  juniper: junos
  huawei: vrp

# vrp.ios:
class VRP < Oxidized::Model
    
  prompt /^(<[\w.-]+>)$/
  comment '# '

  cmd :secret do |cfg|
    cfg.gsub! /(pin verify (?:auto|)).*/, '\\1 <PIN hidden>'
    cfg.gsub! /(%\^%#.*%\^%#)/, '<secret hidden>'
    cfg
  end

  cmd :all do |cfg|
    cfg.each_line.to_a[1..-2].join
  end
 
  cfg :telnet do
    username /^Username:$/
    password /^Password:$/
  end

  cfg :telnet, :ssh do 
    post_login 'screen-length 0 temporary'
    pre_logout 'quit'
  end

  cmd 'display version' do |cfg|
    cfg = cfg.each_line.select {|l| not l.match /uptime/ }.join
    comment cfg
  end

  cmd 'display device' do |cfg|
    comment cfg
  end

  cmd 'display current-configuration' do |cfg|
    cfg
  end
  
end 

Thank You

**Comment by Zuquim** [comment]
If I'm not mistaken, this happens after a new local SSH user is created (not sure if the behavior is limited to this type of user) in a Huawei switch. When the new user logs in, the device displays the following prompt:
```
Warning: The initial password poses security risks.
The password needs to be changed. Change now? [Y/N]:
```
If answered with anything (including `<cr>`) other than `Y` or `N`, it will enter a loop displaying the prompt below until the user inputs `Y` or `N`, or the prompt timeout* is reached (which is `N` by default).
```
Error: Please choose 'YES' or 'NO' first before pressing 'Enter'. [Y/N]:
``` 

_* I've tested this said timeout, and it is 30 seconds counting from the last time the device received an input (any kind of keystroke such as letters, numbers, or `<cr>`). Tested on a S6720 running VRP 5.170 (V200R010C00SPC600)._

This post login behavior will persist for this user until the password is updated by answering `Y` in this prompt.

I believe the VRP model needs to be updated/adapted to expect and bypass this prompt in order to fix the issue.

Can you check if this is the issue that you're experiencing by manually logging, using terminal (SSH/Telnet), on this specific device using the username/password configured in Oxidized, @PutuGandi ?

**Comment by PutuGandi** [comment]
hello @Zuquim thanks for your response. if it works by manually logging using telnet then what spesific code should i change ?

**Comment by Zuquim** [comment]
Sorry for the delay, @PutuGandi 

Did you check if the device is reachable by using SSH/Telnet to log in the device **from the Oxidized server**?

When you manually logged in, the device did **not** prompt you to change the current password? If that's the case, and Oxidized is still unable to log in and get the device's configuration, you should enable Oxidized debugging options and analyze it's output to check what the problem might be before trying to adapt the source code.

If the device is still prompting the user to change the password right after the successful login, then you have 2 options:
1. manually change the Oxidized configured backup user password in each device to avoid the issue (not a good option if you're facing this issue in dozens of devices)
2. adapt the source code for the VRP module so that it may expect this password update prompt and answer `N` to keep using the same password and be able to get the device's configuration.

I don't really know Ruby, so I won't be able to assist you very well with option 2.

Also, I have not tested if this password update prompt happens with AAA (TACACS/RADIUS) users. If the devices happen to not prompt for password update with AAA users, then it might be a good option to setup a AAA server.

**Comment by PutuGandi** [comment]
hay @Zuquim thanks for your assist, so i have created user with AAA server then Huawei's configuration is able to be backed up by oxidized.
😄 👍

**Comment by wlopez506** [comment]
Hello good, I need to know how to do the following option:

Adapt the source code for the VRP module so that it may expect this password update prompt and answer N to keep using the same password and be able to get the device's configuration.

**Comment by muaythai** [comment]
Hi.

I was also struggling with this issue.
I solved the problem in the most rudimentary way.

Added sleep 30 for vrp content.
  cfg :telnet, :ssh do
    sleep 30
    post_login 'screen-length 0 temporary'
    pre_logout 'quit'
  end

For "[Y/N]:", leave 30 seconds after the prompt is displayed and the normal prompt will appear.
Remember to also increase the timeout value in the oxidized config file.

**Comment by LanasVK** [comment]
hello, we have managed to make the backup of Huawei HUAWEI S5732, with this model configuration, I hope it will help you.

class Huawei < Oxidized::Model
  # Prompt for Huawei devices
  prompt /^<.*>/

  # Handle paging (disable more)
  expect /^  ---- More ----$/ do |data, re|
    send ' '
    data.sub re, ''
  end

  # Login prompt
  expect /^Username:/ do |data, re|
    send @node.auth[:username] + "\n"
    data.sub re, ''
  end

  expect /^Password:/ do |data, re|
    send @node.auth[:password] + "\n"
    data.sub re, ''
  end

  # Command to fetch the configuration
  cmd 'display current-configuration' do |cfg|
    cfg.gsub! /^  ---- More ----$/, '' # Remove more prompts
    cfg
  end

  # Configuration settings
  cfg :ssh do
    post_login 'screen-length 0 temporary' # Disable paging
    pre_logout 'quit'
  end
end

Good Luck!!
