### ISSUE TITLE
getting "version not found" error, when trying to look old version config file

### ISSUE THREAD

**Issue by from88** [ytti/oxidized#2222]
hello, using the newest oxidized version. Also configured output to github via single repo and no groups configured.

```
prod [root@dcoxid002prvjay ~]# gem list | grep oxidi
oxidized (0.28.0, 0.26.3)
oxidized-script (0.6.0)
oxidized-web (0.13.1)
```

My config is here:

```
username: s-oxi
password: punt
model: cisco
interval: 3600
log: ~/.config/oxidized/log
debug: false
threads: 30
timeout: 180
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
groups: {}
rest: 0.0.0.0:8888
pid: ~/.config/oxidized/oxidized.pid
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
    single_repo: true
    user: user
    email: oxidized@domain.com
    repo: /home/oxidized/.config/oxidized/oxidized.git
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: "git@gitz.xxxx.com:network/network-configs.git"
    publickey: /etc/oxidized/.ssh/id_rsa.pub
    privatekey: /etc/oxidized/.ssh/id_rsa
source:
  default: csv
  csv:
    file: ~/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
      username: 3
      password: 4
    vars_map:
      enable: 5
model_map:
  cisco: ios

```
I saw that where was info few years ago about some bug. But as the more than three years already passed - is it the same bug or something different ? Thanks

**Comment by from88** [comment]
seems like appending a default group is a workaround for this issue. 
Would be nice to have this bug fixed.

**Comment by Edzilla2000** [comment]
Hi, can you tell me how you appended the default group? I have the same issue.

**Comment by from88** [comment]
> Hi, can you tell me how you appended the default group? I have the same issue.

it should be appended in router.db file, like that:

```defaultgroup:ITCNCS01:101.0.20.250:iosxr
defaultgroup:ITCMGMT:101.1.254.232:ios
defaultgroup:ITCMGMT02:101.13.254.176:ios
```

**Comment by robertcheramy** [comment]
I can reproduce this with:
- output: git
- single_repo
- no group defined

The bug is probably here https://github.com/ytti/oxidized/blob/4b0b65535cb15e3eb05a237a033a22996c9b29e6/lib/oxidized/output/git.rb#L142

Works when replacing the line with:
```
      path = "#{group}/#{node.name}" if !group.empty? && @cfg.single_repo?
```

**Comment by robertcheramy** [comment]
Better fix (group can be nil):
```
path = "#{group}/#{node.name}" if group && !group.empty? && @cfg.single_repo?
```

I have to check in oxidized-web why we sometimes get group = nil and sometimes group = "".

**Comment by ytti** [comment]
Or if !group&.empty? and @cfg.single_repo? 

But maybe better if we could guarantee group type to be string.

**Comment by robertcheramy** [comment]
`/node/fetch/` sends a `nil` group when no group is present in the URL

In `/node/version?node_full=(node)`, group= is passed to the parameters (so group is an empty string in ruby) when a group is empty: https://github.com/ytti/oxidized-web/blob/4addf32d794d66261a551a5350cb963b0f50a61e/lib/oxidized/web/views/versions.haml#L32

Passing no group crashes because `version.haml` awaits a value  https://github.com/ytti/oxidized-web/blob/4addf32d794d66261a551a5350cb963b0f50a61e/lib/oxidized/web/views/version.haml#L4

I prefer to fix this in oxidized.

I did not know the &. operator, which is pretty cool. Unfortunately, it won't work here because of the negation:
group = nil => group&.empty? returns nil => !group&.empty? returns **true**
group = '' => !group&.empty? returns **false**
group = "xx" => !group&.empty? returns true
