### ISSUE TITLE
net::ssh could not settle on host_key algorithm -- needs dh-sha256

### ISSUE THREAD

**Issue by s1eelra1** [ytti/oxidized#2314]
Hi I've recently got oxidized working and providing backups of devices, however, with the latest device installed in production it has the dh-group14-sha256 enabled. ssh on the host works fine to the device.

Unfortunately when I added it to oxidized, it is giving me an error in the logs:
raised Net::SSH::Exception (rescued RuntimeError) with msg "could not settle on kex algorithm

Researching it looks like this is related to the version of net::ssh. I have tried to just test if I can force oxidized 0.28... to use the newer version 6.1 of net::ssh. But I've had no luck.

I've found a few issue references: could not settle on host_key algorithm #686
Support strong SSH KexAlgorithms/MACs #733
forcing oxidized to use the latest version of net-ssh. #2043

So is there a method to force oxidized to load with the newer version of net:ssh. Or is there some flag that I need to use in the config to help with that? 

oxidized (0.28.0, 0.26.3)
net-ssh (6.1.0, 5.2.0)

**Comment by mweaver78** [comment]
Did you ever find a resolution for this?

**Comment by yvesboudreau** [comment]
I have same issue, any update?

**Comment by mortzu** [comment]
https://github.com/ytti/oxidized/issues/2432#issuecomment-995067799

**Comment by FlorianHeigl** [comment]
can verifiy same issue with Mellanox Onyx 3.9.3220 
Using docker image oxidized/oxidized:latest

i had found no good workaround and had to settle for  `no ssh server security strict` temporarily.

**Comment by Bierchermuesli** [comment]
> i had found no good workaround (*) and had to settle for `no ssh server security strict` temporarily.
where?

**Comment by FlorianHeigl** [comment]
@Bierchermuesli in the switch's config. you can find the info for the security related settings in the Mellanox/Nvidia docs. I don't have the title, but iirc there was a security hardening guide for Onyx or MLNX-OS.

**Comment by Bierchermuesli** [comment]
@maavcrusoe your workaround might works but its not so nice by renaming the folders... (future updates or other depencies relies on 5.2?
Also: wit 7.01 you might have issues with older devices with old cryptos. (`needs append_all_supported_algorithms: true` statement

There is a open pull request for 7.0.0 you can use: https://github.com/ytti/oxidized/pull/2570 This works for me well.

**Comment by maavcrusoe** [comment]
Hi @Bierchermuesli I know was only for test, I spend some hours more to fix better that's my working solution:

1. I've reinstalled net-ssh -v 5.2.0 and -v 7.0.1 (not beta)
2. reinstalled oxidized -v 0.28 
3. upgrade ruby because on debian 10 can't intall ruby gem net-ssh 7 or I can't (https://www.howtoforge.com/how-to-install-ruby-on-rails-on-debian-10/)
4. changed on this file `nano /usr/local/rvm/gems/ruby-2.6.6/gems/oxidized-0.28.0/oxidized.gemspec`
`s.add_runtime_dependency 'net-ssh', '~> 5` to` s.add_runtime_dependency 'net-ssh', '~> 7`
5. on this other file `nano /usr/local/rvm/gems/ruby-2.6.6/specifications/oxidized-0.28.0.gemspec`
`s.add_runtime_dependency(%q<net-ssh>.freeze, ["~> 5"])` to `s.add_runtime_dependency(%q<net-ssh>.freeze, ["~> 7"])`
6. and finally see on debug log form oxidized when asking to my new swtich  `SSH-2.0-Ruby/Net::SSH_7.0.1 x86_64-linux'`
7. on the old switches oxidized stablish NET::SSH_5.2 and works well

hope it helps someone 😀

**Comment by FlorianHeigl** [comment]
Hi @AxisNL - I'll try to check again. I have 3 different envs with such switches that's why maybe I was more successful, but I also forgot the details once it was working.
My tl;dr would be that during setup I followed some security guide (NIST?) and then had to pedal back on config settings until it worked.

**Comment by FlorianHeigl** [comment]
@AxisNL I suspect it can be due to your client OS, but no deeper proof for it...

**Comment by fixed77** [comment]
i added in lib/oxidized/input/ssh.rb file in make_ssh_opts function:
```
130c130,131
<         port:                       (vars(:ssh_port) || 22).to_i
---
>         port:                       (vars(:ssh_port) || 22).to_i,
>         append_all_supported_algorithms: true
```
 to solve this problem

**Comment by chrisch80** [comment]
@fixed77: You only added this line and now better ciphers are working with old net-ssh version? For me this is not working.

**Comment by sid3windr** [comment]
Running into this same issue as well with my hardened SSH configurations. Is there any reason why net-ssh can't be bumped to 7?

**Comment by mortzu** [comment]
as can be seen in https://github.com/ytti/oxidized/blob/master/oxidized.gemspec#L27 net-ssh is already on version 7

**Comment by sid3windr** [comment]
I see that on your URL, but it's not in the gem I can install on Debian Stable (0.28.0) due to Ruby 3 requirement.
