### ISSUE TITLE
Telco Systems T-Marc-3308 Prompt issue

### ISSUE THREAD

**Issue by SkylerBlumer** [ytti/oxidized#2474]
I'm trying to create a custom module for a T-Marc-3308.  The issue is I get a login message that oxidized is trying to use in the prompt detection. How to I ignore this message?

This is the code I'm trying..

-----------------
class TMARK < Oxidized::Model
  prompt /^(\r?[\w.@_()-]+[#]\s?)$/
  comment '! '

  cmd :all do |cfg|
    cfg.each_line.to_a[2..-2].join.delete("\n")
  end

  cmd 'show running-config' do |cfg|
    cfg
  end

  cfg :ssh do
    pre_logout 'logout'
  end

  cfg :ssh do
    username /^Username:/
    password /^Password:/
  end
end
------------------

I'm getting this error..

W, [2022-02-09T14:15:28.312028 #10374]  WARN -- : 192.168.0.1 raised Oxidized::PromptUndetect with msg "Telco Systems T-Marc-3308
oxidized connected from 192.168.0.2 using ssh on ms0-tmark-lab-001
ms0-tmark-lab-001# not matching configured prompt (?-mix:^(\r?[\w.@_()-]+[#]\s?)$)"
W, [2022-02-09T14:15:28.823529 #10374]  WARN -- : telcon/ms0-tmark-lab-001 status no_connection, retries exhausted, giving up

------------------

Example of the login message. Where ms0-tmark-lab-001# is the normal prompt.

Telco Systems T-Marc-3308
oxidized connected from 192.168.0.2 using ssh on ms0-tmark-lab-001
ms0-tmark-lab-001#

**Comment by ikewinski** [comment]
There is a [telco.rb in the distribution](https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/telco.rb), but it doesn't work for me. I also get Oxidized::PromptUndetect using it. I've deleted both system banner and system ssh-banner on the device, and also tried falling back to telnet just in case the problem was in ssh somewhere.

There are some very weird characters in the default system banners. If I debugto rsyslog I get to see the octals. It looks like this:

Oxidized::PromptUndetect with msg "**#015#012**T-Marc-3308**#015#012#015#012**backup connected from 192.168.12.2 using ssh on T-Marc-3308**#015#012#033[?7h**T-Marc-3308# not matching configured prompt (?-mix:^(\r?[\w.@_()-]+[#]\s?)$)"

I question whether the existing telco.rb file has ever worked. For one thing, there is no valid "terminal length 0" command in Telco Systems BiNOX operating system, as the telco.rb model specifies:

```
  cfg :ssh, :telnet do
    post_login 'terminal length 0'
    pre_logout 'exit'
  end
```

The way you disable the pager in BiNOX is "show running-config | nomore".

I've made it further, setting **prompt /(\s?.+#\s?)$/** I can see that "show running-config | nomore" is being executed. But it never finds that prompt again so the job never completes.
