### ISSUE TITLE
Cisco configuration can't show all when modified the model file

### ISSUE THREAD

**Issue by TorleyTowne** [ytti/oxidized#2518]
I modified the model of ios.rb to satisfied the need of backing up our device configuration. But when I use the expect statement, the show running-configuration command doesn't show all.  **New modle code is  as follow**，
`class CiscoNEW < Oxidized::Model

  prompt /([\w.@-]+[#>]\s?)$/
  comment '# '

  cmd 'show version' do |cfg|
    comment cfg
  end

  cmd 'show running-config' do |cfg|
    expect /^\s--- More ---\s+.*$/ do |data, re|
      send ' '
      data.sub re, ''
    end
    cfg
  end

  cfg :telnet do
    username /.*login:/
    password /^Password:/
  end

  cfg :telnet, :ssh do
    if vars :enable
      post_login do
        send "enable\n"
        cmd vars(:enable)
      end
    end
    post_login 'terminal length 0'
    pre_logout 'exit'
  end
end`

**And the result is as follow,**
`XXX-XXX-XXX# show running-config
: Saved

: 
: Hardware:   XXX-XX-XX
:
ASA Version 9.10(1)42 <context>
!
hostname XXX
domain-name show
enable password ***** xxxx
names
ip local pool XXX x.x.x.x-x.x.x.x mask x.x.x.x

!
interface Ethernet1/1.x
 description xxx
 nameif xxx
 security-level 50
 ip address x.x.x.x x.x.x.x`

**Any suggestions to solve this problem? Thank you so much.**

**Comment by Tori5310** [comment]
I change another way to handle the page. Unfortunately，the command works well on SecureCRT，but it's not work well in the model. Could any one help me? Many thanks.
**Codes as follow,**
`class CiscoNew < Oxidized::Model

  prompt /([\w.@-]+[#>]\s?)$/
  comment '!'

  cmd 'show version' do |cfg|
    comment cfg
  end

  cmd 'show running-config all' do |cfg|
    cfg
  end

  cfg :telnet do
    username /.*login:/
    password /^Password:/
  end

  cfg :telnet, :ssh do
    if vars :enable
      post_login do
        send "enable\n"
        cmd vars(:enable)
      end
    end
    **post_login 'terminal pager 0'
    post_login 'terminal pager line 0'**
    pre_logout 'exit'
  end
end`

**Comment by Tori5310** [comment]
Update the progress of debug.
I removed the code "post_login 'terminal pager line 0'” since it has similar function to code “post_login 'terminal pager 0'” . According to the debug info，it seems like that the device has return all configuration back when the command _show running-config_ is sent，but the answer is not fully written into the backup file for some reasons I can't figure out yet. Debug info is as follow,
`D, [2022-04-15T10:13:45.724157 #9971] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "terminal pager 0", block: nil at XXX-XXX-XXX_XXX-001
D, [2022-04-15T10:13:45.724739 #9971] DEBUG -- : lib/oxidized/input/ssh.rb terminal pager 0 @ XXX-XXX-XXX_XXX-001 with expect: /([\w.@-]+[#>]\s?)$/
D, [2022-04-15T10:13:45.724930 #9971] DEBUG -- socket[f65c20]: queueing packet nr 11 type 94 len 44
D, [2022-04-15T10:13:45.725011 #9971] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/([\w.@-]+[#>]\s?)$/] at XXX-XXX-XXX_XXX-001
D, [2022-04-15T10:13:45.925647 #9971] DEBUG -- socket[f65c20]: sent 68 bytes
D, [2022-04-15T10:13:46.026026 #9971] DEBUG -- socket[f65c20]: read 136 bytes
D, [2022-04-15T10:13:46.026236 #9971] DEBUG -- socket[f65c20]: received packet nr 17 type 94 len 44


D, [2022-04-15T14:17:34.827739 #21909] DEBUG -- : lib/oxidized/model/model.rb Executing show running-config
D, [2022-04-15T14:17:34.827852 #21909] DEBUG -- : lib/oxidized/input/ssh.rb show running-config @ XXX-XXX-XXX_XXX-001 with expect: /([\w.@-]+[#>]\s?)$/
D, [2022-04-15T14:17:34.828045 #21909] DEBUG -- socket[122e5b0]: queueing packet nr 13 type 94 len 44
D, [2022-04-15T14:17:34.828199 #21909] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/([\w.@-]+[#>]\s?)$/] at XXX-XXX-XXX_XXX-001
D, [2022-04-15T14:17:35.029001 #21909] DEBUG -- socket[122e5b0]: sent 68 bytes
D, [2022-04-15T14:17:35.129575 #21909] DEBUG -- socket[122e5b0]: read 68 bytes
D, [2022-04-15T14:17:35.129852 #21909] DEBUG -- socket[122e5b0]: received packet nr 47 type 94 len 44
I, [2022-04-15T14:17:35.129950 #21909]  INFO -- net.ssh.connection.session[16ff2ec]: channel_data: 0 21b
I, [2022-04-15T14:17:35.330820 #21909]  INFO -- net.ssh.connection.keepalive[16fef04]: sending keepalive 0
I, [2022-04-15T14:17:35.330928 #21909]  INFO -- net.ssh.connection.session[16ff2ec]: sending global request keepalive@openssh.com
D, [2022-04-15T14:17:35.331170 #21909] DEBUG -- socket[122e5b0]: queueing packet nr 14 type 80 len 44
D, [2022-04-15T14:17:35.462557 #21909] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2022-04-15T14:17:35.532176 #21909] DEBUG -- socket[122e5b0]: read 3456 bytes
D, [2022-04-15T14:17:35.532346 #21909] DEBUG -- socket[122e5b0]: sent 68 bytes
D, [2022-04-15T14:17:35.633164 #21909] DEBUG -- socket[122e5b0]: received packet nr 48 type 94 len 28
I, [2022-04-15T14:17:35.633440 #21909]  INFO -- net.ssh.connection.session[16ff2ec]: channel_data: 0 9b
D, [2022-04-15T14:17:35.634053 #21909] DEBUG -- socket[122e5b0]: received packet nr 49 type 94 len 28
I, [2022-04-15T14:17:35.634257 #21909]  INFO -- net.ssh.connection.session[16ff2ec]: channel_data: 0 2b
D, [2022-04-15T14:17:35.634932 #21909] DEBUG -- socket[122e5b0]: received packet nr 50 type 94 len 28
I, [2022-04-15T14:17:35.635066 #21909]  INFO -- net.ssh.connection.session[16ff2ec]: channel_data: 0 4b
.
.
.
D, [2022-04-15T14:17:51.284629 #21909] DEBUG -- socket[122e5b0]: read 796 bytes
D, [2022-04-15T14:17:51.285179 #21909] DEBUG -- socket[122e5b0]: received packet nr 7745 type 94 len 44
I, [2022-04-15T14:17:51.285339 #21909]  INFO -- net.ssh.connection.session[16ff2ec]: channel_data: 0 19b
D, [2022-04-15T14:17:51.285691 #21909] DEBUG -- socket[122e5b0]: received packet nr 7746 type 94 len 44
I, [2022-04-15T14:17:51.285773 #21909]  INFO -- net.ssh.connection.session[16ff2ec]: channel_data: 0 17b
D, [2022-04-15T14:17:51.285918 #21909] DEBUG -- socket[122e5b0]: received packet nr 7747 type 94 len 44
I, [2022-04-15T14:17:51.285998 #21909]  INFO -- net.ssh.connection.session[16ff2ec]: channel_data: 0 17b
D, [2022-04-15T14:17:51.286168 #21909] DEBUG -- socket[122e5b0]: received packet nr 7748 type 94 len 44
I, [2022-04-15T14:17:51.286237 #21909]  INFO -- net.ssh.connection.session[16ff2ec]: channel_data: 0 18b
D, [2022-04-15T14:17:51.286354 #21909] DEBUG -- socket[122e5b0]: received packet nr 7749 type 94 len 44
I, [2022-04-15T14:17:51.286415 #21909]  INFO -- net.ssh.connection.session[16ff2ec]: channel_data: 0 17b
D, [2022-04-15T14:17:51.286527 #21909] DEBUG -- socket[122e5b0]: received packet nr 7750 type 94 len 28
I, [2022-04-15T14:17:51.286606 #21909]  INFO -- net.ssh.connection.session[16ff2ec]: channel_data: 0 3b
D, [2022-04-15T14:17:51.286769 #21909] DEBUG -- socket[122e5b0]: received packet nr 7751 type 94 len 60
I, [2022-04-15T14:17:51.286834 #21909]  INFO -- net.ssh.connection.session[16ff2ec]: channel_data: 0 37b
D, [2022-04-15T14:17:51.286949 #21909] DEBUG -- socket[122e5b0]: received packet nr 7752 type 94 len 76
I, [2022-04-15T14:17:51.287008 #21909]  INFO -- net.ssh.connection.session[16ff2ec]: channel_data: 0 49b
D, [2022-04-15T14:17:51.287118 #21909] DEBUG -- socket[122e5b0]: received packet nr 7753 type 94 len 76
I, [2022-04-15T14:17:51.287178 #21909]  INFO -- net.ssh.connection.session[16ff2ec]: channel_data: 0 49b
D, [2022-04-15T14:17:51.287301 #21909] DEBUG -- socket[122e5b0]: received packet nr 7754 type 94 len 28
I, [2022-04-15T14:17:51.287362 #21909]  INFO -- net.ssh.connection.session[16ff2ec]: channel_data: 0 7b
D, [2022-04-15T14:17:51.287494 #21909] DEBUG -- socket[122e5b0]: received packet nr 7755 type 94 len 44
I, [2022-04-15T14:17:51.287554 #21909]  INFO -- net.ssh.connection.session[16ff2ec]: channel_data: 0 23b`

**Comment by ciscolive** [comment]
try with my repo : https://github.com/ciscolive/oxidized
```shell
git clone  https://github.com/ciscolive/oxidized
cd oxidized 
gem build 
gem install ./local.gem
```
