### ISSUE TITLE
cisco ios commit "NVRAM config last updated"

### ISSUE THREAD

**Issue by pubyun** [ytti/oxidized#2644]
the master code has a issue commit "NVRAM config last updated" every time:

https://github.com/ytti/oxidized/commit/4f97d9cd6e7fdcbffab5bd48d1ad904f0489a5ea

i add one line code, its OK:

`cfg.gsub! /^! NVRAM config last updated.*\n/, ''`

**Comment by ytti** [comment]
Isn't this debatable? Why is it changing every time? Do you have automation issuing 'write' periodically? Can we be confident that everyone else wants to ignore when the NVRAM was hit? I could imagine some want to record that information?

**Comment by pubyun** [comment]
cisco IOS will update the "NVRAM config last updated" constantly.
https://github.com/ytti/oxidized/issues/456

so we should delete "NVRAM config last updated" line, otherwise oxidized will commit every time it fetch config.

this commit remove the code:
https://github.com/ytti/oxidized/commit/4f97d9cd6e7fdcbffab5bd48d1ad904f0489a5ea

**Comment by ytti** [comment]
One of us is not understanding #456, in #456 it was also a problem that NVRAM got hit, problem caused by ISE. 

The NVRAM is hit, when NVRAM is updated, which occurs when you hit 'write' or copy, which could happen via SNMP.

The common case is, NVRAM stays unchanged until users hits 'write', and the common case is, that operators want to know history when these occurred.

If your NVRAM is changing all the time, you probably want to ask 'why' and then answer that question. 

I have some worries about security aspect, like could someone want to sneak code in Oxidized as part of more elaborate attack, code which makes it harder for target to know attack occurred. I know I am not motivated at 0 compensation level to keep track of this, but it does concern me.

**Comment by ytti** [comment]
I am very skeptical if this is common need. We have robust way of extending models for local needs. So we need to understand if this is something that happens commonly, or just you. If it is not common, like I believe, there is no reason to modify globally, for local demand.

Are you confident yours is changing because of NTP? Because I am skeptical of that. Do you have any SNMP, netconf tooling which might update config? 

How often does it change? What is the trigger? 

I did bug search but couldn't really find issues about NVRAM getting updated periodically, I did find issues of NVRAM not getting updated when it should.

**Comment by pubyun** [comment]
here some case:

https://github.com/ytti/oxidized/issues/1190

**Comment by pubyun** [comment]
we have no way such as snmp or netconf to update config.

we set config "interval: 3600" for oxidized and git commit every hour when oxidized fetch config from cisco 4948.

then  we find ”ntp clock-period“ changes every time.

**Comment by ytti** [comment]
#1190 also does not explain what is hitting the config, something is.

This is eminently debuggable and also TAC can help answering.

I am not sure if 'clock-period' is related to your NVRAM problem or not, I do know that the command is deprecated since 15.0 and I've not seen this problem even when it was still a thing. 

But what I do know is that it's not normal that NVRAM keeps updating always, and you probably should investigate why it is happening.
