### ISSUE TITLE
oxidized 0.29.0

### ISSUE THREAD

**Issue by vi-lgtm** [ytti/oxidized#2756]
Hello,
I'm trying to install oxidized 0.29.0 on Debian 10.

If I install with _gem install oxidized_ it installs 0.28.0 version.

If I install with
_git clone https://github.com/ytti/oxidized.git
cd oxidized/
gem install bundler
rake install_

I got error:

**root@VM-OXIDIZED:~/oxidized# rake install
oxidized 0.29.0 built to pkg/oxidized-0.29.0.gem.
rake aborted!
Running `gem install /root/oxidized/pkg/oxidized-0.29.0.gem` failed with the following output:

ERROR:  Error installing /root/oxidized/pkg/oxidized-0.29.0.gem:
        oxidized-0.29.0 requires Ruby version >= 3.0. The current ruby version is 2.7.4.191.

/var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/gem_helper.rb:211:in `sh'
/var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/gem_helper.rb:101:in `install_gem'
/var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/gem_helper.rb:57:in `block in install'
/usr/share/rubygems-integration/all/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => install
(See full trace by running task with --trace)**

**Comment by aschaber1** [comment]
Hello, 
`0.29.0` requires Ruby 3.0 and higher. It looks like you're using Ruby 2.7. 

Please install Ruby 3.0 or newer and try again. 

Best regards,
Alexander

**Comment by raunz** [comment]
Is there a specific technical codebase reason to increase ruby required version from 2.3 to 3.0? 
Ruby requirement can't be met on any stable debian release, as debian10 has ruby 2.5 and current stable debian11 has ruby 2.7. Ruby 3+ just isn't available on current debian stable releases (afaik rvm isn't feasible solution). 
Debian 12 (testing) has Ruby3.1, but that hasn't yet a proposed release date.

Due to ruby3.0 requirement latest gem for debian11 is still 0.28 :(

**Comment by aschaber1** [comment]
Besides that Ruby 2.7 is no longer supported by Ruby[1], there was also a dependency that had Ruby 3.0+ dependency. Don't remember which one though. My goal was it to have current versions throughout the supply chain, to avoid outdated and potentially vulnerable packages.

[1] https://www.ruby-lang.org/en/downloads/branches/

**Comment by marnovdm** [comment]
Hi Alexander, nice to see a new release for Oxidized, thanks! I was also struggling with the Ruby requirement in combination with a stable Debian release, perhaps it would be helpful to add some info to the docs on how this could be installed? I imagine many users running into this.

I tried to install a compatible Ruby version manually but found there are many different installation methods available and it was not clear to me (as someone not familiar with Ruby ecosystem) which approach is recommended. My current attempt is using RVM, if that is a recommended approach I could open a pull request to add this documentation but I'm not convinced this is the easiest method yet.

Weird that Debian 11 does not offer a supported Ruby version...

**Comment by ilGino** [comment]
> Hello, I'm trying to install oxidized 0.29.0 on Debian 10.
> 
> If I install with _gem install oxidized_ it installs 0.28.0 version.
> 
> If I install with _git clone https://github.com/ytti/oxidized.git cd oxidized/ gem install bundler rake install_
> 
> I got error:
> 
> **root@VM-OXIDIZED:~/oxidized# rake install oxidized 0.29.0 built to pkg/oxidized-0.29.0.gem. rake aborted! Running `gem install /root/oxidized/pkg/oxidized-0.29.0.gem` failed with the following output:
> 
> ERROR: Error installing /root/oxidized/pkg/oxidized-0.29.0.gem: oxidized-0.29.0 requires Ruby version >= 3.0. The current ruby version is 2.7.4.191.
> 
> /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/gem_helper.rb:211:in `sh' /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/gem_helper.rb:101:in `install_gem' /var/lib/gems/2.7.0/gems/bundler-2.4.12/lib/bundler/gem_helper.rb:57:in `block in install' /usr/share/rubygems-integration/all/gems/rake-13.0.3/exe/rake:27:in `<top (required)>' Tasks: TOP => install (See full trace by running task with --trace)**

Hello,

I suggest you may follow this route: install a single debian _testing_ package in a debian _stable_ system.

Beware that this may replace more package on your system, upgrading them from the stable branch to the testing branch, so make some laboratory before running into production.
In my case, in a fresh new debian stable (11 codename _bullseye_) virtual machine, installing ruby 3.1 from testing (12 codename _bookworm_) also pulled a handful of other upgraded packages as well, GNU libc included.
This should not be a major issue since the apt system is usually smart at respecting dependencies.

Indications are like:

https://tipstricks.itmatrix.eu/installing-debian-testing-packages-in-stable-system/

The final comand will be:

`apt-get -t testing install ruby`

and it will install ruby 3.1 instead of the ruby 2.7 of the current stable branch.

Hope this helps
Regards
GG

**Comment by umiseaz** [comment]
root@oxidized:~# sudo gem update oxidized
Updating installed gems
Updating oxidized
Fetching rugged-1.6.3.gem
Fetching oxidized-0.29.1.gem
Fetching net-ssh-7.1.0.gem
Successfully installed net-ssh-7.1.0
Building native extensions. This could take a while...
Successfully installed rugged-1.6.3
ERROR:  Error installing oxidized:
	There are no versions of oxidized (= 0.29.1) compatible with your Ruby & RubyGems
	oxidized requires Ruby version >= 3.0. The current ruby version is 2.7.0.0.
Gems updated: net-ssh rugged oxidized
root@oxidized:~# 
root@oxidized:~# 
root@oxidized:~# ruby --version
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
root@oxidized:~# 

any can help ? ruby ver is 3.0 already
