### ISSUE TITLE
Group link issue 

### ISSUE THREAD

**Issue by andreas1o** [ytti/oxidized#283]
Sorry if my lack of ruby and programing skills is make me look bad =).

I think I found another issue when working with groups.

The config is saved direct under the folder where I point the output. 

utput:
      default: file
      file:
        directory: /home/admin1o/.config/oxidized/configs

However when I have a group mapping the configs are saved under 
/home/admin1o/.config/oxidized/groupname

That brakes the fetch feature in under the 
http://X.X.X.X:8888/nodes
That points to 
http://X.X.X.X:8888/node/fetch/default/nodename

And not 
http://X.X.X.X:8888/node/fetch/configs/default/nodename 

Running version 0.10 

*** LOCAL GEMS ***

oxidized (0.10.0)
oxidized-script (0.1.1)
oxidized-web (0.6.1)

**Comment by ytti** [comment]
So it's expected/normal that the directory specifies the 'main group' name, explicit groups will be created below it. So if you want 

configs/groupX
configs/groupY

Specify the directory as

configs/groupless

But I see that the API may not understand this for file output correctly currently, not sure and too late to go into it now. 
Are you planning on using 'file' output for now, or migrating to git output later? Since it might be that it works correctly on git output.

**Comment by andreas1o** [comment]
Planning on using file actually but if git in the current workaround I might set that up.

**Comment by ytti** [comment]
If you can test with git, to see if it exhibits same or if this is just file issue it would help to triage.

**Comment by andreas1o** [comment]
With git it works. So I will close this thread for now.

**Comment by ytti** [comment]
I'll keep this open, this is clearly a bug.

**Comment by ytti** [comment]
Thank you for the triage, it does help.

**Comment by ytti** [comment]
I think this was fixed in some other PR. If not, reopen.
