### ISSUE TITLE
Viewing device configurations in LibreNMS is very slow

### ISSUE THREAD

**Issue by dbesade** [ytti/oxidized#2909]
Hello,

We are using Oxidized/Librenms for Configuration Backups. We currently use a git repo to store these files, primarily for the versioning capability it brings. We backup approximately 2200 devices every hour. It is extremely slow to load the backup configurations via the LibreNMS UI... its slow to query Oxidized even in the node list. Some research on similar issues... we have done the 'gc --auto' fix, adjusted threads, etc. None have made a dent in the issue. Any suggestions?

**###Version Information###**
some-user@servername:/home/oxidized/.config/oxidized# gem list --local | grep oxidized
oxidized (0.29.1, 0.26.3)
oxidized-script (0.6.0)
oxidized-web (0.13.1)

[config.txt](https://github.com/ytti/oxidized/files/12352713/config.txt)

**Comment by michieltimmers** [comment]
We have the same issue. But are you sure this is related to LibreNMS? Because when I use the oxidized web gui and select the versions icon it also takes a long time to load, as long as when I use LibreNMS . I believe this is because LibreNMS is using this version to get the current config but also show the different version. I just upgrade our Oxidized node (hardware) and now its a bit faster. Not sure what else I can do other then just starting with a clean git repository.

**Comment by JohnyGemityg** [comment]
Hi. Same problem here. I guess the issue is the git size. I had 2GB.
`git repack -a -d -f --depth=250 --window=250`
And now I have 155MB and performace is much better.
