### ISSUE TITLE
(FortiOS) CRLF line endings break ruby multi-line regex

### ISSUE THREAD

**Issue by hatclub** [ytti/oxidized#3019]
(Running oxidized in docker, have today pulled the latest version.)

I *think* the command output from the fortigate (OS series 7.4) we are backing up is being sent with CRLF line endings (\r\n), certainly the config that has been checked into git has them.

Best I can tell, for some reason, regex in Ruby (I know nothing about Ruby) declines to include \r in permitted characters for "." to match, even when multiline (/m) is specified.

This means that when you enable remove_secret for your fortios model because of the anti-feature of constantly changing encrypted secrets causing endless diffs to be filed when nothing has changed, the regex in the model for private-key fails to match the keys which are split over multiple lines.

I have resorted to cloning the current model and modifying the block

`  cmd :all do |cfg, cmdstring|`

to include at the end:

```
    # fortios output includes carriage returns and ruby apparently can't multiline match including CR
    new_cfg.delete("\r").each_line.to_a[1..-2].join
```

This now means that private-keys are suppressed as expected with remove_secret enabled.

Is there something else I should be considering instead of this?

*Should* a Ruby /m regex match \r\n line endings or is there a way to make it do so?

Related to this particular vendor and this problem... is there perhaps any way to selectively ignore sections of the config output for a device when assessing for change, but to still store them 'as exported' if something else changes? I do not like the notion of remove_secret as it dramatically reduces the utility of the backup, but it's the only option to prevent commits for a config that hasn't actually changed.

**Comment by hatclub** [comment]
On the specific subject of fortios' irritating habit of re-encrypting secrets and keys with a fresh IV each and every time the config is exported, In concert with using the (relatively new) private-encryption-key feature on fortios, I've made some progress with successfully decrypting some secrets (certainly the ones used for certificates) and am going to try and make the model decrypt these secrets and private keys as the config is ingested.

**Comment by n-rodriguez** [comment]
Hi there! Got the same EOL issue. Fixed with this patch : https://github.com/n-rodriguez/oxidized/commit/3d9c18b4fb49cfda5f73ed7b0f83e90cd6e04829

> I do not like the notion of remove_secret as it dramatically reduces the utility of the backup, but it's the only option to prevent commits for a config that hasn't actually changed.

Me neither ^^ To workaround this I wrote few patches to be able to run 2 instances of oxidized with almost the same conf :

* 1 instance of oxidized is run normally with the web interface and `remove_secret` for FortiOS. This allows a regular fetch of the conf (every 1/2h) which is committed to git repo and push remotely
* 1 instance of oxidized which is triggered by cron every midnight. this instance is called with `--home-dir` and `--config-file` options (from my patches) which allow you to specify a custom config file without `remove_secret` :)

Hope this helps!
