### ISSUE TITLE
Hostname resolving issues

### ISSUE THREAD

**Issue by SaaldjorMike** [ytti/oxidized#314]
Looks like my oxidized install have issues resolving hostnames of my devices (68 out of 176 works though). When reloading my list of devices, I see a lot of the following types for entries:
```
E, [2016-02-15T22:40:42.887754 #29503] ERROR -- : node {:name=>"switch.example.org", :model=>"ciscosmb", :group=>"member"} is not resolvable, raised Resolv::ResolvError with message 'no address for switch.example.org'
```
Using `dig switch.example.org` on the same machine as the oxidized is running on returns the A record just fine. Any suggestions on how to debug this?

**Comment by ytti** [comment]
Could this be related to #153 or #147

**Comment by tpomerhn** [comment]
Hitting this same bug. Wasn't happening too long ago (system used to run fine) but since LibreNMS is a bit flaky with 200 devices being monitored I have to reload it periodically and when it reloads I have to check that Oxidized is still running, which lately it hasn't. Here's a snippet from my Oxidized log:

`# Logfile created on 2016-03-11 10:47:27 -0500 by logger.rb/44203
I, [2016-03-11T10:47:27.478908 #16787]  INFO -- : Oxidized starting, running as pid 16787
E, [2016-03-11T10:47:27.654361 #16787] ERROR -- : node {:name=>"switch1.example.com", :model=>"ios", :group=>nil} is not resolvable, raised Resolv::ResolvError with message 'no address for switch1.example.com'
E, [2016-03-11T10:47:27.655870 #16787] ERROR -- : node {:name=>"switch2.example.com", :model=>"ios", :group=>nil} is not resolvable, raised Resolv::ResolvError with message 'no address for switch2.example.com'
E, [2016-03-11T10:47:27.657382 #16787] ERROR -- : node {:name=>"switch3.example.cisco.com", :model=>"ios", :group=>nil} is not resolvable, raised Resolv::ResolvError with message 'no address for switch3.example.com'`

However, LibreNMS and the underlying OS can resolve it just fine. The only difference is in the case of the "COM" portion of the returned record... perhaps an artifact of case sensitivity?

`nslookup switch1.example.com
Server:         10.122.1.11
Address:        10.122.1.11#53

Non-authoritative answer:
Name:   switch1.example.COM
Address: 10.122.9.251
`
Running Oxidized 0.12.2 with Ruby 2.1.2, pulling nodes using HTTP as a source from LibreNMS, which worked until recently.

**Comment by ytti** [comment]
Can you try this:
´´`
ruby -rresolv -e 'p Resolv::DNS.new.getaddress "switch1.example.com"'
ruby -rresolv -e 'p Resolv::DNS.new.getaddress "switch1.example.COM"
```
And also output of ```ruby -v```

**Comment by tpomerhn** [comment]
Thanks for the prompt response! Output as requested (and it does seem like a case sensitivity issue now):

ruby -rresolv -e 'p Resolv::DNS.new.getaddress "switch1.example.com"'
/usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/resolv.rb:384:in `getaddress': DNS result has no information for switch1.example.com (Resolv::ResolvError)
        from -e:1:in `<main>'

ruby -rresolv -e 'p Resolv::DNS.new.getaddress "switch1.example.COM"'
#<Resolv::IPv4 10.122.9.251>

ruby -v
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]

**Comment by tpomerhn** [comment]
Sorry looks like the paste didn't work well. Trying again.

`#ruby -rresolv -e 'p Resolv::DNS.new.getaddress "switch1.example.com"'
/usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/resolv.rb:384:in `getaddress': DNS result has no information for as-rtp-ic12.cisco.com (Resolv::ResolvError)
        from -e:1:in `<main>'

# ruby -rresolv -e 'p Resolv::DNS.new.getaddress "as-rtp-ic12.cisco.COM"'
#<Resolv::IPv4 10.122.9.251>

# ruby -v
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]`

**Comment by ytti** [comment]
Yeah this is same issue as in #147 it's ruby bug and it's fixed in newer releases.

**Comment by SaaldjorMike** [comment]
Have been quite busy last few weeks but finally managed to get some time to look at this. Upgrading Ruby fixed my issue.
