### ISSUE TITLE
Rugged::NetworkError: unsupported URL protocol

### ISSUE THREAD

**Issue by gp1009658** [ytti/oxidized#3211]
rugged:1.7.2
oxidized:0.30.1

**Comment by gp1009658** [comment]
i have install oxidized,but when i hook to gitlab,don't work normal.  there is the information. "NetworkError: unsupported URL protocol"

**Comment by KarlTheFish** [comment]
This seems to be a common issue. How did you install?

Here's how I fixed it for my system:
- uninstall oxidized and rugged
- `gem install rugged -v 1.5.0.1 -- --with-ssh`
- Build from Git. Follow all steps until `rake install`
- BEFORE doing `rake install`, edit the file oxidized.gemspec in the repo: change the line `s.add_runtime_dependency 'rugged',       '~> 1.6'` to `s.add_runtime_dependency 'rugged',       '~> 1.5'`
- Continue with `rake install`

**Comment by robertcheramy** [comment]
Can you post your config file? I suspect you are using http instead of ssh to access the remote git.

**Comment by robertcheramy** [comment]
After having played with rugged the last days, I think the problem is, as stated by @KarlTheFish, that rugged needs to be installed --with-ssh. As this is a common issue, I plan to make a better warning, including the hint to install Rugged with ssh-support when `Rugged::features` does not include `:ssh`.
