### ISSUE TITLE
I would like to see an explanation of the router.db settings in the document

### ISSUE THREAD

**Issue by ts0818** [ytti/oxidized#3266]
Could you please include a description of each of the router.db settings in the documentation?
For example, in the example of five configuration items,
[1]:[2]:[3]:[4]:[5]
It will be in the form of,
[1] Host name of the target device
[2] IP address of the target device
[3] Key name of the setting item "model_map" in the oxidized configuration file
[4] Users for SSH login to the target device
[5] User's password for SSH login to the target device
I wonder if that will be the explanation.

I'm having trouble figuring out how to set the correct router.db.

**Comment by skiera6** [comment]
First of all, refer to [docs/Sources.md](https://github.com/ytti/oxidized/blob/master/docs/Sources.md). I assume you want to use a CSV (comma-separated values) format for your router.db, but you can set a different delimiter in the configuration if needed(in [this.](https://github.com/ytti/oxidized/blob/master/docs/Sources.md#source-csv) example it's set to ":" for convenience as you may want to use dots in ip addresses for example)

It might not be necessary to create separate documentation for this since you can map the fields yourself. Your configuration just needs to match the actual contents of the CSV file. For example, if you set name: 0 in the config, the corresponding value must be in the first position of the CSV, as it's zero-indexed.

Here’s a brief overview of [this.](https://github.com/ytti/oxidized/blob/master/docs/Sources.md#source-csv) example:
>[0]rtr01.local:[1]192.168.1.1:[2]ios:[3]oxidized:[4]5uP3R53cR3T:[5]T0p53cR3t

- [0] Host name of the target device
- [1] IP address of the target device
- [2] Key name of the setting item "model_map" in the Oxidized configuration file
- [3] Username for your [input](https://github.com/ytti/oxidized/blob/master/docs/Ruby-API.md#input) 
- [4] Password for your [input](https://github.com/ytti/oxidized/blob/master/docs/Ruby-API.md#input) 
- [5] This is a bit special as it's vars_map enable: This is the name of the variable in your Oxidized configuration that you want to set. This specifies that the value for enable will be taken from the sixth column (fifth index) of the router.db entry.

Make sure that your router.db aligns with this structure in your configuration.

**Comment by ts0818** [comment]
Thank you for your reply.

> https://github.com/ytti/oxidized/blob/master/docs/Sources.md

I have confirmed this, but I am not sure, so I would like to confirm it again.

The setting items of ``map'' or ``model_map'' in config are
I somehow understood that it was an item that could be set in router.db, but
Is there no particular naming rule for the key name of "map" or "model_map"?
Or does it have to be a fixed key name?
Also, is there no particular upper limit to the number of items that can be set in "map"?
For example, can you set even 10?
You may not know the total number of items that can be set in router.db.

**Comment by skiera6** [comment]
>Is there no particular naming rule for the key name of "map" or "model_map"?

You map the variables from the [source](https://github.com/ytti/oxidized/blob/master/docs/Sources.md) to the variables that are going to be used to access your device such as 
```
  name: 1
  model: 3
  ip: 2
  username: 6
  password: 8
  group: 7
```

>Is there no particular naming rule for the key name of "map" or "model_map"?

you can map an arbitrary amount of variables as ```vars_map:``` and i think ```map:``` too can map to any variable but it might not be used in the source code (the ones i listed above are used and documented, the names are basically self explanatory) so what's the point if you wont implement any functionality. 

```model_map:``` is responsible for mapping string to [supported models ](https://github.com/ytti/oxidized/blob/master/docs/Supported-OS-Types.md) for example your router.db contains model ```cisco``` but oxidized doesn't know what's that but is knows that it supports ios (the os used by cisco) so basically if your data source is a bit off from what oxidized uses you can just map the variables to models that oxidized uses so you dont need to change much in your data source
```
model_map:
  cisco: ios
  juniper: junos
  SomeNewCustomMikroTik: routeros
```

>You may not know the total number of items that can be set in router.db.

Yes but you know the position at which a certain data is stored for example at position 1 is the name of the device
you dont need all the data just bare minimum that allows you to connect to the device and get the config contents

**Comment by ts0818** [comment]
Thank you for your reply.

We understand that the naming rules for the setting item "map" are not easily defined if they are not stated in the documentation.
I understand that although the number of setting items "map" is arbitrary, the number listed in the document is the total number.
Regarding the naming rule for the setting item "model_map", I understand that the key name can be anything.

**Comment by skiera6** [comment]
>We understand that the naming rules for the setting item "map" are not easily defined if they are not stated in the documentation.
Yes.
>I understand that although the number of setting items "map" is arbitrary, the number listed in the document is the total number.
Yes.
>Regarding the naming rule for the setting item "model_map", I understand that the key name can be anything.
Yes as long as the value matches actual existing oxidized model (or a model that you created yourself)

**Comment by ts0818** [comment]
Thank you for checking and responding.
I will close the question.
