### ISSUE TITLE
the git generated by oxidized gets passively larger the more time passes

### ISSUE THREAD

**Issue by Atroskelis** [ytti/oxidized#3269]
The difference between repo before and after git gc is immense

before:
2.2G    /var/oxidized/oxidized.git

after gc
74M     /var/oxidized/oxidized.git

**Comment by skiera6** [comment]
I'm not directly associated with Oxidized, but I can help clarify based on what I understand:

The rugged library, which is a Ruby binding to the libgit2 library, does not support running git gc (garbage collection) directly. The libgit2 library focuses on interacting with Git repositories at a lower level, and it doesn’t have a built-in equivalent to Git's gc command, which packs and cleans up repository data.

Since Oxidized uses rugged/libgit2 for interacting with repositories, it won’t handle Git maintenance tasks like garbage collection automatically. To address this, you might want to schedule regular git gc operations to avoid the repo growing too large over time. You can automate this using a cron job.

If anything i wrote is wrong feel free to correct me

**Comment by Atroskelis** [comment]
Fixed via cronjob git gc
