### ISSUE TITLE
Store junos config as set statements

### ISSUE THREAD

**Issue by funzoneq** [ytti/oxidized#357]
Hi,

We want it easy for our engineers to restore junos switches. With all switch types it's just as simple as copy pasting the configuration in the terminal. With junos they have to do 'load replace relative terminal'.

I would like to have the option to store 'set statements'. So that the behaviour is similar to cisco/hp/etc devices.

I could just patch https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/junos.rb#L21 to:

```
show configuration | display omit | display set
```

But I don't want to change the default behaviour without first discussing this option.

Do we want to:
- Support this option
- Make it a configurable option
- Make it a default option?

What do you think @ytti?

**Comment by benbacardi** [comment]
Personally I'd rather this wasn't the default. `display set` is harder to read than the hierarchical version, and I'm not sure I understand your arguments against `load replace terminal relative` - when restoring config you want to paste it in, which is exactly what that command (and the hierarchical config) is designed for. Pasting set commands is far easier to screw up (over running terminal buffers, executing some of the commands but not others, etc).

A configurable option is certainly not a bad thing though - my two cents are just that I wouldn't use it.

**Comment by ytti** [comment]
I'm huge fan of 'set' commands, because they are easily greppable, unlike the native presentation. The rationale presented does not make sense to me, but of course that's just my opinion. Also you should use 'overwrite' when restoring config from backups not 'replace', 'replace' is just 'merge' with support for 'replace:' blocks.

And I know several oxidized users who use customised models to get them. Usually people want them in separate files, and we support that, but you need to tinker the model bit.

#327 PR discussed this bit, and shows how you can have set commands in their own file.

Ultimately this boils down to fact that not everyone can agree what should be collected, and I think we should be able to cater for variety, I don't know if #327 solutions are easy/userfriendly enough, if not, I'm open to suggestion how to support model customisation in more userfriendly manner.

**Comment by funzoneq** [comment]
We could make a 'custom_models' directory in the config directory. There I could include a list of custom models (that override the default models). That way it's outside of the gem directory (that changes per version).

**Comment by ytti** [comment]
There is ~/.config/oxdized/model.rb is used instead of distribution model.rb.

However, this means that if distribution model.rb changes, you won't see any of them. So it's not 'additive' to distribution, rather complete replacement.

But in #327 I propose method which may make it additive, didn't test.

**Comment by funzoneq** [comment]
I can confirm that this works:

file: ~/.config/oxidized/model/junos.rb

```
require 'oxidized/model/junos'

class JunOS
  cmd 'show conf | display set'
end
```
