### ISSUE TITLE
Keep 'Last Update' value during refresh

### ISSUE THREAD

**Issue by pblasquez** [ytti/oxidized#377]
When a node is updating the 'Last Update' value is deleted.  This can be replicated by clicking the 'update' button on the web interface - the node will immediately show 'Last Status' and 'Last Update' as 'never'.

Can we please have it where the blue color highlight text says 'Updating' and keep the 'Last Update' timestamp until the update finishes and writes a new timestamp?

**Comment by ytti** [comment]
Originally it worked like this, but this has the implication that IF rotation delay has not passed, and we ask oxidized to fetch the node, it won't fetch it, because 'last update' was too recently.

@aakso fixed this in c045382479d

I guess we could add node#force_update or equivalent instead of deleting last time.

**Comment by pblasquez** [comment]
How about saving a dedicated timestamp field for use on the UI?

**Comment by ytti** [comment]
I think it's better idea to just have new attribute for immediate refresh.
