### ISSUE TITLE
cannot load such file -- oxidized/cli (LoadError)

### ISSUE THREAD

**Issue by kefiras** [ytti/oxidized#378]
Hello,
I've just installed Oxidized locally with ruby 2.3.0 and getting below error:

/opt/LLruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- oxidized/cli (LoadError)

Unfortunately i am not speaking Ruby yet so I am looking for help with this. I suspect it may have something with my environment. 

Thanks a lot

**Comment by ytti** [comment]
Which oxidized version 'gem list'?

In 0.13.0 we probably had wrong file permissions, 0.13.1 should have fixed that.

If you are running 0.13.1 and it's still not working, can you check your 'umask'? 

sudo -s
umask

If umask is 077, gem probably is installed so that only root can use it. Then try:

sudo -s
umask 022
gem install oxidized



The error is caused beause 'oxidized/cli' is not readable to the user trying to run oxidized

**Comment by kefiras** [comment]
Thanks for replying.

I am using the latest one 0.13.1 and umask is set to 0022. since this server doesn't have access to the internet i have downloaded packages and installed with gem install --local.

**Comment by ytti** [comment]
Hmps. That is strange. You probably then have to just reset the permissions with find

Go the the directory for 0.13.1

```
find -type f | xargs chmod 644
find -type d | xargs chmod 755
```

**Comment by kefiras** [comment]
i don't think it's a permission issues- getting the same error when running as root

**Comment by ytti** [comment]
It maybe wonky ruby installation then. Do you have system ruby and the /opt ruby both installed? Are you sure you used 'gem' from the /opt distribution to install it?

**Comment by ytti** [comment]
Is this still relevant?

**Comment by kefiras** [comment]
No, not really. Thanks a lot for help
5 maj 2016 15:21 "ytti" <notifications@github.com> napisał(a):
