### ISSUE TITLE
PAN OS - Variable to disable the inventory

### ISSUE THREAD

**Issue by FTBZ** [ytti/oxidized#439]
Palo Alto backup is working fine, but it will be great to add a way to disable the inventory command (I disabled it manually right now by editing panos.rb). 

During the inventory command it will return the URL filtering version and it can change many times in a day. So we don't want to create a new configuration every time that the URL filtering is updated in the Palo Alto side.

The line is (exemple):
> url-filtering-version: 2016.05.24.429

**Comment by ytti** [comment]
Instead of disabling inventory command, wouldn't it be better to just remove that string from inventory? Ore replace the version with 'X'?

**Comment by FTBZ** [comment]
Yes, it's a good idea.

**Comment by ytti** [comment]
I don't have PANOS, so either you'll have a crack at it, or give me remote access to some box. I'm confident you'll be able to solve this yourself by looking at existing models.

For testing, you can copy your model to ~/.config/oxidized/model directory and then that model will be used, instead of distribution.

When you're happy with results, send a pull request.

**Comment by rixxxx** [comment]
I'll look into this

**Comment by ytti** [comment]
What's the status here? (and the other PANOS ticket)

**Comment by FTBZ** [comment]
@charlesklement has removed annoying lines, on May 26.

**Comment by ytti** [comment]
Cool, thanks for confirming.
