### ISSUE TITLE
Remove version lock on slop v3.4

### ISSUE THREAD

**Issue by wk** [ytti/oxidized#452]
As mentioned by @ytti in ytti/oxidized#203, oxidized currently version locks its slop dependency to v3.4 in order to prevent a conflict with 'pry'.

This dependency on a specific version of slop has been resolved in upstream pry in this [commit](https://github.com/pry/pry/commit/1fc5e7f1d5c010c1c43409b12308fcfb3bb11266). Unfortunately, no new versions of pry have been released yet since.

@ytti if you are willing to upgrade your local installation of pry to the current master, the version lock of slop can be eliminated already. Alternatively, this issue can be used to track pry until release and remove the version lock when that occurs.

This version lock is presently the only blocking factor toward packaging oxidized for Debian and Ubuntu, as there the shipped ruby-slop package is currently at v4.2.

**Comment by ytti** [comment]
slop3 and slop4 are not interchangeable, they have entirely different API. Essentially they are two different libraries. If we go to slop4 we need to change our command argument parsing. I am ready to do that.

Having said that, can Debian really take this position? That everyone has to run specific version of package to be able to be included in Debian? What about when slop5 comes? Does Debian mandate that every program ever using slop4 needs to be rewritten using slop5?

Ruby handles multiple versions of libraries seamlessly. Debian cannot due, arguably poor 90s design of package management. The canonical way Debian solves this problem is packaging each version separately. I.e. ruby-slop3, ruby-slop4.

**Comment by wk** [comment]
The correct means of repackaging components from interpreted language repositories for OS distribution (and the wisdom of doing so) is an ancient and storied art form that is as old as perl and as contested as systemd. This is especially the case in instances where components with foreign 
function interface into compiled language libraries are involved.

The authors of `gem2deb` have gone out of their way to create a low-touch tool that makes the task nearly enjoyable, which considerably reduces the overhead of doing so; but there are still policies and conventions of various distributions to adhere to and find willing sponsors for.

Contributing and maintaining a Debian package of slop v3 would be feasible but dubious undertaking as recent Debian (and Ubuntu) distributions ship exclusively with Ruby 2, where slop v4 is recommended, whereas older distributions ship exclusively with Ruby 1.9, where slop v4 is unsupported.

Since slop v4 is only officially supported on Ruby 2, this would also mean an official end to Ruby 1.9 support for oxidized.

There seem to be a number of alternatives that can be considered:
* Continue relying on slop v3 as-is, abandon Debian packaging effort
* In-line the slop v3 gem into oxidized, and consider it legacy dependency (same as pry)
* Transition to slop v4 and abandon Ruby 1.9 support

**Comment by ytti** [comment]
I have no problem going to slop v4 and abandoning ruby1.9. But this is decidedly Debian problem, and Debian solution is to package slop3 and slop4. And who ever is doing Debian packaging of slop should do this.

In the mean time, I welcome PR for slop4 as soon as new pry has been released.

**Comment by ytti** [comment]
0.11.0 pry has vendored slop, and no longer has conflict (gem install pry --pre)
