### ISSUE TITLE
OXIDIZED_HOME variable handled inconsistently

### ISSUE THREAD

**Issue by wk** [ytti/oxidized#454]
Currently, setting the `OXIDIZED_HOME` variable to anything but `/etc/oxidized` leads to an unexpected outcome:
- `OXIDIZED_HOME` is set as Root in [config.rb](https://github.com/ytti/oxidized/blob/65273f736ce059fbb3785e251f65a3f84b387ef1/lib/oxidized/config.rb#L6) where it is then honored for [crash](https://github.com/ytti/oxidized/blob/65273f736ce059fbb3785e251f65a3f84b387ef1/lib/oxidized/config.rb#L7), [log](https://github.com/ytti/oxidized/blob/65273f736ce059fbb3785e251f65a3f84b387ef1/lib/oxidized/config.rb#L8) and [pid](https://github.com/ytti/oxidized/blob/65273f736ce059fbb3785e251f65a3f84b387ef1/lib/oxidized/config.rb#L33) files.
- It is _not_ passed to [asetus](https://github.com/ytti/oxidized/blob/65273f736ce059fbb3785e251f65a3f84b387ef1/lib/oxidized/config.rb#L17) for configuration loading, resulting in asetus using the built-in [defaults](https://github.com/ytti/asetus/blob/beb424eeade657b2d20ad3cbd1c8784efe024dd0/lib/asetus.rb#L103) to attempt to load the configuration from `/etc/oxidized` and the user's home directory.

The correct behaviour is probably to pass OXIDIZED_HOME as `usrdir` to asetus while instantiating it for configuration parsing.

**Comment by ytti** [comment]
Thanks for looking into this. I'm not sure which makes more sense ```sysdir``` or ```usrdir``` but I'm happy to accept PR for this. I'll accept either, unless someone can come up with solid argument which makes more sense.

**Comment by danilopopeye** [comment]
I think it makes sense to force `OXIDIZED_HOME` as `sysdir`, otherwise it'll impossible to override it with `usrdir`.

But also, using `usrdir` will avoid having some weird debug cases when a config from `usrdir` keeps overriding your config from `OXIDIZED_HOME`.
We had some problems with this in the beginning and wasn't too easy to find, since `Asetus` won't tell you what configs it loaded.

I'm happy with any solution, just have to be clear in the docs. :smile:

**Comment by ytti** [comment]
```Asetus``` loads both configs and merges them, usrdir taking precedence.

**Comment by danilopopeye** [comment]
> Asetus loads both configs and merges them, `usrdir` taking precedence.

Exactly, but this is not mentioned anywhere in oxidized docs, and this was the issue I was commenting. But this its besides this issue point, sorry!

---

Anyway, @wk can choose one as @ytti has said :wink:

**Comment by ytti** [comment]
Yeah our docs blow dead goats, sorry about that. Anyhow reason it is like this, if you have multiuser system, you might want to have oxidized proper config in /etc/ and then authentication config in ~/.oxidized, so that users can use oxs/oxidized-script with their individual authentication, without needing to know about other config, particularly node source/mapping etc.

**Comment by danilopopeye** [comment]
> Anyhow reason it is like this, if you have multiuser system, you might want to have oxidized proper config in /etc/ and then authentication config in ~/.oxidized, so that users can use oxs/oxidized-script with their individual authentication, without needing to know about other config, particularly node source/mapping etc.

so, if I understood correctly, the using `sysdir` makes more sense then. as I see it `OXIDIZED_HOME` will mostly be by `systemctl` and friends, right?

**Comment by davama** [comment]
I think there’s a pr for this…
https://github.com/ytti/oxidized/pull/2479

**Comment by mjbnz** [comment]
> I think there’s a pr for this… #2479

Indeed... never searched for issues, sorry, just found the annoyance when I was trying to test some mods I've been working on

> Yeah I think `sysdir` is better option, unless someone gives solid arguments for `usrdir`

`usrdir` takes precedence over `sysdir`, so `usrdir` is the better option so that setting the environment variable is able to be used to use a different config file than `~/.config/oxidized/config` for testing

**Comment by mortzu** [comment]
@mjbnz can I close the issue?

**Comment by mjbnz** [comment]
> @mjbnz can I close the issue?

I think so... if you agree that my PR was the appropriate solution.

**Comment by mjbnz** [comment]
> But also, using `usrdir` will avoid having some weird debug cases when a config from `usrdir` keeps overriding your config from `OXIDIZED_HOME`. We had some problems with this in the beginning and wasn't too easy to find, since `Asetus` won't tell you what configs it loaded.

Hah! see #2485 for an exact case of this happening. I also detailed the current config loading order in that issue.
