### ISSUE TITLE
Don't need to backup the uptime of Ironware and Cisco IOS equipments

### ISSUE THREAD

**Issue by davromaniak** [ytti/oxidized#577]
Hello.

On IronWare/Cisco IOS based equipments, all the configuration is backed up, but it contains the current uptime.

So every 6 hours (in my case), I get this kind of diff.
```
-! STACKID 1  system uptime is 466 days 5 hours 45 minutes 19 seconds 
+! STACKID 1  system uptime is 466 days 11 hours 46 minutes 15 seconds 
```
or
```
-! switchname uptime is 47 weeks, 5 days, 9 hours, 51 minutes
+! switchname uptime is 47 weeks, 5 days, 15 hours, 52 minutes
```
I don't think it's useful to backup this information.

If needed, I can work on a patch.

Thanks.

**Comment by davromaniak** [comment]
I just checked ironware.rb, and it seems the following code doesn't do anything : 

```
  cmd 'show version' do |cfg|
    cfg.gsub! /(^((.*)[Ss]ystem uptime(.*))$)/,  #remove unwanted line system uptime
    cfg.gsub! /(^((.*)[Tt]he system started at(.*))$)/, ''
    cfg.gsub! /[Uu]p\s?[Tt]ime is .*/,''

    comment cfg
  end
```
As the regex seems to be correct, but the system uptime line is still here.

For the IOS module, there isn't any gsub to remove the uptime, I will try to make it work and make a patch.

Thanks.

**Comment by ytti** [comment]
The IOS model only takes first line of 'show version', which does not contain uptime. But you're welcome to store all of it and remove changing data.

I can't explain the IronWare issue, but I'm happy to take a look, if remove access can be arranged.

**Comment by davromaniak** [comment]
I won't be able to give you remote access to this device.

But I can send you a complete "show version" in a private message.

Thanks.

**Comment by ytti** [comment]
I'm just confused because you see this problem in ios, which shouldn't even be storing this data to begin with. And you see this in ironware, which should be filtering.
So I suspect something else may be in play than model error, perhaps mistakenly wrong models are being used.
I have high confidence that the regexp would work if I give it to ruby.

You can test easily yourself
```
ssh box|tee box.log
show version
exit
irb
cfg = File.read "box.log"
cfg.gsub! /(^((.*)[Ss]ystem uptime(.*))$)/, '' #remove unwanted line system uptime
File.write "box-mangled.log", cfg
```

And review box-mangled.log.

**Comment by davromaniak** [comment]
Hi.

I just tested the script using telnet (because SSH isn't enabled on these Brocade switches) and it works, the system uptime is stripped from the "show version".

I'm double checking my configuration to see where I made a PEBKAC.

Thanks.

**Comment by davromaniak** [comment]
Hello.

It seems I found the issue.

I removed "prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/" from the configuration file and it works.

Here is the prompt I get on the Brocade switches : "telnet@sw8-oob.domain.tld#"

I'm testing to see if removing the prompt variable hasn't broke anything.

Thanks.

**Comment by ytti** [comment]
We don't use the configuration prompt, if model (or device) has prompt configured. Order of resolution is:

device_prompt => model_prompt => configuration_prompt

We'll stop when it is defined. If this is not true, then there is a bug. Code is here: https://github.com/ytti/oxidized/blob/master/lib/oxidized/node.rb#L127

**Comment by davromaniak** [comment]
Well, I think I have an issue on those switches.

When the system uptime is displayed, the config file begins with 
```
! Invalid input -> length 0
! Type ? for a list
```

But when the system uptime isn't displayed, there isn't these two lines.

I will try to see what these two lines are about.

Thanks.

**Comment by ytti** [comment]
Do you per-chance use enable? Quite common bug we have (I should have paid more attention on model submissions) is that we don't consume/read prompt always. 

If we don't consume prompt, then the next command we write races, it might read the previous prompt and have completely wrong idea where the command starts and ends.

We /must/ always eat every prompt (except if ssh and exec is set true), otherwise we get desynchronisation and program runs wonkily depending on timing.

I see that ironware actually has this bug:
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/ironware.rb#L77

```send``` does not expect for prompt, but that line actually produces prompt, so prompt is left unconsumed and we lose track of state.
This line should be replaced by ```cmd vars(:enable)```which will cause it to consume the prompt, and probably will address your problem.

**Comment by davromaniak** [comment]
Hello.

Wiith "cmd vars(:enable)" instead of "cmd vars(:enable) + "\r\n"", I don't have any other issues.

Even the temperatures are stripped, which wasn't the case earlier.

Thanks.
