### ISSUE TITLE
Scalability Issues

### ISSUE THREAD

**Issue by shailigum** [ytti/oxidized#597]
Has anyone had issues with scalability?

I've got an instance with approximately 1600 nodes set to pull at 6 hour intervals. The longer it runs the more disparity I start to see in config pull times, and sometimes it doesn't even pull all configs before starting over at the top again (leaving a certain number of nodes ignored).

I'm assuming the latter has to do with the number of nodes/failures and it being unable to complete the entire router.db table within the allotted time, though as I increase this to 12 hours I am still getting similar results.  Shouldn't the threading account for this, and increase to a count high enough to sustain that number of nodes within that time frame?  With a maximum of 32 threads I should be able to pull well over 1600 nodes in 12 hours...however I rarely see it exceed 2 simultaneous threads, and even then it appears to be painfully slow.

Anyone have similar experiences?  Thoughts?

**Comment by ytti** [comment]
This shouldn't happen, the more threads it needs the more threads it launches, pulling 1600 nodes every 30min shouldn't really be a problem at all.

It maintains rolling average of time it takes to fetch node, multiplies that by amount of nodes you have, divides that by your interval to determine how many threads are needed.

There is no such thing as 'starting back from top', there is no top, it's circular buffer, which it traverses box at a time. There isn't any magic beginning, end or middle, so it decided cannot in middle jump to a beginning. 

You can change the circular buffer by reloading the nodes or by moving node ahead of queue. If you do that, we don't really guarantee where it starts after reload.

So you should have your interval much shorter than your reload, so that you'll guarantee they'll will be some rotation(s) before reload kicks in.

**Comment by shailigum** [comment]
Okay, thanks for clarifying.

I get the concept of the circular buffer, however what confuses me is that in this instance, if I have my interval set to 6 hours and leave it running for a week straight, I will come back and see that there are several nodes that remain 'blue' under their status indicator, and many others that show their 'last checked' date being days behind.

What would be the reason for this?

**Comment by ytti** [comment]
Are the nodes reachable? Anything in logs? Are you periodically running /reload?

**Comment by shailigum** [comment]
Not running reload periodically, not touching the instance at all in this example.

Not all nodes are reachable, about 5% fail when unreachable via ssh or telnet.  Nothing of note in the logs other than some nodes failing/timing out.  Most unusual thing I see is extended periods of 'lib/oxidized/worker.rb: X jobs running in parallel' where X is never higher than 2.

Config has the max threadcount set to 30, timeout set to 20, and retries at 1.

**Comment by ytti** [comment]
I think it is meeting the interval requirement, I don't think that is the problem, I think it's going through whole lot.

Is there some indication it is not?  Maybe run with debugging enabled and see if it is trying each? Are there any crash logs? Which oxidized version?

**Comment by shailigum** [comment]
Indication being the status light staying blue and the 'last checked' time being days behind when I set the interval to 6 hours.  I also check the filesystem and don't see the folders having been written to within the interval set, despite there being config changes.

I have logging and debugging enable and I don't see attempts on the outstanding nodes.  No crashes.  Version 17.0, however i've seen this on previous versions as well.

**Comment by ytti** [comment]
So you don't have line like:       

 ```"lib/oxidized/job.rb: Starting fetching process for #{@node.name} at  #{Time.now.utc}"````

If you grep for that, and sort|iuniq -c|sort -n based on the node.name, you see large difference? For nodes which have far smaller number, have they all stopped at same time? No reload or next used around that time?
