### ISSUE TITLE
Feature Request: description field

### ISSUE THREAD

**Issue by bradvido** [ytti/oxidized#672]
Since the "name" field is used as a unique identifier for the devices, it would be nice to have another field to describe the device, which could change without altering the device identity.

**Comment by ytti** [comment]
Where would you display it and for what purpose? Use case might help.

You can already pass arbitrary variables from sources to the node via ```vars_map```

**Comment by bradvido** [comment]
Ideally, it would be displayed in oxidized-web.  I submitted the issue here because I'm assuming the data structures live here and the web interface is just presentation.

**Comment by ytti** [comment]
I'm not against this, and I can do the oxidized part, it's extremely easy. However, it would be cool, if we we'd rather figure out acceptable way to display vars in oxidized-web, this way your use-case and any other arbitrary future variable would be supported.

However, I'm not sure if this is such an easy task, because you probably don't want some vars blob in the oxidized-web, which you need to click open to see what vars there are.
Or should all vars be columns in the table?

**Comment by bradvido** [comment]
All vars in the columns table, and hidden by default seems reasonable to me.

**Comment by ytti** [comment]
W000, then my work is done! :>

Someone just needs to expose that in oxidized-web, all the vars are available via ```#Node.vars``` as a hash.

**Comment by bradvido** [comment]
Can you give a hint as to where to start? I'll take a stab

**Comment by ytti** [comment]
For example the nodes list is here: https://github.com/ytti/oxidized-web/blob/master/lib/oxidized/web/webapp.rb#L34-L46

The view is here: https://github.com/ytti/oxidized-web/blob/master/lib/oxidized/web/views/nodes.haml

In the view ```@data``` contains list of nodes. You could iterate it with something like this:
```
@data.each do |node|
  # node is individual node
  node.vars.each do |name, value|
    # name is name of the variable
    # value is the value of the variable
  end
end
```

**Comment by laf** [comment]
@bradvido Did you manage to look at this?
