### ISSUE TITLE
Local files versioning

### ISSUE THREAD

**Issue by CJloHuK** [ytti/oxidized#789]
Hello,

Maybe I overlooked, but I'm not able to see how to make versioning/diff while using local file output.
It would just overwrite the current file.

Kindly advise if that is possible or versioning/diff only supported with git?

Thanks in advance

**Comment by ytti** [comment]
There is today no versioning for flle output. And reinventing git seems hard to justify. Can you try to explain what you'd want and why, instead of git?

**Comment by CJloHuK** [comment]
I was thinking about same way rancid did/does - for each poll it will save new file and will email/show in web the diff to the first/initial file output.

**Comment by ytti** [comment]
That is not what rancid does, rancid uses CVS by default, which is yet another versioning system, like git.
I.e. by changing file output to git you'll get similar behaviour to rancid. 

There is hook in example directory for email diffs, personally I'd push the git repo to gitlab, github, stash, gitea or something like that, and have that system generate diffs. Mainly because I believe vast majority of companies already run their git server for other purposes, so it makes sense to capitalise on existing infra.

**Comment by CJloHuK** [comment]
Sure, I'll use git for that.
