### ISSUE TITLE
Device not present - Dell powerconnect

### ISSUE THREAD

**Issue by packtman** [ytti/oxidized#804]
I am getting a weird issue. All my device configurations are visible in oxidized except for one. We have dell powerconnect (Dell Networking Switch) switches in our environment. 

When I run oxidized the configuration gets updated for this one particular device. Under logs after enabling  
input: 
    debug: true
I can see the device-info (devicename-telnet) with show system, show version and show running-config. But, the same device info just shows,  show system and show version. It completely skips the actual configuration (show running-config).

PFA image.
![devicenotpresent](https://cloud.githubusercontent.com/assets/7194155/24871124/9f8c3cc8-1de6-11e7-8934-893f10bad979.PNG)

Please let me know if you need more information.

Thanks.

**Comment by ytti** [comment]
If in your logs it doesn't logout, it implies it perhaps didn't detect the prompt. No crashfiles, nothing in logs? Nothing when running in debug?
For simplicity you might want to run with just that node.

**Comment by rverchere** [comment]
Hi @packtman , which Dell switch model do you use? There are many OS versions (powerconnect, force10, dnos6, dnos9, etc.).

You can try with `dnos` model + `enable` parameter.

**Comment by okand** [comment]
I just stumbled over this exact issue. I have two Dell PowerConnect M6348 blades that Oxidized doesn't pull the full config off.

I'm using the `powerconnect` model and by looking at the other Dell/Force10 models in Oxidized I'm pretty sure this is the one I should be using. There is no `show inventory` command like the DNOS/FTOS devices have for example.

This is everything Oxidized gets before declaring its done and committing to the repo:
```
! 
! System Description................ Dell Ethernet Switch
! System Contact....................
! System Name....................... pcm01
! System Location...................
! Burned In MAC Address............. D067.E592.1FBE
! System Object ID.................. 1.3.6.1.4.1.674.10895.3025
! System Model ID................... PCM6348
! Machine Type...................... PowerConnect M6348
! 
! unit image1      image2      current-active next-active
! ---- ----------- ----------- -------------- --------------
! 1    5.1.11.1    4.2.0.4     image1         image1
! 
! System Description: Dell Ethernet Switch
! USB Port Power Status:
! ----------------------
! Device Not Present
            ^
% Invalid input detected at '^' marker.
```
It's like Oxidized starts typing the next command a bit early maybe? It's only got `show running-config` left and then it should be done.

**Comment by okand** [comment]
The issue was that Oxidized didn't run `enable` first.

I don't know ruby but I get a feeling something might be wrong in the block between lines 43 and 56 in https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/powerconnect.rb
I feel like there's a `do` missing or one `end` too much there or something.

Adding a field to router.db with an enable password didn't make oxidized start trying to type enable for me so I brute forced it instead by deleting lines 44 to 49 and adding `post_login "enable"` on line 50. Then I changed the model/class name on line 1 and saved the file in a folder called `model` next to my oxidized config and updated router.db to use my new modified model instead.

This makes it always run `enable` first which depending on your configuration might not work but it works for me at least.
