### ISSUE TITLE
Skip username on SSH?

### ISSUE THREAD

**Issue by kunwon1** [ytti/oxidized#899]
Some sonicwall devices use a default ssh username, and skip right to the password prompt. I can't figure out how to handle this in a model, I'm betting it's an obvious solution I'm missing, any tips?

**Comment by ytti** [comment]
What is 'default ssh username'? I believe SSH (RFC4252) will always send some username string. Now sonicwall may not care what it is, if so, then just configure any username string, if it does care, configure what it expects.

**Comment by laf** [comment]
@kunwon1 Any update on this?

**Comment by infinite-ideation** [comment]
Reviewed this with a SW NSA2500 and a TZ200, the sonicwall default SSH username is whatever the default admin username is.

In a factory default configuration, the default username for admin is 'admin' followed by the password. 

The NSA series has three inputs:

Prompt 1:  Login as: (this seems to be arbitrary, doesn't matter, enter 'admin' to be safe)
Prompt 2:  User: (this is where you would enter your default admin username, 'admin')
Prompt 3:  Password: (your 'password')

The TX series has two prompts

Prompt 1: User: 'admin'
Prompt 2: Password: 'password'

attaching an image for reference.
![nsa2500](https://user-images.githubusercontent.com/29865604/27912575-718e18f8-622b-11e7-92f6-298ff16acbec.JPG)

**Comment by ytti** [comment]
And all of these are SSH examples? The TX would work with normal model which defines userrname and password regexp. 

I don't think the NSA model would work right now, except with some dirty hack which makes User: a prompt, so it'll succeed login after 'login as' prompt. Then use ```post_login``` to handle the set second login, then reset prompt to something more sensible. 
We probably should have less hacky way to handle it, it's not entirely obvious to me yet how to do it, maybe callback, so that model can write its own login handler, not using telnet/ssh built-in at all, allowing arbitrary complex login. 

What would be the preferred solution?

**Comment by infinite-ideation** [comment]
I actually just read the Sonicwall documentation and it's advised to insert 'root' as the user handle if prompted for "login as". The image above is an NSA sonicwall, not the *TZ series, sorry not TX. 

Here's a screenshot for a TZ
![tzcapture](https://user-images.githubusercontent.com/29865604/27913172-3f322ee2-622d-11e7-9624-86b56d1bbe6e.JPG)

If I had to propose a solution, I'd recommend (for the NSA)
1. insert random username for login as: e.g. 'root'
2. use the post_handle to set second login to 'admin'
3. send 'password'

I'm not sure what model @kunwon1 is working with because I can't replicate his specific scenario with any of the devices we have (TZ200/205/300,NSA2500/2600) running current firmware.

**Comment by ytti** [comment]
Maybe if we implement ```pre_login```. And have something like

```
cfg :ssh, :telnet do
  pre_login do
    expect /login as:/
    send "root\n"
  end
end
```

Then it would continue to login.

**Comment by ytti** [comment]
That won't work, because we don't have ```pre_login```, I'd need to implement one first.

**Comment by ytti** [comment]
This may or may not work:
https://github.com/ytti/oxidized/commit/72a6619986086df4d8db876ca0424f6bb6671b1b

**Comment by darylturner** [comment]
Where is the pre_login block supposed to be defined? I've created a SonicOS model and built oxidized with the pre_login branch but I'm not seeing any pre_login blocks executed in the debug output.

```ruby
class SonicOS < Oxidized::Model
    prompt /^.*@\w*> $/

    cmd 'show current-config'

    cfg :ssh do
        password /^[Pp]assword:$/
        pre_login do
            match = expect password, prompt
            if match == password
                cmd @node.auth[:password]
            end
        end
        post_login 'no cli pager session'
        pre_logout 'exit'
    end
end
```

**Comment by laf** [comment]
@darylturner Are you using the patch that ytti linked to?

**Comment by darylturner** [comment]
Yes, should be. Did a fresh clone, checkout of 72a6619 and gem build/install.

```
> grep -C5 pre_login /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/input/ssh.rb              

    def login
      unless @exec
        shell_open @ssh
        begin
          pre_login
          shell_login
        rescue Timeout::Error
          raise PromptUndetect, [ @output, 'not matching configured prompt', @node.prompt ].join(' ')
        end
      end
```

**Comment by darylturner** [comment]
Yes, can see pre_login def in cli.rb.

**Comment by darylturner** [comment]
There are two pre_login defs in cli.rb. I've renamed the one called by the get method pre_login_run not sure on the convention. My block now gets called but isn't fixing my wonky login. Slightly closer though.

**Comment by toyowheelin** [comment]
@darylturner where did you end up on this? I am attempting to get my TZ 205 working with oxidized and have a model file that I feel should be working however for whatever reason it seems to be getting the password incorrect.
