### ISSUE TITLE
Not matching configured prompt

### ISSUE THREAD

**Issue by filenox** [ytti/oxidized#92]
When running Oxidized I'm getting this in my logs:

>I, [2015-03-16T15:59:21.131421 #10744]  INFO -- : Oxidized starting, running as pid 10744
>I, [2015-03-16T15:59:21.205009 #10744]  INFO -- : Loaded 1 nodes
>D, [2015-03-16T15:59:21.731407 #10744] DEBUG -- : Jobs 0, Want: 1
>W, [2015-03-16T15:59:42.584389 #10744]  WARN -- : ******IP****** raised Oxidized::PromptUndetect with msg "
>Welcome to the Alcatel-Lucent OmniSwitch 6000
>Software Version 6.4.4.707.R01 Service Release, September 17, 2014.
>
>Copyright(c), 1994-2011 Alcatel-Lucent. All Rights reserved.
>
>OmniSwitch(TM) is a trademark of Alcatel-Lucent registered
>in the United States Patent and Trademark Office.
>
>******WELCOME_MESSAGE******
>********************************************************************************FE-001->  not matching >configured prompt (?-mix:^([\w.@-]+[#>]\s?)$)"
>D, [2015-03-16T15:59:42.589125 #10744] DEBUG -- : 192.168.253.101 raised >Errno::ECONNREFUSED with msg "Connection refused - connect(2)"
>W, [2015-03-16T15:59:42.735280 #10744]  WARN -- : ******DNS****** status no_connection, retry >attempt 1
>D, [2015-03-16T15:59:42.735462 #10744] DEBUG -- : Jobs 0, Want: 1

Can someone help me out?

**Comment by ytti** [comment]
What is your prompt? It complains that it is not finding it.

Is your prompt:
'*****************************************************************************FE-001-> '

Perhaps welcome message missing newline?

**Comment by filenox** [comment]
This might sound really stupid but what should my "prompt" be? What is my "prompt"? 
The documentation about that parameter-setting is a little bit 'basic' (for me at least)

**Comment by ytti** [comment]
When it logs in, it waits for prompt to appear, i.e. that set of strings where you know that you can start punching in commands to the box.

It is complaining, that it cannot find that.

When you login to the box, how do you know when you can start entering commands? What will it print on the screen? Is it 'FE-001->'

Since right now it seems like it it is seeing ''*****************************************************************************FE-001-> ' which does not match to https://github.com/ytti/oxidized/blob/master/lib/oxidized/config.rb#L27

There are to options on how to fix this
 1. we change the prompt in configuration file or model (aos.rb, aos7.rb depending on your OS) to allow for '*****************************************************************************FE-001-> ' as an prompt
2. we change the welcome message so that it sends new line, so that we'll see 'FE-001->' should should match.

**Comment by filenox** [comment]
Problem solved, thank you! The script now keeps running forever though,
>D, [2015-03-17T16:29:03.780462 #30049] DEBUG -- : SSH: exit @ fe-018.netwerk.vrt.be
>D, [2015-03-17T16:29:04.759535 #30049] DEBUG -- : Jobs 0, Want: 1
>D, [2015-03-17T16:29:05.760003 #30049] DEBUG -- : Jobs 0, Want: 1

**Comment by ytti** [comment]
This is normal. It once per second re-enters loop, it never wants less than 1 work to do. But upon starting that work, it sees that all boxes that need to have config fetched, have been fetched earlier than rotation delay.
