### ISSUE TITLE
How to enable git + file

### ISSUE THREAD

**Issue by reavenm** [ytti/oxidized#967]
I read somewhere that you can enable git and file since i would like to have versioning plus have the config stored in a folder. I tried multiple combinations but nothing, most of the time just the git end up working but wont store the config in the directory assign.

**Comment by davama** [comment]
https://github.com/ytti/oxidized/issues/425

**Comment by reavenm** [comment]
Sorry but  you lost me there. Already read that and now I am confused, is this feature been merge, pending or there is a work around like this one you posted [here](https://github.com/ytti/oxidized/issues/396#issuecomment-213124356)

Thanks for the quick reply

**Comment by davama** [comment]
Well looks like it was never merged https://github.com/ytti/oxidized/issues/425#issuecomment-243183487

If it is merged one day, I personally would probably still continue with the work around since the way oxidized stores the files can be cumbersome when you have thousands of devices. Hence why i asked about https://github.com/ytti/oxidized/issues/425#issuecomment-221583484 but that's an adjustment and i dont know jack squat about Ruby to begin attempting this.

I would close this and follow/update that issue

**Comment by reavenm** [comment]
hahaha, about Ruby we both, either way I am trying to use your workaround but just getting file output git is not working 
```
vars: {}
groups: {}
models: {}
pid: "/home/administrator/.config/oxidized/pid"
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: file
  file:
    directory: "/home/administrator/repo/"
  hooks:
    first_hook:
    type: exec
    events: [node_success]
    cmd: 'cd /home/administrator/repo/$OX_NODE_GROUP && git add --all . && git config user.name "administrator" && git config user.email "administrator@ubuntu.com" && git commit --quiet -m "$OX_NODE_GROUP"'
```

another weird thing it doesn't respect my directory path it create the group inside <administrator> but not inside repo

**Comment by reavenm** [comment]
followup on #396
