### ISSUE TITLE
Intermittent CLI data corruption (powerconnect.rb)

### ISSUE THREAD

**Issue by candlerb** [ytti/oxidized#983]
Occasionally I see a pair of commits where clearly the CLI communication was mangled for one operation, and then was reverted for the next one. 

The first three examples are Dell PowerEdge 5524

Example 1:

~~~
@@ -10,7 +10,9 @@
 ! 
 ! 
 ! 
-
+! 
+! 1   00,
+! 00:00:-8666022
 
vlan database
 vlan 2,4,7
 exit
~~~

then on the next commit it's reversed:

~~~
@@ -10,9 +10,7 @@
 ! 
 ! 
 ! 
-! 
-! 1   00,
-! 00:00:-8666022
+
 
vlan database
 vlan 2,4,7
 exit
~~~

Example 2:

~~~
@@ -11,7 +11,6 @@
 ! 
 ! 
 
-ing-config
 
vlan database
 vlan 5,10,112,999
 exit
~~~

Example 3:

~~~
@@ -2,6 +2,7 @@
 !        Unit             SW version         Boot version         HW version      
 ! ------------------- ------------------- ------------------- ------------------- 
 !          1               4.0.1.11            1.0.0.12            00.00.02       
+! 29-Oct-2007 17:45:01 %AAA-I-DISCONNECT: User CLI session for user admin over telnet , source 192.168.7.71 destination  192.168.0.9  TERMINATED. The Telnet/SSH session may still be connected.
 ! 
 ! Unit          Type
 ! ---- ----------------------
~~~

Example 4: this is a Dell N1548

~~~
@@ -18,100 +18,5 @@
 ! USB Port Power Status:
 ! ----------------------
 ! Device Not Present
-
-!Current Configuration:
-!System Description "Dell Networking N1548, 6.2.6.6, Linux 3.6.5"
-!System Software Version 6.2.6.6
... snip
-exit
+                                    ^
+% Invalid input detected at '^' marker.
~~~

My guess is there's some sort of race going on.  I didn't see these errors with rancid.

**Comment by candlerb** [comment]
And another one which just happened:

~~~
@@ -11,6 +11,7 @@
 ! 
 ! 
 
+show running-config
 
vlan database
 vlan 5,7,112,255,901,999
 exit
~~~

**Comment by ccummings-coeur** [comment]
Hi @candlerb I have seen the same thing, mainly with Cisco SMB switches. Were you ever able to reach a resolution?

Thanks!

**Comment by candlerb** [comment]
Unfortunately not, still getting these intermittently.

**Comment by ccummings-coeur** [comment]
Thanks for the info. Luckily at our site these devices aren't very critical, so I am going to try and figure out a way to disable alerts for the specific devices that are the most troublesome.

**Comment by ytti** [comment]
Which version you are rocking? This issue is almost invariably caused by prompt desync, somewhere prompt is output, but model is not waiting for it.

https://github.com/ytti/oxidized/commit/689d4dba60de7a1faf555011f9db6fb3aef2fbea

When we do send "password" we blindly send it, not expect anything to happen, so unread prompt may be left behind.
Now next some 'cmd' runs, it may immediately consume the prompt it sees output from the password entry, considering the 'cmd' has finished.

Same problem exist quite widely.

**Comment by ccummings-coeur** [comment]
We are currently rocking oxidized-0.21.0, oxidized-script-0.5.0, and oxidized-web-0.9.3. Thanks @ytti !

**Comment by ytti** [comment]
Unfortunately I don't see this problem in ciscosmb, unsure what's going on there. But definitely if OP is running older oxidized that fix may fix his problem on powerconnect

**Comment by candlerb** [comment]
gem list shows:

~~~
oxidized (0.20.0)
oxidized-script (0.4.0)
oxidized-web (0.9.2)
~~~

I've just redone `gem install oxidized oxidized-script oxidized-web` and this has upgraded me to 0.21.0, 0.5.0, 0.9.3.

However, both 0.20.0 and 0.21.0 already have the patch you pointed at.  I can try to point out some more examples of failures.

**Comment by candlerb** [comment]
Here are the recent ones from my mail records:

10th Mar

~~~
@@ -10,6 +10,7 @@
 ! 
 ! 
 ! 
+! 23-May-2008 02:25:49 %AAA-I-DISCONNECT: User CLI session for user admin over telnet , source 192.168.7.71 destination  192.168.0.11  TERMINATED. The Telnet/SSH session may still be connected.
 
 
vlan database
 vlan 5,7,112,255,901,999
~~~

7th Mar

~~~
@@ -18,111 +18,5 @@
 ! USB Port Power Status:
 ! ----------------------
 ! Device Not Present
-
-!Current Configuration:
-!System Description "Dell Networking N1548, 6.2.6.6, Linux 3.6.5"
-!System Software Version 6.2.6.6
...
-exit
+                                    ^
+% Invalid input detected at '^' marker.
~~~

16th Feb:

~~~
@@ -10,7 +10,8 @@
 ! 
 ! 
 ! 
-
+! 
+! 1     80,07:50:40
 
vlan database
 vlan 2,4,7
 exit
~~~

These were all reverted an hour later when the next poll took place.

So it's not so often as to be really annoying; but this is a pretty small installation of oxidized (20 devices).

**Comment by ytti** [comment]
Would need more time to troubleshoot that I'm willing to commit at this time, start from what input sees, what it hands over to model, what model cmd returns.

**Comment by ccummings-coeur** [comment]
In the interest of not hijacking @candlerb 's post I will submit a seperate issue for the devices that I am seeing this on since we are talking about different device templates. It isn't a huge annoyance for us right now, so I will probably look into just disabling alerting for those devices that are the most troublesome. 

Thanks for all the hard work on this project @ytti I am really loving this project.

Thanks,
Chris

**Comment by candlerb** [comment]
The `%AAA` messages suggests that maybe console messages are getting mixed into the output.  I can replicate this by telnetting into the switch, and then telnetting into it a second time from another screen, and then logging out again.

On the first screen I see:

~~~
wrn-sw2...# 25-May-2008 08:37:56 %AAA-I-CONNECT: User CLI session for user admin over telnet , source 192.168.7.59 destination  192.168.2.254 ACCEPTED
25-May-2008 08:38:31 %AAA-I-DISCONNECT: User CLI session for user admin over telnet , source 192.168.7.59 destination  192.168.2.254  TERMINATED. The Telnet/SSH session may still be connected.
~~~

If I go into configure mode, and set `no logging console`, this no longer happens.  This may be the source of the problem.

Of course it'll probably stop the device logging to serial port as well.  There's no equivalent to `term no mon` that I can see.  But it still logs to buffer, and to syslog.

Will have to leave it for a few weeks to see if this is the solution, but I'm happy to close it for now.

**Comment by candlerb** [comment]
Is it possible that there's still a race here?

~~~
        send "enable\n"
        cmd vars(:enable)
~~~

Should it be:

~~~
        cmd "enable"
        cmd vars(:enable)
~~~

(`ipos.rb` does this) - or at least put a sleep after sending enable?  However I'm not sure what the `cmd vars(:enable)` bit is doing.

**Comment by shthead** [comment]
FWIW I see the same issues on some of my Dell switches too. The issue seems to only occur on my N3000 series devices that are located in remote offices from where the poller is and the latency is higher (latency is 100ms-450ms). I don't have the same issue with any of my N3000 devices where the latency is only a few ms. I also don't have the issue for any of my other devices (mix of Juniper and other Dell + Force 10 devices), eg. I have a bunch of M6220's at remote and local sites which use this same powerconnect module which do not see the same problem.

For my environment, I have almost 200 devices being polled. From gem list:

oxidized (0.21.0, 0.20.0)
oxidized-script (0.5.0, 0.4.0)
oxidized-web (0.9.3, 0.9.2, 0.9.1)

As with the OP I see changes like:
```
 ! 
+! level14-stack#show version
+! 
 ! Machine Description............... Dell Networking Switch
 ! System Model ID................... N3048
 ! Machine Type...................... Dell Networking N3048
```
And:
```
 ! 
-! level14-stack#show version
-! 
 ! Machine Description............... Dell Networking Switch
 ! System Model ID................... N3048
 ! Machine Type...................... Dell Networking N3048
```

I will also try using `no logging console` on my N3000 devices to see if that helps.

**Comment by candlerb** [comment]
Things have been better since turning off console logging, however I've just had an example of another spurious message:

```
diff --git a/wrn-sw10g1.int.example.net b/wrn-sw10g1.int.example.net
index f4ae1fd..b9156c8 100644
--- a/wrn-sw10g1.int.example.net
+++ b/wrn-sw10g1.int.example.net
@@ -1,4 +1,6 @@
 ! 
+! wrn-sw10g1.int.example.net#show version
+! 
 ! Machine Description............... Dell Networking Switch
 ! System Model ID................... N1548
 ! Machine Type...................... Dell Networking N1548
```

It appears that oxidized has captured the echo-back of the command line in this case - both the prompt and the command.

**Comment by laf** [comment]
Yeah I see this on some cisco ios based devices as well.
